### PR TITLE
1917 - Converted Area Chart to Playwright

### LINKED ISSUE #1917: Tests: Convert Area Chart Tests
Describe the task
Convert Area Chart tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-area-chart to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-area-chart/ids-area-chart.spec.ts

Additional context
N/A

### PR DESCRIPTION
**Pull request by n-ace-ancog**
**Explain the details for making this change. What existing problem does the pull request solve?**
Converted and added Area Chart tests to Playwright script.

**Related github/jira issue (required)**:
Closes #1917 

**Steps necessary to review your pull request (required)**:
Pull this branch, build, and run the app
Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Review by ericangeles — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@n-ace-ancog looks like some of the tests work differently when running on the server https://github.com/infor-design/enterprise-wc/actions/runs/8724121135/job/23933972993?pr=2236#step:11:166

Maybe they can be improved?

**Comment by n-ace-ancog** [comment]
Added a fix on the failing test with treemap in this PR.

**Review by ericangeles — CHANGES_REQUESTED** [review]
It's still failing in the build 

https://github.com/infor-design/enterprise-wc/actions/runs/8731756266/job/23957676734?pr=2236#step:11:334

**Comment by tmcconechy** [comment]
@ericangeles @n-ace-ancog  looks good now 👍🏻

**Review by ericangeles — APPROVED** [review]
Good stuff! 🍌

**Pull request merged**
