### PR TITLE
2559 - Made swaplist search area sticky on scroll

### LINKED ISSUE #2559: IdsSwaplist: Searchfield is included in scrolling
If you scroll down through the items in swaplist, the search field is also included with the items. Thus, if you scroll down enough, the search field will be hidden.

**Describe the solution you'd like**
It would be great if the search field stays in position when you scroll through the swaplist items.

swapsearch

Label is team: M3

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Made swaplist search area sticky when scrolling

**Related github/jira issue (required)**:
Fixes #2559 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-swaplist/search.html
- scroll the first area with enough items to scroll and ensure the search is now sticky
- check themes (dark especially since its a different color)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image
image
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The search box is now sticky, but the drag indicator seems to overlap if the mouse is hovering in the first item then scrolled slowly upwards.

image

https://github.com/user-attachments/assets/fe576377-195c-4c2b-90dd-8dc9679224bc

**Comment by tmcconechy** [comment]
@n-ace-ancog I fixed that issue (on another PR we changed the Icon and it seems to work with the new one)

**Review by n-ace-ancog — DISMISSED** [review]
Now working on my end.

https://github.com/user-attachments/assets/f3caa49b-4d53-41d5-861f-06c3df693d16

**Pull request merged**
