### PR TITLE
1198 - Add fix for scrollRowIntoView

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

After triggering an infinite-scroll, IdsDataGrid.ScrollRowIntoView() was not going the the expected row.
This PR fixes IdsDataGrid.ScrollRowIntoView() so that it finds correct row after infinite-scrolling.
The main fix seems to be removing one `RAF`. This can lead to an increase in `Forced reflow while executing JavaScript` warnings but the trade off is proper functionality.

Replaces https://github.com/infor-design/enterprise-wc/pull/1213 if approved.

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-wc/issues/1198

**Steps necessary to review your pull request (required)**:
- on each page:
http://localhost:4300/ids-data-grid/virtual-scroll-infinite-scroll.html
http://localhost:4300/ids-data-grid/virtual-scroll-infinite-scroll-m3.html
http://localhost:4300/ids-data-grid/infinite-scroll.html
- scroll down until you hit the bottom to load all data
- run this sequence and see it hits the right row (zero based index) and ensure it goes to the right row

```
document.querySelector("#data-grid-1").scrollRowIntoView(0)
document.querySelector("#data-grid-1").scrollRowIntoView(300)
document.querySelector("#data-grid-1").scrollRowIntoView(200)
```
- scan for warnings in the console and see if it seems acceptable
- also test http://localhost:4300/ids-data-grid/m3-features.html and notice when scrolling down it doesn't go in an infinite loop (found during testing https://github.com/infor-design/enterprise-wc/issues/1238)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by EdwardCoyle — DISMISSED** [review]

**Comment by clayinfor** [comment]
hey @tmcconechy , just a heads up that I am seeing some issues with this PR:

https://user-images.githubusercontent.com/93789065/233101484-1da3d1b1-2974-4e0d-8090-5bb58992792d.mov

**Comment by tmcconechy** [comment]
i think its wierd it tries to get 33 more rows "sometimes". Maybe we can just max out the example at 300 and be done with it? Seems like the issue is when you scroll down you get 300 rows but then go back up and down again then you get 33 rows so its then off by 33 rows?

@clayinfor not understanding that example logic, maybe you can adjust?

**Comment by danielortiz1982** [comment]
@tmcconechy and @clayinfor 
This looks great so far. When I navigate to row `205` the entire table seems to blank out completely. Thinking out loud here, could be the `recycling` scripts. 

Screen Shot 2023-04-21 at 10 29 45 AM
https://www.loom.com/share/776c53086a10488cbd01bc477f710eb2

**Comment by clayinfor** [comment]
hey @tmcconechy, I just pushed a change that's hacky but it gets things mostly there.

**Review by tmcconechy — COMMENTED** [review]
Looks good to me! But i cant approve the PR since i started it @clayinfor @danielortiz1982 @EdwardCoyle @deep7102 @jdilag

**Comment by jdilag90** [comment]
infscroll-missing

On initial load of http://localhost:4300/ids-data-grid/infinite-scroll.html, if the browser window is larger than the table, no scroll appears. You can test by setting your browser zoom to 50% or to a zoom value small enough for the table to be smaller than the browser window, and then reloading the example page.

**Review by deep7102 — COMMENTED** [review]
All other looks good, only that zoom thing.

**Review by deep7102 — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Review by clayinfor — APPROVED** [review]

**Pull request merged**
