### PR TITLE
1140 - Fix build and import issues

### LINKED ISSUE #1140: Build: Some imports Treeshaking Out
**Describe the bug**

Something strange is happening that is unexpected with tree shaking. Imports added with `import '../ids-menu-button/ids-menu-button';` format should be included but they seem to be tree shaking out in the build.

**To Reproduce**

1. Make edits to this example https://github.com/infor-design/enterprise-wc-examples/tree/main/plain-html
2. Load Page
3. See error in the console about missing menu button

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title>IDS Tag Component</title>
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="Cache-control" content="max-age=31536000">
  <script type="module" src="/node_modules/ids-enterprise-wc/components/ids-container/ids-container.js"></script>
  <script type="module" src="/node_modules/ids-enterprise-wc/components/ids-tag/ids-tag.js"></script>
  <script type="module" src="/node_modules/ids-enterprise-wc/components/ids-alert/ids-alert.js"></script>
  <script type="module" src="/node_modules/ids-enterprise-wc/components/ids-text/ids-text.js"></script>
  <!--<script type="module"
    src="/node_modules/ids-enterprise-wc/components/ids-menu-button/ids-menu-button.js"></script>-->

  <script type="module" src="/node_modules/ids-enterprise-wc/components/ids-theme-switcher/ids-theme-switcher.js"></script>
</head>
<body>
  <ids-container locale="en-US">
    <ids-theme-switcher></ids-theme-switcher>
    <ids-tag color="error">Error Tag</ids-tag>
    <ids-alert icon="error"></ids-alert>
    <ids-text translate-text="true">Legend</ids-text>
  </ids-container>
</body>
</html>
```

Additionally debugging doesnt work on the `npm run build:dist` this needs further testing.

**Expected behavior**
All included imports should be not tree shaking out, should be possible to debug with `npm run build:dist` debug package.

**Additional context**
- explained pretty well on https://esbuild.github.io/api/#tree-shaking
- side effects the issue https://esbuild.github.io/api/#tree-shaking-and-side-effects
- force imports to be included or should we disable tree shaking?
- source map options to explore https://esbuild.github.io/api/#sourcemap for the debugging issue

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**
Updates the dependency tree ~ most notably adds a new esbuild that fixes issues with import order in the chunks. This caused some imports to not work in the prod build.

**Related github/jira issue (required)**:
Fixes #1140 

**Steps necessary to review your pull request (required)**:
- pull and run `npm i`
- then `npm run build:dist` or `npm run build:dist:prod`
- clone https://github.com/infor-design/enterprise-wc-examples
- copy build/dist/development or build/dist/production to plain-html/node_modules/ids-enterprise-wc in the examples clone
- then cd into   plain-html/ and run `npm run start`
- test http://localhost:8000/ and it should have a working calendar, with no errors

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
build/rebuild/copied a few times, seeing some errors in the console on http://localhost:8000/
image

**Comment by tmcconechy** [comment]
@andriivarhanov what are you doing to get that? Maybe we are missing another import? Also did you make sure to do `rm -rf node_modules && npm i` first?

**Comment by andriivarhanov** [comment]
@tmcconechy yeah, removed `node_modules` before `npm i`, installed modules, made build, checked chunks hash, copied 
 `build/dist/production` to `plain-html/node_modules/ids-enterprise-wc`, checked chunks hash to be sure it's the same as in  `build/dist/production`, `npm start` in `/enterprise-wc-examples/plain-html`

let me try it again, and maybe with `build/dist/development`

**Comment by andriivarhanov** [comment]
@tmcconechy same with `build/dist/development`, the only thing I did differently from the steps in the description is I removed `build` folder before `npm run build:dist` or `npm run build:dist:prod`

**Comment by tmcconechy** [comment]
@andriivarhanov good catch. I fixed some imports. Not sure why i didnt see it. Please try again.

**Comment by andriivarhanov** [comment]
@tmcconechy works now on  http://localhost:8000, but build is failing

**Comment by tmcconechy** [comment]
ok @andriivarhanov think i got it now

**Review by andriivarhanov — APPROVED** [review]
looks good, I think build will not fail

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
