### PR TITLE
930 - Improve IdsToolbarMoreActions menu

### LINKED ISSUE #930: IdsToolbar: Not able to click nested menu item when overflowed
**Describe the bug**
Not able to click (or navigate by keyboard) on a nested menu (sub menu) item, if the menu has been automatically moved  to the more button (haven't tested if it works when then nested menu was purposely added to the more menu e.g. you only have a more button with items).

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-toolbar/overflowed.html
2. Make screen size smaller so that `Text Button 1` and `Menu Button 2` is hidden in the more menu.
3. Try to click the `Menu Button 2 > More Items > Item x` now
4. Then menu will hide when trying to click the nested menu, and you cannot use keyboard navigation for the overflowed menu. Also, the `has-icon` class has now been added, which applies wrong styling I would assume.

**Expected behavior**
The menu should not be closed and one should be able to click the menu items and be able to use keyboard navigation.

**Version**
- ids-enterprise-wc: 1.0.0-beta.1? (couldn't see a version on the html, but whatever is on main.wc.design today)

**Screenshots**
wc-toolbar

The class `has-icon` is also added, even though there is no icon, which gives it wrong styling:
image

**Platform**
 - Infor M3/Experience Designer
 - OS Version:  osMonteray
 - Browser Name: Firefox
 - Browser Version: 104.0.2

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR makes a few improvements to the IdsToolbarMoreActions component (primarily in the IdsPopupMenu part):
- Nested submenus inside the More Actions menu no longer close when activated
- Keyboard functionality to IdsPopupMenu overall has been restored
- Fixed hover/mouseover highlighting behavior to work correctly when mixed with keyboard control of the menu (you can now interchangeably navigate menus by dragging the mouse to a menu item, then use the keyboard to navigate away like what was possible in 4.x)
- Fixed premature menu closing in some cases when moving the mouse from a top-level menu to a submenu
- Made menu icon spacing/alignment depend on whether or not any menu icons are visible (updates when toolbar overflow changes)

**Related github/jira issue (required)**:
Closes #930

**Steps necessary to review your pull request (required)**:
Pull/Build/Run, then test the following cases:

**Test submenu accessibility:**
- Open http://localhost:4300/ids-toolbar/overflowed.html
- Shrink the browser window so that only "Icon Button 4" and "Text Button 5" are displayed, and other buttons are pushed to overflow
- Open the "..." menu > "Menu Button 2" > "More Items".  The menu should be accessible.

**Test keyboard functionality:**
- Open http://localhost:4300/ids-toolbar/overflowed.html and shrink the window similar to above
- Use the tab key to navigate to the IdsToolbar, then use the arrow keys to navigate to the "...".  Press enter, and use the arrow keys to navigate the more actions menu.  Use the right arrow to open submenus, and the left arrow to close submenus.  Navigation with keyboard should make sense

**Test highlighting:**
- Open http://localhost:4300/ids-toolbar/overflowed.html and shrink the window similar to above
- Use the keyboard to open the menu, navigate two menu items down, and press "escape" to close
- Re-open the menu with Enter or Spacebar.  The item highlighted should be the same as when you closed

**Test keyboard/mouse nav mixing**
- Open http://localhost:4300/ids-toolbar/overflowed.html and shrink the window similar to above
- Use the mouse to open the more actions menu, and pick any menu item to hover
- Without closing the menu, switch to keyboard navigation.  The next/previous highlighted items should be relative to the mouse-hovered menu item.

Also, smoke-test the following examples to make sure they are all still working:
- http://localhost:4300/ids-popup-menu/example.html
- http://localhost:4300/ids-popup-menu/selected-state.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — CHANGES_REQUESTED** [review]
All looks good!

http://localhost:4300/ids-toolbar/overflowed.html
-see js error showing on load, might need some checks

image

**Review by andriivarhanov — APPROVED** [review]
looks good, no issues found

**Review by tmcconechy — APPROVED** [review]
Looks good to me too 👍🏻

**Review by deep7102 — APPROVED** [review]
Looks good, Thanks! @EdwardCoyle

**Pull request merged**
