### PR TITLE
2429 - Loading indicator fixes

### LINKED ISSUE #2429: IdsLoadingIndicator: All loading indicator types are circular
**Problem**

On setting linear type loading indicator, it shows circular indicator.
Also while trying different types of loading indicators : linear, circular, sticky - All of them are showing circular indicators only.

**To Reproduce**

1. Go to http://localhost:4300/ids-loading-indicator/example
2. Check the different types of loading indicators
3. All will show in circular motion

**Expected behavior**

Correct loading indicator should be shown as per the type : linear 
NOTE: The behaviour in hosted ids demo app is correct : [example](https://main.wc.design.infor.com/ids-loading-indicator/example.html)

**Version**
ids-enterprise-wc : 1.2.0

**Screenshots (From local)**

image

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes a few properties that made it such that the angular example showed all circular indicators.

**Related github/jira issue (required)**:
Fixes #2429 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-loading-indicator/example
- on the first indicator add `linear` it should update  to that type
- reload
- on the first indicator add `progress="20"` it should stop and go to 20
- reload
- on the first indicator add `generative-ai` it should update to that type
- test the angular page by running `npm run build:dist` and copying it over to that project (pull to get latest changes and run and go to http://localhost:4300/ids-loading-indicator/example
- should look the same as the other page minus the spinboxes (all types should be correct)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by andrivarhanov — DISMISSED** [review]

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The example page is now working, but setting `linear` to `true` is not working

https://github.com/infor-design/enterprise-wc/assets/156752175/48636b5b-3f01-4f71-ba6b-d44fc5765af5

**Comment by tmcconechy** [comment]
@n-ace-ancog nice catch. I fixed that as well.

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Setting to `linear` is working, but returning it to false fails to return to a circular model.

https://github.com/infor-design/enterprise-wc/assets/156752175/c8a34000-49c7-4afb-ae10-f3af051ccd4d

image

Also, once `generativeAi` is set to `true` then `false` it doesn't return to a circular model (is this expected?)

Lastly, do the following:
1. `document.querySelector('ids-loading-indicator').generativeAi = true`
2. `document.querySelector('ids-loading-indicator').generativeAi = false`
3. `document.querySelector('ids-loading-indicator').linear = true`

Modes models stack side by side
image

**Comment by tmcconechy** [comment]
@n-ace-ancog I fixed those cases as well

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
The fix is working, but setting `generativeAi` to `true` then `false` hides the loading indicator.

**Steps to replicate**
1. Enter `document.querySelector('ids-loading-indicator').generativeAi = true`
2. Enter `document.querySelector('ids-loading-indicator').generativeAi = false`
3. Component is hidden

https://github.com/infor-design/enterprise-wc/assets/156752175/0f7d6b5a-ef9b-4fc6-a861-9c7f1412ed18

**Comment by tmcconechy** [comment]
@n-ace-ancog that final case is also now fixed 👍🏻

**Review by n-ace-ancog — APPROVED** [review]
Now working on my side.

https://github.com/infor-design/enterprise-wc/assets/156752175/aec580d7-2877-474d-9edd-26ea7f4666a8

**Pull request merged**
