### PR TITLE
1181-IdsColorPicker multiple change events

### LINKED ISSUE #1181: IdsColorPicker: Change Event fires too many times
**Describe the bug**
A clear and concise description of what the bug is. Check this on other components ids-input -> ids-trigger-field -> this

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-color-picker/example.html
2. Add this to the console: 
```
var picker1 = $('ids-color-picker');
picker1.addEventListener('change', () => console.log(picker1.value))
```
3. Click on first picker and pick a value
4. See problem in console

**Expected behavior**
For a selection change should fire only once.

**Additional context**
Needed for #1118

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixes `change` firing multiple times upon color selection. 
I removed the `triggerEvent('change')` within color-picker since it extends `IdsTriggerField` which already fires a change event when the value changes

**Related github/jira issue (required)**:
Closes #1181 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm install`, `npm run start`
2. Go to http://localhost:4300/ids-color-picker/example.html
3. Add this to console
```
const picker1 = $('ids-color-picker');
picker1.addEventListener('change', (evt) => console.log(evt.detail.value));
```
4. Select a color in first ids-color-picker
5. Check that listener fires and only once

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Do see one thing but i dont think its a major issue (might even be unavoidable?)

- tab to first picker after establishing the event handler
- type emerald-10 -> after typing change fires
- tab out -> change fires again

**Comment by jdilag90** [comment]
@tmcconechy 

* Updated color-picker to use IdsTriggerField in its template
* Default/Advanced ColorPicker should have a `change` event that only fires once
* ColorPicker now also emits `input` events

**Review by deep7102 — COMMENTED** [review]
Event looks good, fires only once 🍌 

Saw another issue might not related to this fix, color swatches misalliances in small view
- Resize view port around 500px -to- 550px wide
- Open picker, and see color swatches misalliances

image

**Comment by tmcconechy** [comment]
@deep7102 i think i have that fixed with the border size already on my branch for themes. so maybe consider it unrelated for now (even tho it looks a bit ugly)

**Review by deep7102 — APPROVED** [review]

**Review by danielortiz1982 — COMMENTED** [review]
Gave this PR a quick glance, looks good to me however @EdwardCoyle or @deep7102 should have a look to see if I missed something. A few notes below...

1. Change target from `any` to maybe `htmlElement` or `IdsElement` line => 466, const target: any = event.target;
2. Not too sure about line => 513 I don't think you need that return statement. 

Not a show stopper just some recommendations from a quick pass... Looks good @jdilag

**Pull request merged**
