### PR TITLE
#1922 - Ids color picker conversion

### LINKED ISSUE #1922: Tests: Convert Color Picker Tests
Describe the task
Convert Color Picker tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-color-picker to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-color-picker/ids-color-picker.spec.ts

Additional context
N/A

### PR DESCRIPTION
**Pull request by jbrcna**
**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes #1922 

**Steps necessary to review your pull request (required)**:

Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [ ] A note to the change log.

**Additional Context**
I have two issues that I need help with.
``` diff
- colorpicker.triggerEvent('click', colorpicker.container) seems to be not working
- Error: locator.evaluate: TypeError: colorpicker.addOpenEvents is not a function
```

### CODE REVIEW

**Comment by tmcconechy** [comment]
@jbrcna 

- please check lint errors
- i think you can skip the test about `addOpenEvents` since that should be called internall
- to trigger a click did you try the idea of:

```
const locator = await page.locator('ids-tag ids-icon[icon="close"]').first();
await locator.click();
```

**Comment by jbrcna** [comment]
thank you for your inputs @tmcconechy .
what is this? `ids-tag ids-icon[icon="close"]` is this to close the picker? . no element is found with this

ok I will try to do this (`colorpicker.triggerEvent('click', colorpicker.container) ` ) in a different way. I just thought that trigger event has something to do with the coverage. 

Also, my eslint extension seems to not work. I've tried to restart vscode

**Comment by n-ace-ancog** [comment]
For the `colorpicker.triggerEvent('click', colorpicker.container)`, you can still use it but only side a `page.evaluate` or `locator.evaluate`. The reason behind is that `colorpicker.container` object only exists in the browser context and not in Playwright.

```ts
const element = page.locator('ids-color-picker');
await element.evaluate((colorpicker: IdsColorPicker) => {
  colorpicker.triggerEvent('click', colorpicker.container);
});
```

If you want it to work in the Playwright context, you need to locate the element of the container using `page.locator` then trigger the event.

```ts
// this is just pure example
const element = page.locator('ids-color-picker');
const container = element.locator('div');

container.dispatchEvent('click');
```

**Comment by tmcconechy** [comment]
@jbrcna my example about tag was just an example from there. Need to adapt it to the color picker basically..

```
const locator = await page.locator(<selector to the thing you want to click>).first();
await locator.click();
```

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]

**Comment by tmcconechy** [comment]
@jbrcna try to check in visual code at the problems and output tab on the bottom? Maybe there is some error?

**Pull request merged**
