### PR TITLE
2457 - Remove redundant `recentlyHidden` property

### LINKED ISSUE #2457: IdsPopupmenu: remove recentlyHidden flag
**Describe the bug**
A popupmenu on breadcrumbs is not opening the second time that it opened in a production system. The recentlyHidden flag is staying true, which is preventing the showIfAble method being called. Could we try removing this flag?

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Landmark reported an issue in prod instances where the popup would not open. We found it was related to this flag so attempting to remove as it doesnt seem needed

**Related github/jira issue (required)**:
Fixes #2457

**Steps necessary to review your pull request (required)**:
- retest all examples on http://localhost:4300/ids-popup-menu/ and http://localhost:4300/ids-menu-button
- should not see any difference / in particular try reopening the menus
- test filter row http://localhost:4300/ids-data-grid/filter.html

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jdilag90 — DISMISSED** [review]

**Comment by jbrcna** [comment]
this is working as expected
image

image
image

there is an error in console



just a minor observation, the icon is cut off
image

**Review by glenlieorillo — COMMENTED** [review]
Menus are working as expected.

**Popup Menu**

image

image

image

image

image

image

image

image

image

image

image

**Menu Button**

image

image

_@tmcconechy I noticed there's too much space between `check` and text._

image

image

image

image

image

http://localhost:4300/ids-data-grid/filter.html

_I also noticed the cut-off icon, as mentioned by @jbrcna._

image

**Comment by tmcconechy** [comment]
@glenlieorillo lets make a new issue for the space issue

**Comment by glenlieorillo** [comment]
> @glenlieorillo lets make a new issue for the space issue

Created an issue for this bug. Kindly refer to this issue: https://github.com/infor-design/enterprise-wc/issues/2495

**Pull request merged**
