### PR TITLE
139 - ids spinbox wc

### LINKED ISSUE #139: IdsSpinBox: Add new web component
Add the spinbox component https://main-enterprise.demo.design.infor.com/components/spinbox/list

**Phase 1 Features (MVP)**
- Settings min/mask and step
- Use the ids-mask mixin for masking
- Use the ids-trigger-field maybe - expanding it to have a left and right button 
- Add all the states  for inputs (placeholder/readonly/dirty/enabled/disabled/required) like the other inputs using the mixins (Deepak Created) see textarea/inputs
- keyboard/ accesibility

**Future Features (Not Now)**
- Autocorrect on blur
- Attributes/Internal IDs
- Comb through edge cases in https://main-enterprise.demo.design.infor.com/components/spinbox/list

**Suggested Internal Markup**
```js
<ids-spin-box step="2" min="10" max="20" value="5" label="Select a number" placeholder="10 - 20"></iis-spin-box>
```

**Suggested Dependencies**
- ids-trigger-field
- ids-input
- ids-mask-mixin

**Settings**
- step (string / live)
- max (string / live)
- min (string / live)
- (all input settings for states)

**Events**
- change
- native events for inputs (see input)

**Other**
Pass the following checklist ordered in priority (some may be left for later) https://github.com/infor-design/enterprise-wc/blob/main/doc/CHECKLIST.md

### PR DESCRIPTION
**Pull request by rob2d**
**Explain the details for making this change. What existing problem does the pull request solve?**

Adds IdsSpinbox (Phase 1) and base attributes.

Misc: also fixes:

a small potential issue with ids-keyboard-mixin where we sub on an array as the key vs the events (since we do not actually group key combos or use it in this manner in other components -- the fix was 2 lines so figured small enough to include here)

**Related github/jira issue (required):**

Closes #139

Steps necessary to review your pull request (required):

pull this PR branch locally and run environment (139-ids-spinbox)
visit http://localhost:4300/ids-spinbox/
ensure functionality listed at #139 for Phase 1 is implemented.

**Included in this Pull Request:**

- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by rob2d** [comment]
@tmcconechy  & @deep7102 thanks for the useful feedback on the previous PR. Sorry to not realize this but if you edit a closed PR in a certain way, it can't be re-opened. So just for reference the review on previous PR can be found @ #206 .

Tried to be thorough to address all comments, except for:
> @deep7102 - Type in 10 then click on and button +/- value got reset

In this case I need to add some custom key-down listener/possibly blur, but I did fix a bunch of other edge cases on value. Based on suggestion of scope on the issue I hadn't done this yet just to get another round.

And:

> @tmcconechy hold and press a spinbox ... hold down on the + button with the mouse

On this feature I put a `TODO.md` note here.

Will see if both of these are feasible in current but we're also using different patterns + WC so may be muddy. Will be addressing while this is open again here time-boxed to this evening (after investigating failing CI build).

**Comment by rob2d** [comment]
@deep7102 @tmcconechy should be ok to look at again. 

Was able to get value cycling and also made the timing speed up a little as you hold down the mouse on the increment/decrement buttons, but lot of gotchas for mousedown=>up tests and they needed rework to get any useful coverage; figured since adding helpers to finally move the other time-related helpers as so we can DRY other stuff later but was getting out of scope to continue it.

@deep7102 addressed some things on rounding the value to the step and other edge cases but the specific key down on numeric vs just handling change before button isn't there since above required some time (also a little hesitant on the consideration on this since if it's auto validating it may be frustrating for a user e.g. typing "35" w/ step == 5. Would jump from 3 to 5... so not impossible just may take time to not add frustrating side effects if done straightforwardly).

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
@rob2d Looks great! Very nice work 👍

**Review by tmcconechy — DISMISSED** [review]

**Review by deep7102 — APPROVED** [review]
Thanks! @rob2d
looks great 🍌

**Comment by tmcconechy** [comment]
Since every one approved im merging

**Pull request merged**
