### PR TITLE
1046 - Implement new IdsButton designs / Add destructive button states

### LINKED ISSUE #985: Button - new type 'danger'
**Is your feature request related to a problem or use case? Please describe.**
We'd like to have a 'danger' type button. We want to use it before deleting crucial customers data for example from S3 buckets etc.

**Describe the solution you'd like**
Probably red backgrounded button (ruby-60/ruby-80 on hover?).
image

**Describe alternatives you've considered**
We can use css restyling, something like this works just fine
```
ids-button.danger-button::part(button) {
  background-color: var(--ids-color-palette-ruby-60);
  border-color: var(--ids-color-palette-ruby-60);

  &:hover {
    background-color: var(--ids-color-palette-ruby-80);
  }

  &:focus {
    box-shadow: 0 0 0 2px var(--ids-color-palette-white), 0 0 0 3px var(--ids-color-palette-ruby-60), 0 0 4px 3px var(--ids-color-palette-ruby-60);
  }
}
```

**Additional context**
Data Fabric application

### LINKED ISSUE #1046: IdsButton: New Designs
**Describe the bug**
Implement new desiigns on https://github.com/infor-design/enterprise/pull/7024
- includes button style changes
- trigger buttons
- destructive action

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR updates IdsButton and all dependencies to use the new Figma designs provided in #1046.  This PR also implements new button types `btn-tertiary-destructive` and `btn-primary-destructive` to add new "Destructive" style designs (this is described in the designs and requested on #985)

**Related github/jira issue (required)**:
Closes #985
Closes #1046

**Steps necessary to review your pull request (required)**:
Pull/build/run.  Then check the new example page against the Figma designs provided in #1046.  The new example page reflects the layout of the 4.x component page:
- http://localhost:4300/ids-button/example.html

See the original matrix page and "alternate" variants with added destructive types:
- http://localhost:4300/ids-button/matrix.html
- http://localhost:4300/ids-button/variant-alternate.html

Smoke test other usage of IdsButton to ensure styles are correct:
- http://localhost:4300/ids-app-menu/example-footer.html (uses color-variant "alternate")
- http://localhost:4300/ids-editor/example.html (uses color-variant "alternate-formatter")
- http://localhost:4300/ids-header/toolbar.html (this will change when we change the header colors, but it uses color-variant "alternate" and the colors should make sense, for now)
- http://localhost:4300/ids-message/types.html (activate modals to ensure their inner-buttons are correct)
- http://localhost:4300/ids-search-field/example.html
- http://localhost:4300/ids-spinbox/example.html (should remain the same)
- http://localhost:4300/ids-swipe-action/example.html (need to test on a mobile device or browser tools)
- http://localhost:4300/ids-toggle-button/example.html
- http://localhost:4300/ids-toolbar/example.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

@hohnzy

**NOTE TO REVIEWERS**: Lots of Percy tests are being marked as changed, most likely because this PR alters the `ids-container` background colors for dark/contrast modes, which previously did not match their 4.x counterparts.  Please look at these carefully and ensure there aren't also issues with buttons.

### CODE REVIEW

**Comment by jdilag90** [comment]
These new buttons look nice!

I think the red primary destructive button is missing the red box shadow around it in focus state. 
There's one illustrated in the [figma](https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=932%3A1441&t=myIFgNGPajHnkHWY-0) under "Destructive Actions" for primary focus state

Small nitpicky thing, the Primary Destructive and Tertiary Destructive buttons in matrix/variant examples overlap when browser is around 1000px

**Review by tmcconechy — CHANGES_REQUESTED** [review]
A few things would like to double check (i didnt look at the design but looked at the EP version).

- http://localhost:4300/ids-editor/example.html hover on buttons seems to have changed
- http://localhost:4300/ids-button/example.html in dark mode should the .. state be azure or white?
- we probably do need to do something with buttons in http://localhost:4300/ids-message/types.html but this a design question @inforandy 
- on http://localhost:4300/ids-toolbar/example.html the hover state box shadow looks square (nit pick)
Screenshot 2023-01-05 at 2 04 58 PM

**Comment by EdwardCoyle** [comment]
@tmcconechy @jdilag90 I think I've addressed all the comments on this one, except for this:

> http://localhost:4300/ids-button/example.html in dark mode should the .. state be azure or white?

I think you mean the focus state?  I think the normal focus state remains azure (but it's a lighter one to contrast the dark).  In the alternate variant the border/shadow become white in most cases: http://localhost:4300/ids-button/variant-alternate.html

**Review by jdilag90 — DISMISSED** [review]

**Comment by EdwardCoyle** [comment]
@jdilag90 I pushed a minor change to the margin of some buttons because I realized the alignment was a bit off... can you re-review?

**Review by tmcconechy — APPROVED** [review]
Looks good. Will approve percy as well.

**Review by jdilag90 — APPROVED** [review]

**Pull request merged**
