### PR TITLE
2582 - IdsDropdown position in tabs

### LINKED ISSUE #2582: IdsDataGrid: Follow up position issue (tabs with toolbar with grid)
**Describe the bug**
As a follow up to  https://github.com/infor-design/enterprise-wc/pull/2512 it was found 

**To Reproduce**

1. Go to a branch a made with new example `2582-dropdown-position-tabs`
2. `npm run start`
3. Click dropdown on last column
4. see its not connected to the cell

**Screenshots**
Screenshot 2024-07-11 at 2 55 13 PM

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fix position of dropdown in datagrids in tabs

**Related github/jira issue (required)**:
Closes #2582 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Test these example pages
3. http://localhost:4300/ids-dropdown/example.html
4. http://localhost:4300/ids-dropdown/sizes.html (test all sizes)
5. http://localhost:4300/ids-dropdown/in-action-panel.html
6. http://localhost:4300/ids-data-grid/in-tabs.html
7. http://localhost:4300/ids-data-grid/editable.html
8. http://localhost:4300/ids-dropdown/in-modal.html

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
Working now as expected on my end.

https://github.com/user-attachments/assets/87495c0a-ecf6-4396-b438-56e9fdf48959


https://github.com/user-attachments/assets/b914af24-df7e-4ca3-9553-32d563269ef3


https://github.com/user-attachments/assets/897131e7-6ae0-412c-b7b5-557a4d00b9a9


https://github.com/user-attachments/assets/43006743-59ae-436b-998f-57f3f7c56924


https://github.com/user-attachments/assets/60e2d177-a83f-44ab-afd6-f6ec406cbf22


https://github.com/user-attachments/assets/fdd0d97e-3a1f-42b9-ae40-d2bed91f5ec9

**Review by jbrcna — APPROVED** [review]

**Comment by jbrcna** [comment]
this is working as expected. However, in Safari the container moves up a bit when you open a dropdown.
Also, after opening all the dropdowns, the first dropdown cannot be open. (Safari)
http://localhost:4300/ids-dropdown/example.html
Large GIF (508x870)

http://localhost:4300/ids-data-grid/in-tabs.html
image


perhaps not related but just noting for reference.
http://localhost:4300/ids-dropdown/in-action-panel.html - when you open the dropdown using space, you have to press Enter key twice to select.

**Review by tmcconechy — COMMENTED** [review]
@jdilag90  

Go to:
1) http://localhost:4300/ids-dropdown/in-action-panel.html and resize the page around this size:

Screenshot 2024-07-12 at 2 24 50 PM

2)Also on http://localhost:4300/ids-data-grid/editable.html if you set each of the four row sizes one by one then open and close the dropdowns in some of the row heights you see the text and icon open in different positions

**Comment by jbrcna** [comment]
image

**Comment by tmcconechy** [comment]
@jdilag90 can you check into @jbrcna 's comment? Did that last commit intend to fix? Also a change log conflict.
And can you add the change log to section 1.4.0?

**Comment by tmcconechy** [comment]
@jdilag90 also can you sync main and put this in 1.3.1 change log so it will reflect in the right version? Thanks

**Comment by jdilag90** [comment]
@tmcconechy @jbrcna I added a resizeObserver to fixed dropdowns so the dropdown popups should resize with dropdown container now. The resize handler is debounced for the sake of performance, so you'll notice a slight lag when resizing.

**Review by tmcconechy — DISMISSED** [review]

**Review by jbrcna — APPROVED** [review]
awesome!

image
image
Large GIF (1372x764)

**Comment by jbrcna** [comment]
Large GIF (1372x764)

**Review by tmcconechy — APPROVED** [review]

**Comment by jdilag90** [comment]
@tmcconechy can we close this for now and clean up in the future. 
There is this new Popover and CSS Anchoring API being added soon which could solve all these use cases.
Needs to be explored

https://developer.mozilla.org/en-US/docs/Web/API/Popover_API
https://developer.mozilla.org/en-US/docs/Web/CSS/anchor

**Pull request merged**
