### PR TITLE
1019 - M3 example data grid page

### LINKED ISSUE #1019: IdsDataGrid: New M3 Example to show m3 features
**Task**

Make a new m3 example that shows the things m3 uses for performance testing and finding the best ways.. Call it m3-features.html maybe?

**Features to include:**

- [x] Virtual Scroll
- [x] Tree (needs #1018 )
- [ ] Editor (needs #991 )
- [x] 10-20 columns
- [x] 500-1000 rows
- [x] Filtering with no filter icons
- [x] Conditional Styles
	- [x] Can be Any color including RGB
	- [x] Individual Per Cell
	- [x] Optional Icon (needs #990)
	- [x] Hyperlink instead text for content
	- [x] Text font styles
	- [x] Style the row color
	- [x] Every Cell Can be different
	
**Sample** (but just the grid part)

image

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**
Adds an example a little like m3, with a bunch of columns and rows, virtual scroll. Filtering and some custom editors. We may add to this later including editing when merged or based on feedback.

In addition, i fixed an issue that virtual scroll did not work with filtering. Also when filtering the bottom row looked missing so moved it in the css to the bottom instead of top. May be some visual regressions to accept and test.

This is a good test page for testing virtual scroll clunkiness. cc @clayinfor 

**Related github/jira issue (required)**:
Fixes #1019 (But can add to this later including editing)

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-data-grid/m3-features.html
- try scrolling right and down
- try the filter

### CODE REVIEW

**Review by deep7102 — APPROVED** [review]
Looks good 🍌

**Review by andriivarhanov — APPROVED** [review]

**Comment by EdwardCoyle** [comment]
I'm seeing a duplication/overlapping of grid rows if you scroll down a bit from the top of the page... seems to happen with/without filtering, but I did also try filtering with "10000007" for good measure.  It doesn't appear you can click on the duplicate rows:

[IDS Data Grid Component.webm](https://user-images.githubusercontent.com/3249601/209187701-3701cec2-eb44-443f-9feb-9d7ee48c8b54.webm)

**Review by EdwardCoyle — CHANGES_REQUESTED** [review]
See above

**Comment by tmcconechy** [comment]
@EdwardCoyle that issue is fixed. caused by the placement of the empty message.

**Review by deep7102 — APPROVED** [review]
Looks good 🍌

**Pull request merged**
