### PR TITLE
244 - Added compatibility examples for all components 

### LINKED ISSUE #218: General: Add more compatibility examples
**Is your feature request related to a problem or use case? Please describe.**

We want to have more side by side examples that test that the old component library can work along side of the new component library.

**Describe the solution you'd like**
- For all ids-xxx folders in https://github.com/infor-design/enterprise-wc/tree/main/app make sure there is a compatibility example
- for reference there are two you can use https://github.com/infor-design/enterprise-wc/blob/main/app/ids-tooltip/compatibility.html and https://github.com/infor-design/enterprise-wc/blob/main/app/ids-tag/compatibility.html
- update this link to the latest version https://github.com/infor-design/enterprise-wc/blob/main/app/ids-tag/compatibility.html#L29 (4.52.0) as of this call
- For each example you can just use the simplest example in each one no need to 
- Look at the old component code and copy it over the simple example and copy a simple example from each web component examples to make the page

**Additional context**
Any issues let us know / we can report them as bugs

### PR DESCRIPTION
**Pull request by RiyaTayal20**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds compatibility examples, now titled "side-by-side", for all the components to be able to see compatibility between wc and 4.x components.

**Related github/jira issue (required)**:

Closes #218 

**Steps necessary to review your pull request (required)**:

- Pull this branch down, build and run the app
- Go to http://localhost:4300/ids-accordion/side-by-side
- Check to see that both wc and 4.x components work
- Then continue to check all the side-by-side examples for all components

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@RiyaTayal20 only one issue here and i checked through all the examples there is a lint error in many of the js files https://github.com/infor-design/enterprise-wc/pull/244/checks?check_run_id=3057888474#step:7:9

Can you fix that? I can check in with you if you have any questions on those `npm run lint` local to test

Also i pushed a fix for one shrunken text issue. ids-text needs a default

**Review by tmcconechy — CHANGES_REQUESTED** [review]
please check the lint issues

**Comment by tmcconechy** [comment]
Still a few more @RiyaTayal20  https://github.com/infor-design/enterprise-wc/pull/244/checks?check_run_id=3060291690#step:7:80

Ping me if you need help

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
Looks good for now. We can add more to this later as needed

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
Good stuff @RiyaTayal20!

**Pull request merged**
