### PR TITLE
993 - IdsDataGrid row navigation setting

### LINKED ISSUE #993: IdsDataGrid: CellNavigation with keyboard and setting
**Enhancement**

- Add setting `cellNavigation` / true or false
- when off it behaves like this https://main-enterprise.demo.design.infor.com/components/datagrid/example-key-row-select.html
- default is on as it is now
- will need to style row selection and row focus
- keyboard up/down / enter to select as the example

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
Added a row-navigation setting for data grid. Allows the user to focus the entire, not the just column, when navigating the data grid via keyboard/clicks. Changed naming to `rowNavigation` instead of `cellNavigation` , since cell navigation is the default behavior.

**Related github/jira issue (required)**:
Closes #993 

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm install`, `npm run start`
2. Go to http://localhost:4300/ids-data-grid/row-navigation.html
3. Click on any row, ensure entire row has focused styles
4. Navigate the rows via keyboard arrows, ensure the navigated rows have focused styles
5. Hit spacebar on focused rows to select them

Mixed Selection Row Navigation
1. Go to http://localhost:4300/ids-data-grid/mixed-selection.html
2. Add `row-navigation` attribute to <ids-data-grid>,  or run in console `$('ids-data-grid').rowNavigation = true;`
3. Navigated rows should have focused and activated styles

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Some minor things

1. The colors / theme(s)
2. Might be able to use `:focus-within` instead of adding the class.
3. The border looks thicker on the bottom -> maybe can use box shadows?
4. If possible the box shadow effect in addition to the borders would be nice to have (like the single cells focus state)

**Review by tmcconechy — COMMENTED** [review]
Oh also can you add a brief note to https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-data-grid/README.md#converting-from-previous-versions-breaking-changes about the setting being renamed...

**Review by clayinfor — APPROVED** [review]
Looks good 👍 ... the only thing I noticed was that pressing the Spacebar on a highlighted row selects (or deselcts) that row, but pressing the Enter/Return key does not.

**Comment by tmcconechy** [comment]
@clayinfor i think thats correct enter does other actions like click a button cell or submit. Space is the right key for selection see https://www.htmlelements.com/demos/grid/datagrid-bind-to-json/ as one example

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@jdilag minor lint error

**Review by deep7102 — APPROVED** [review]
Looks good 🍌

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
