### PR TITLE
738 - Charts Add rotated axises 

### LINKED ISSUE #738: IdsAxisChart: Rendering Axis and Rotated Labels
**Is your feature request related to a problem or use case? Please describe.**

- [x] Add Axis Labels all around
Add the ability to include an axis label on all 4 of the sides like https://main-enterprise.demo.design.infor.com/components/line/example-axis-labels.html 
We should tweak the style and make it a bit smaller.

- [x] Add support to rotate the x-axis-labels
Also add an option to rotate the labels for longer labels https://main-enterprise.demo.design.infor.com/components/line/example-rotate.html

Add tests

**Describe the solution you'd like**

Use the textWidths option and add an axisLabels setting where you can set the text and the side. Once set the textWidth options should be adjusted and the chart should render ok.

Similar for rotating labels, add a setting and the lower textWidth should be set.

**Describe alternatives you've considered**
Not including

**Additional context**
https://main-enterprise.demo.design.infor.com/components/line/example-rotate.html
https://main-enterprise.demo.design.infor.com/components/line/example-axis-labels.html

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds rotatable axises for more space to all axis charts. Included also is

- more test coverage
- fix memory leak / more leak tests on charts
- minor improvements

**Related github/jira issue (required)**:
Fixes #738

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-axis-chart/rotate-x-labels.html
- notice the axis can rotate vs  http://localhost:4300/ids-axis-chart/example.html which will be unchanged
- in the ... menu change locale to arabic or hebrew to ensure it works in RTL
- try to set the rotate-x-axis setting to another degree or zero in the DOM
- try http://localhost:4300/ids-line-chart/rotate-x-labels.html as well
- and http://localhost:4300/ids-bar-chart/rotate-x-labels.html
- notice all memory leak tests pass for charts

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by deep7102 — APPROVED** [review]
🍌 Looks Good!

**Review by EdwardCoyle — COMMENTED** [review]
@tmcconechy everything looks great, but it seems the memory leak test caught something.

**Comment by tmcconechy** [comment]
yeah its wierd as this passed before. I will look.

**Comment by tmcconechy** [comment]
Merging as was approved by three folks

**Pull request merged**
