### PR TITLE
2323 - IdsButton Notification badges

### LINKED ISSUE #2323: IdsButton/IdsMenuButton: Want to add notification badges
**Enhancement**

We have a requirement to show a notification badge on top of the ids-button and ids-menu-button.
There is an example for ids-icon https://main.wc.design.infor.com/ids-icon/notification-badge.html. 
In the same way, want to show a notification badge for the menu button and button.

**Notes** 
Team: ION

**Screen Shot**
image

**Solution** 
- add the icon notification badge settings (or better a mixin) so that you can display the badge on the icon in the button
- Do we need design feedbacK?

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
Added `badge-position` and `badge-color` settings to button component that passed to `ids-icon` component if the button has the icon

**Related github/jira issue (required)**:
Closes #2323

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-button/notification-badge.html
- check different buttons with icons and various icon notification badges

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
@andrivarhanov looks good but can you double check this added padding 

https://percy.io/00aaa841/enterprise-wc/builds/35163761/changed/1921160825?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=375%2C1280

Is it equal padding on both sides now?

**Comment by andrivarhanov** [comment]
@tmcconechy should be fixed

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Notification badges are misaligned in RTL.

image

**Review by jbrcna — APPROVED** [review]
image
image

in Chinese locale, the button seems to be larger.
image

**Review by glenlieorillo — DISMISSED** [review]
Working now as expected in RTL. Thanks, @andrivarhanov!
image

Verified @jbrcna's observation. Same result on my end.
image

**Comment by andrivarhanov** [comment]
there was an issue with shift of the last icon here

https://percy.io/00aaa841/enterprise-wc/builds/35210335/changed/1923846314?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280

and here

https://percy.io/00aaa841/enterprise-wc/builds/35210335/changed/1923845497?browser=chrome&browser_ids=59&group_snapshots_by=similar_diff&subcategories=approved&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280

should be fixed now

**Review by tmcconechy — APPROVED** [review]

**Review by jdilag90 — APPROVED** [review]

**Pull request merged**
