### PR TITLE
1498 - Added support for base href

### LINKED ISSUE #1498: Themes: Loading of ids-theme-default-light.css is failed because of lack of base href in the url
**Describe the bug**
Loading of the theme failed because of missing base href in the request URL:

image

**To Reproduce**
1. Add a base href to your Angular project https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base 
2.  After adding it the theme file will be failed with 404 status.

**Expected behavior**
When calling the theme endpoint, the URL should include the baseHref if it's presented in the application:
`${baseHref}/themes/ids-theme-default-light.css`

Example:

http://localhost:4200/process-intelligence/themes/ids-theme-default-light.css

image

**Version**

- ids-enterprise-wc: [1.0.0-beta.14]

**Additional context**
The problem occurs in the Angular 15 version.

I think the same issue occurs in the React, Vue.js frameworks. It would be nice if you could also check if we can fix it in all frameworks. Thanks!

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Changed the theme fetching logic to use any `<base>` tags if they exist in the page.

**Related github/jira issue (required)**:
Fixes #1498

**Steps necessary to review your pull request (required)**:
- go to page http://localhost:4300/ids-theme-switcher/example.html
- check the network tab in dev tools
- switch themes to dark and contrast
- in all cases theme should work and the path should be like `http://localhost:4300/themes/...`
- http://localhost:4300/ids-theme-switcher/base-href.html
- switch themes to dark and contrast
- in all cases theme should work and the path should be like `http://localhost:4300/myappui/themes/...`

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
@tmcconechy I noticed on the example with the different base path that when the page initially loads, there is no style.  However you can use the theme switcher to select a theme, and it does load successfully:

Screenshot 2023-10-10 at 8 07 13 AM

**Comment by tmcconechy** [comment]
@EdwardCoyle - what page? or is it NG? Do i need something to try?

**Comment by EdwardCoyle** [comment]
@tmcconechy sorry it's http://localhost:4300/ids-theme-switcher/base-href.html, I tried after a fresh build/cleared cache

**Comment by jdilag90** [comment]
I'm experiencing the same lack of styles on page load that Ed mentioned. I think it's the `self-managed` attr on theme switcher.

`<ids-theme-switcher mode="light" self-managed></ids-theme-switcher>`

I think we also add a line of code to resolve the `onThemeLoaded` promise we have on IdsGlobal, when theme-switcher has `self-managed` enabled. This is handled inside of IdsElement's `loadTheme()` fn
image

**Comment by tmcconechy** [comment]
@EdwardCoyle @jdilag90 -> fixed that. I dont need self-managed on this example it was copied from another example

**Review by jdilag90 — APPROVED** [review]

**Review by clayinfor — APPROVED** [review]

**Pull request merged**
