### PR TITLE
2303 - IdsTriggerButton Style issues fixes

### LINKED ISSUE #2303: IdsTriggerField: TriggerButtion: Style issues
**Describe the bug**
The following style issues are found in the TriggerField component:
1. Left button hover state in a two trigger button setup looks way off
2. Button in a read-only state has hover state
3. Setting the IdsTriggerButtton `inline` to true, makes the button border looks off

1. Go to https://main.wc.design.infor.com/ids-trigger-field/example.html
4. Hover on the 1st button of the **Two Trigger Buttons**
5. See issue
6. Hover on the button of the **Read-only Trigger Field**
7. See issue
8. Open developer's console and enter `document.querySelector('ids-trigger-field').querySelector('ids-trigger-button').inline = true`
9. See issue

**Expected behavior**
1. Button hover state does not overlap at the edge of the input box
2. Button does not have a hover state in read-only

**Version**

- ids-enterprise-wc: v1.0.1

**Screenshots**
Left button of two trigger button
image

Hover state in readonly
image

Setting IdsTriggerButton `inline` to true
image

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed style issues of the trigger button. Trigger start spacing, readonly hover, and inline border radius.

**Related github/jira issue (required)**:
Closes #2303 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-trigger-field/example.html
- hover on the 1st button of the `Two Trigger Buttons` example
- see the button doesn't overlap with the input
- hover on the button of the `Read-only Trigger Field` example
- see there is no border
- open developer's console and enter document.querySelector('ids-trigger-field').querySelector('ids-trigger-button').inline = true
- see the button border is correct in `Date Field` example

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by n-ace-ancog** [comment]
For the button in a read-only state should it be like in enterprise where nothing happens when mouse is hovered?

Something like this: https://main-enterprise.demo.design.infor.com/

https://github.com/infor-design/enterprise-wc/assets/156752175/8daa5bfe-6428-4b4a-87c2-080ade55a7d4

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Same observation with @n-ace-ancog. The button should be disabled upon hover.

https://github.com/infor-design/enterprise-wc/assets/102151352/ca0d84f0-ddbd-48f0-870b-e5a0cd28c539

**Review by jbrcna — APPROVED** [review]
great work!
image

**Review by tmcconechy — DISMISSED** [review]
Looks good for me aside from the other comments being addressed

**Review by jbrcna — APPROVED** [review]
reapproving for the hover state of disabled button
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/infor-design/enterprise-wc/assets/102151352/8c893ca7-7b1a-4e13-bd46-877886a54166

**Review by n-ace-ancog — APPROVED** [review]
Very nice!

https://github.com/infor-design/enterprise-wc/assets/156752175/f3bd80af-1821-4f1e-8a4f-335c53a2e163

image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
