### PR TITLE
861 - Add support for router link

### LINKED ISSUE #861: IdsDataGrid: Add option to override hyperlink href attribute
**Is your feature request related to a problem or use case? Please describe.**
When using the datagrid in certain frameworks the user may want to override the default use of `href`. For example, Angular makes use of a custom attribute `routerLink` to initiate navigation.

**Describe the solution you'd like**
Add an option to `ids-hyperlink` or the `ids-data-grid` hyperlink formatter to override the use of `href`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

This should be reviewed by @jmacaluso711  / angular experts. As im not sure about routerLink. https://github.com/infor-design/enterprise-wc/issues/861#issuecomment-1228923805

**Related github/jira issue (required)**:
Closes #861 

**Steps necessary to review your pull request (required)**:
- go http://localhost:4300/ids-data-grid/columns-formatters.html
- inspect the column Location With RouterLink
- since routerLink is a string processed by JS is this going to work in a real scenario?
- go to http://localhost:4300/ids-hyperlink/example.html
- this should work and `routerLink` will set the href which will feed down to the link

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
Is there a way to test this with the Angular examples?  I think the code looks OK, but not sure of the test case

**Comment by tmcconechy** [comment]
@EdwardCoyle i was hoping @jmacaluso711 would do that as he requested this. But im not sure how the grid routerLink might work (like if the routes are dynamic or something)

**Comment by jmacaluso711** [comment]
@tmcconechy @EdwardCoyle After reviewing this it seems this may not be the best approach. Since `routerLink` is a directive, if it's added in our library it won't be processed by Angular and will just be a string. Best approach might be to add a listener for click on the Angular side and use the router to navigate. Just need to make sure to document it

**Comment by tmcconechy** [comment]
Ok i wasnt sure either but didnt seem 100% right. I will close it

**Pull request closed without merging**
