### PR TITLE
1737 - dropdown typeahead not working

### LINKED ISSUE #1737: IdsDropdown: Typeahead option no longer working
**Describe the bug**

**To Reproduce**
1. Go to  https://main.wc.design.infor.com/ids-dropdown/typeahead.html
2. Click tab to the dropdown and type a -> see that search works
3. Reload and click to open the dropdown
4. Type a -> see that this doesnt work when opening it first 

**Expected behavior**

Should work same if you click to open or type to open. Also should work on https://main.wc.design.infor.com/ids-multiselect/ which it is not right now.

**Legacy version**

- https://main-enterprise.demo.design.infor.com/components/dropdown/test-reload-typeahead.html
- https://main-enterprise.demo.design.infor.com/components/dropdown/test-typeahead-automation-id.html

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Typeahead was not working on `IdsDropdown`

**Related github/jira issue (required)**:

Closes #1737 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm i && npm run dev`
2. Go to http://localhost:4300/ids-dropdown/typeahead.html
3. Type "caro" and ensure "North Carolina and South Carolina" appear in dropdown.

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
The only problem i see is that you cant resume typing. Try:

- type `ca` then wait and then try to type `ro` or backspace

This should be possible?

**Comment by tmcconechy** [comment]
@clayinfor can you also add a typeahead example to the multiselect and make sure that works?

**Comment by tmcconechy** [comment]
Adding the WIP tag for those two issues

**Review by tmcconechy — APPROVED** [review]

**Review by jdilag90 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@clayinfor FYI i created a future issue for multiselect https://github.com/infor-design/enterprise-wc/issues/1867

**Pull request merged**
