### PR TITLE
Misc - Add fixes and tests for popups and fix text color

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes three items as noted in the steps.

**Related github/jira issue (required)**:
Closes https://inforwiki.atlassian.net/browse/IDS-4665
Closes https://inforwiki.atlassian.net/browse/IDS-4660
Closes https://inforwiki.atlassian.net/browse/IDS-4264
Closes https://github.com/infor-design/enterprise-wc/issues/2561

**Steps necessary to review your pull request (required)**:

**IDS-4665**
-  go to http://localhost:4300/ids-input/example.html
- hover password/hide show button. Should not be cut off
- change to dark mode. Text in the inputs should be visibile
 
**IDS-4660**
- go to http://localhost:4300/ids-lookup/example.html
- click on first lookup to open
- should be a border again between the two buttons on the modal
- test http://localhost:4300/ids-editor/example.html by selecting text and clicking the image button (should also again be a border again between the two buttons on the modal)

**IDS-4264**
- go to http://localhost:4300/ids-data-grid/editable.html and ensure filter buttons position ok
- go to http://localhost:4300/ids-lookup/example.html and open a modal and click the filter buttons and ensure they position ok
- new test page: http://localhost:4300/ids-popup-menu/in-action-panel.html
- new test page: http://localhost:4300/ids-popup-menu/in-modal.html
- new test page: http://localhost:4300/ids-popup-menu/in-popup.html

**Included in this Pull Request**:
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by jdilag90** [comment]
Looks good, found one thing which could be another ticket

Tooltip positiong is off when hovering over show/hide button. It also reveals hidden password.
Happens on main.wc as well.
Maybe we just disable tooltips for password inputs?
image

**Review by jdilag90 — APPROVED** [review]
Approving 

Made another for tooltip issue mentioned above (https://github.com/infor-design/enterprise-wc/issues/2810)

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

image

image

image

**Review by glenlieorillo — APPROVED** [review]
image

image

image

image

image

image

image

image

**Review by jbrcna — APPROVED** [review]
image
image
image
image
image
image
image
image
image

**Pull request merged**
