### PR TITLE
935 - IdsLayoutGrid fix for responsive behavior

### LINKED ISSUE #935: IdsLayoutGrid: Breakpoint settings not working
**Describe the bug**
The responsive breakpoint settings are no longer working in `ids-layout-grid`. For example `col-span-md`, `col-span-xs`, etc. when set should be adding classes with sizes for the corresponding breakpoint. 

**To Reproduce**

1. Go to http://localhost:4300/ids-layout-grid/example.html
2. Scroll down to LAYOUT GRID - 12 COLUMN FLUID GRID W/BREAKPOINTS
3. See error

**Expected behavior**
The grid col setting should be responding to breakpoints.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Screen Shot 2022-09-21 at 1 43 45 PM

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
This seems to have stopped working when the RAF was removed from the setter in this commit: https://github.com/infor-design/enterprise-wc/commit/221ce8e8dae5d7576da7b044e0e1d0a8c3f434fc

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds a fix for the `ids-layout-grid` breakpoint classes.

**Related github/jira issue (required)**:
closes #935 

**Steps necessary to review your pull request (required)**:
- pull and run branch
- go to http://localhost:4300/ids-layout-grid/example.html
- make sure the fluid grid examples are responding to breakpoints appropriately

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
~- [ ] A note to the change log.~

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@jmacaluso711 i did notice that somehow this seems to have had an adverse effect on the image in https://percy.io/00aaa841/enterprise-wc/builds/21672992/changed/1208668488?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280 

Maybe check that out? Perhaps its just the grid setup there?

**Comment by jmacaluso711** [comment]
@tmcconechy I took a look at this, but can't recreate it locally, so was wondering if it's a percy timing issue?

**Comment by tmcconechy** [comment]
@jmacaluso711 it could be - if its not happening locally then we could try

- does the layout grid or cell rely on any timeout or rAF stuff
- could add a short delay/wait to the test (this often doesnt seem to work)
- aside from that could just limit the test to the mobile one.. or remove it as a last resort

**Comment by jmacaluso711** [comment]
@tmcconechy All RAFs and setTimeouts were removed from the layout grid, so attempting the percy test delay

**Review by tmcconechy — COMMENTED** [review]
Another idea with the image is to maybe take the "auto" one and put it on a separate second example? So the main ids-image example just uses the grid and the second example shows the auto?

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
