### PR TITLE
1962 - Convert popup test to Playwright

### LINKED ISSUE #1962: Tests: Convert Popup Tests
**Describe the task**
Convert Popup  tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-popup to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-popup/ids-popup.spec.ts

**Additional context**
N/A

### LINKED ISSUE #2360: IdsPopup: `bleed` property value not in sync with attribute when a string is provided
**Describe the bug**
When setting `bleed` property with a string, the getter return is not in sync with the attribute.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-popup-menu/example.html
2. Open developer's console
3. Enter `document.querySelector('ids-popup').bleed = 'true'`
4. Attribute is added
5. Enter `document.querySelector('ids-popup').bleed`
6. Returns `''`
7. Enter `document.querySelector('ids-popup').bleed = 'false'`
8. Returns `null`

**Expected behavior**
When property is set to true, should return true and vice-versa.

**Version**

- ids-enterprise: v1.1.0

**Screenshots**
https://github.com/infor-design/enterprise-wc/assets/156752175/afd43849-846a-47e0-bb18-a8914b41ade6

### PR DESCRIPTION
**Pull request by n-ace-ancog**
**Explain the details for making this change. What existing problem does the pull request solve?**
1. Popup test conversion to Playwright
2. Flaky test fix for splitter and input components 
    - added `await page.locator('#test').waitFor({ state: 'attached' });` on test cases that are failing which waits for the element to be attached in DOM before proceeding in validation
    - `await page.waitForSelector('#test');` was not used since its checking if the element is attached and visible without exceptions
3. In the `eventsTest` helper object, added a `setPage(page: Page)` function to set/change the page in context in cases where a new page is created in the test case itself
4. Fixes return of `bleed` property

**Related github/jira issue (required)**:
Closes #1962
Fixes #2360

**Steps necessary to review your pull request (required)**:

1. Pull this branch, build, and run the app
2. Run the test suite
5. Check the code conversion
6. New converted tests should pass and no flaky test

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by n-ace-ancog** [comment]
@tmcconechy - I've added some fix for the flaky test in splitter, but skip those test with `test.skip`. Should I include them as well?

**Comment by tmcconechy** [comment]
@n-ace-ancog sure 👍🏻

**Comment by ericangeles** [comment]
@n-ace-ancog yes please.

**Comment by n-ace-ancog** [comment]
@tmcconechy @ericangeles  I've log an issue regarding `bleed` property with #2360. Seems the fix is easy and will add it in this PR. Let me know if this is fine.

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]
👍🏻 Nice!

**Review by andrivarhanov — APPROVED** [review]

**Pull request merged**
