### PR TITLE
562 - IdsDatePicker remaining features/issues

### LINKED ISSUE #562: IdsDatepicker: Remaining Features/Issues
**Description**
Lists the Remaining Bugs/Features for a 100% Component

**Major**
- [x] Code to new designs https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/?node-id=892%3A348 and 
https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/Calendar?node-id=1%3A2269&viewport=-288%2C2528%2C0.32999536395072937
- [x] Add Masking / Localization with way to customize or disable the mask
- [x] Keyboard Shortcuts according to https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/readme.md#keyboard-shortcuts https://github.com/infor-design/enterprise-wc/issues/538
- [x] General accessibility (screen reader) / axe https://github.com/infor-design/enterprise-wc/issues/538
- [x] Clicking the month/year opens the month and year selection panel https://github.com/infor-design/enterprise-wc/issues/538
- [x] Configurable legend https://main-enterprise.demo.design.infor.com/components/datepicker/example-legend.html https://github.com/infor-design/enterprise-wc/issues/538
- [x] Range picker https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html including https://main-enterprise.demo.design.infor.com/components/datepicker/test-week-picker.html https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L69-L79 https://github.com/infor-design/enterprise-wc/issues/538
- [x] Make it open faster (seems a little slow and for @EdwardCoyle it was 2-3 seconds) https://github.com/infor-design/enterprise-wc/issues/538
- [x] Add functional tests for these cases https://main-enterprise.demo.design.infor.com/components/datepicker/example-anniversary-format.html and https://main-enterprise.demo.design.infor.com/components/datepicker/example-custom-format.html
- [x] Add disabled dates https://main-enterprise.demo.design.infor.com/components/datepicker/example-disabled-dates.html for month view as well. Can rethink the API see current settings https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L40-L57
- [x] Add sizes and field height examples like input https://main-enterprise.demo.design.infor.com/components/datepicker/example-sizes.html with tests
- [x] Date picker with time https://main-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html with tests see settings https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L26-L31
- [x] Add tests for invalid dates https://main-enterprise.demo.design.infor.com/components/datepicker/example-validation.html
- [x] Add test that the change and input event is fired when the date is changed as a test. And make sure the hide/show events are fired as well (from the popup component). And add to breaking changes.
- [x] Add test that the placeholder works (should work)
- [x] Add test for UTC picker https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L83
- [x] Speed -> if you run the performance tab https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html is about 10 times slower rendering the page

**Minor**
- [x] Add week numbers when design approved https://github.com/infor-design/enterprise/issues/5785
- [x] Add mobility changes when design approved https://github.com/infor-design/enterprise/issues/5763 (some need to be confirmed)
- [x] Add test for this case https://github.com/infor-design/enterprise/issues/5255
- [x] Add side by side example
- [x] Figure out https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html if needed?

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds remaining items from #562

**Related github/jira issue (required)**:
Closes #562 

**Steps necessary to review your pull request (required)**:
- pull and run
***
> Code to new designs

New designs were added including styles, clear/apply buttons functionality adjustments, month/year picker adjustments, hitbox adjustments, full list is here https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/Datepicker or here https://github.com/infor-design/enterprise/issues/5763

- go to http://localhost:4300/ids-date-picker/sandbox.html
- open some date picker calendar popup
- open month/year picker at the top left
- check month/year lists changes and apply button functionality
- check `With Clear Button` date picker
- check the clear button functionality
- go to http://localhost:4300/ids-date-picker/range.html
- check the apply button functionality with range picker
***
> Add Masking / Localization with way to customize or disable the mask

Since only `date` mask can be applied to date picker `mask` attribute was simplified to boolean value.
Was added `rangeMask` for range picker
- go to http://localhost:4300/ids-date-picker/example.html
- check masking on each available date picker
- go to http://localhost:4300/ids-date-picker/range.html
- check masking on each range picker
***
> Add side by side example

- go to http://localhost:4300/ids-date-picker/side-by-side.html
- check 4.x version and compare to 5.x version
***
>  Add test for this case https://github.com/infor-design/enterprise/issues/5255

- go to http://localhost:4300/ids-date-picker/example.html
- set different locale and language for `ids-container`
```js
await document.querySelector('ids-container').setLocale('es-ES');
await document.querySelector('ids-container').setLanguage('en');
```
- check months and week days in the calendar are still in English
***
> Add week numbers

- go to http://localhost:4300/ids-date-picker/sandbox.html
- check `With Week Numbers` example
***

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@andriivarhanov i probably should have said this but i wasnt sure about removing the buttons for OK, Cancel.  think this actually works nicer than i was picturing so maybe just need a setting in case they really need those buttons (for some reason). Is this already possible with a setting?

Small Bugs:
- on http://localhost:4300/ids-date-picker/sandbox.html on the "Abbreviated Month Year" example if i open it with arrow down and then try to arrow left right this doesnt work. Seems like just this one..
-  http://localhost:4300/ids-date-picker/example.html if i type 'a' in the required one the message popups up right away - maybe we do it on tab?
- also on  http://localhost:4300/ids-date-picker/example.html in the mask i can type 9000-99-99 -> do we have a valid date validation we can add like before?
- on http://localhost:4300/ids-date-picker/sandbox.html for week numbers i was picturing it showing small on the left side of the calendar but maybe this works we can see if they like it this way.

**Comment by andriivarhanov** [comment]
@tmcconechy 
> Is this already possible with a setting?

sure, I will add another setting `show-cancel` for Cancel button similarly to `show-clear` setting

> on http://localhost:4300/ids-date-picker/sandbox.html for week numbers i was picturing it showing small on the left side of the calendar but maybe this works we can see if they like it this way

It makes sense to have week numbers in the calendar as well, I was thinking about it as well, just not sure about the design. I've added them same style as calendar days as a preview, please check screenshot below and let me know if it looks good for you

image

**Comment by tmcconechy** [comment]
Rereading https://github.com/infor-design/enterprise/issues/5785 it sounds like the way you have it is what they want. So maybe this is good enough for now?

If you do add it i would make that column:
- the same color as inactive days (like 29, 30 ect)
- reduce the width of that column by about half (less padding ext)
- reduce the font size to 10px of just that column 
(i.e. it should not get confused with days in the week)

But ok to leave that out for now 👍🏻

**Comment by tmcconechy** [comment]
Also should we reduce the coverage threshold down or do you plan to add some more tests?

**Comment by andriivarhanov** [comment]
@tmcconechy it looks like the coverage doesn't include my e2e tests, there are a lot of e2e tests for date picker, month view and week view components. I will try to increase the coverage with just func tests. 
I will leave week numbers functionality as is for now

**Comment by tmcconechy** [comment]
ok sounds good - we can also change the tolerance down to 83% or something for now. I have not gotten the e2e coverage to work since we went to typescript.

**Review by tmcconechy — DISMISSED** [review]

**Comment by andriivarhanov** [comment]
- added show-cancel setting, http://localhost:4300/ids-date-picker/sandbox.html With Cancel Button example
- added blur validation event and date validation to the required example on http://localhost:4300/ids-date-picker/example.html
- increased a bit test coverage with func tests

ready for review

**Review by tmcconechy — APPROVED** [review]

**Review by danielortiz1982 — APPROVED** [review]

**Pull request merged**
