### PR TITLE
524 - Fix rtl issue

### LINKED ISSUE #521: IdsTag: Revert Style Changes
**Describe the bug**
We need to revert the tag styles back to the smaller ones. Because the style impact is breaking UI for hight and off putting.

So https://main.wc.design.infor.com/ids-tag/
should be changed back to https://4580-enterprise.demo.design.infor.com/components/tag/example-index.html

**Expected behavior**
- Update the font size/ tag height back to https://4580-enterprise.demo.design.infor.com/components/tag/example-index.html
- Only that leave the colors ect as is...

### LINKED ISSUE #524: IdsMenuButton: Styling issues in RTL Mode
**Describe the bug**
The arrow styles are off in RTL mode.

**To Reproduce**
1. Go to http://localhost:4300/ids-tag or http://localhost:4300/ids-menu-button
2. In the html inspector find `ids-container` and change `language="ar"` to force RTL
3. Click ....

**Expected behavior**
Fixed styles in RTL mode for menu button/theme switcher

**Screenshots**
Screen Shot 2022-01-27 at 1 52 23 PM

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

While reviewing https://github.com/infor-design/enterprise-wc/issues/524 i found an easier fix. Turns out the locale mixin was missing and in some situations when slotted it needs the getClosest() function that pierces the shadow DOM as it otherwise it wont find the container to attach events on.

This may need to be changed in other places but starting with this...

In addition:

- cleanup button styles the rtl class is not needed with padding-start/end changes
- revert tag bold (same as EP)

**Related github/jira issue (required)**:
Fixes #524 
Fixes #521

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-tag
- in the DOM find `ids-container` and set `language="ar"`
- reload
- in the DOM find `ids-container` and set `locale="ar-SA"`
- open the ... menu 
- make sure the RTL UI looks nice
- test RTL on to http://localhost:4300/ids-button
- go to http://localhost:4300/ids-menu-button

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
the fix looks good, I just wanted to raise another issue not sure if it should be separated one. 
The direction changes not only on languagechange event but on localechange event as well. 
Steps to reproduce:
1. localhost:4300 any page
2. `document.querySelector('ids-container').setLocale('ar-SA')` in the console
3. check `ids-container` has `dir="rtl"`
4. check no other components have `dir="rtl"`
5. same with `document.querySelector('ids-container').setLanguage('ar')`
6. all components have `dir="rtl"`

can be fixed by adding localechange.mixin listener to `ids-locale-mixin` connectedCallback and to all slotted components

**Comment by tmcconechy** [comment]
Thanks @andriivarhanov going to take a look as i missed that.

**Comment by tmcconechy** [comment]
@andriivarhanov changed this fix around you can now change via the locale.

**Review by andriivarhanov — APPROVED** [review]
looks great

**Review by jeffwa428 — APPROVED** [review]

**Pull request merged**
