### PR TITLE
2001 - IdsDropdown size and position

### LINKED ISSUE #2001: Dropdown: size=full attribute is not working on dropdown's pop-up option list
**Describe the bug**
Dropdown's size=full attribute is working on Dropdown but not to its dropdown options.

**To Reproduce**

1. Go to [https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ts-ids-wc](https://github.com/infor-design/enterprise-wc-examples/tree/main/react-ts-ids-wc)
2. Update ids version in package.json: "ids-enterprise-wc": "^1.0.0-beta.21",
3. Update examples/ids-dropdown.tsx to add size="full" attribute on a sample dropdown:
4. `<ids-dropdown label="Required Dropdown" value="opt1" validate="required" size="full">`
5. npm i && npm run start to get the latest
6. Go to http://localhost:3000/ids-dropdown
7. Click the dropdown to view options and observe that the width of the dropdown and its option list are not the same:
image

**Expected behavior**
The same width

**Version**
- "ids-enterprise-wc": "^1.0.0-beta.21"

**Platform**
 - Infor Application/Team Name: Rhythm Billing
 - Browser Name: Edge, Firefox, Chrome

### LINKED ISSUE #2248: IdsMultiselect: Popup not display in correct position with size='lg'
1) Ids-multiselect when using the size property with size='lg', the popup of Ids-multiselect does not fit with the dropdown width.
2) When using label-state="collapsed" with ids-multiselect the gap between the label and multi-select element is not reduced. collapsed style is not applying.
image
 

**To Reproduce**
Add ids-multiselect with size attribute "lg"
Click on the dropdown icon and observe.
The popup width and dropdown width are not equal.

**Expected behavior**
Expected is the popup width should fit with the dropdown width based on the dropdown given size.

**Version**
"ids-enterprise-wc": "^1.0.0",

**Screenshots**
image

**Platform**
Infor ION team

### LINKED ISSUE #2431: IdsDropdown : Placement issue in Version 1.2.0
**Describe the bug**
I encounter an issue when utilizing ids-dropdown on a modal. Once user clicks on the dropdown and opens, the list of options is rendered bottom right of the dropdown, instead of directly underneath. Encountered this issue in Web components - examples (Angular). 
Note : Also previously raised a ticket regarding this situation - https://github.com/infor-design/enterprise-wc/issues/2348.

**To Reproduce**

1. Open this Stack blitz -  https://stackblitz.com/edit/ids-enterprise-wc-120-sjjfv2?file=index.html
2. Click on dropdown displayed.
3. Options shown some where to right bottom of page.
4. See as it not even used for selection.

**Expected behavior**
To be displayed underneath of dropdown to show list of options.

**Version**

- ids-enterprise: v1.2.0

**Screenshots**
image

### LINKED ISSUE #2441: IdsDropdown: Layout issue on Dropdown contents inside an Expandable Area header
**Describe the bug**
Dropdown contents are not in the correct location when inside an expandable-area header.

1. Go to https://stackblitz.com/edit/stackblitz-starters-8pvaan?file=src%2Fapp%2Fexample%2Fexample.component.html
2. Click on the dropdown

**Expected behavior**
Dropdown contents should be aligned with the dropdown element and should be on top level

**Version**
- ids-enterprise-wc: 1.2.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: M3
 - OS Version: Windows 11

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixes issues with IdsDropdown/IdsMultiselect sizing and popup positioning

**Related github/jira issue (required)**:
Closes #2001 
Closes #2441 
Closes #2431 
Closes #2248 

**Steps necessary to review your pull request (required)**:

** #2001 Dropdown size full **
1. Go to http://localhost:4300/ids-dropdown/sizes.html
2. Check that the dropdown popup is correctly sized and positioned

** #2441 Dropdown in expandable area **
1. Go to http://localhost:4300/ids-dropdown/in-expandable-area.html
2. Check that dropdown opens above the expandable area

** #2431 Dropdown in action panel **
1. Go to http://localhost:4300/ids-dropdown/in-action-panel.html
2. Check that dropdown opens outside of the action panel modal

** #2248 Multiselect size full **
1. Go to http://localhost:4300/ids-multiselect/example.html
2. Run `$('ids-multiselect').size = 'full';`
3. Check that the popups is correctly sized and positioned

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Working on my side.

http://localhost:4300/ids-dropdown/sizes.html

https://github.com/infor-design/enterprise-wc/assets/156752175/a7d26551-999f-4d9d-b3e7-180bb1fa017d

http://localhost:4300/ids-dropdown/in-expandable-area.html#0
image

http://localhost:4300/ids-dropdown/in-action-panel.html
image

http://localhost:4300/ids-multiselect/example.html
image

**Review by glenlieorillo — APPROVED** [review]
Working now as expected.

https://github.com/infor-design/enterprise-wc/assets/102151352/713f5e28-6b27-4a3d-bef2-46b83544c70f

image

image

image

image

**Review by jbrcna — COMMENTED** [review]
this is working as expected. 
image
image
image
image

**Comment by jbrcna** [comment]
However, in smaller viewport.
image
image
image

**Pull request merged**
