### PR TITLE
842 - IdsTabs fix styling for draggable tabs

### LINKED ISSUE #842: IdsTabs: Fix styling for draggable tabs
**Describe the bug**
Should improve the styles for dragging tabs.

**To Reproduce**

1. Go to http://localhost:4300/ids-tabs/swappable.html or https://main.wc.design.infor.com/ids-tabs/swappable.html
2. Click on a tab and drag it

**Expected behavior**
Should look close to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html at least the tab contents should be visible

**Additional context**
NA

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds CSS classes with slotted element names to `ids-swappable-item` what allows to exclude default draggable color and background color for some cases like `ids-tabs`

**Related github/jira issue (required)**:
Closes #842 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-tabs/swappable.html
- drag a tab
- see there is no background and color when dragging and tab content is visible
- go to http://localhost:4300/ids-swappable/example.html
- see dragging/selected items have background and color

**Included in this Pull Request**:
~- [ ] An e2e or functional test for the bug or feature.~
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks nice @andriivarhanov ! Just wondering two things

a) Should we make the icon be in the middle of the left edge and text start? Seems a bit close to the front

Screen Shot 2022-09-19 at 12 55 33 PM

2. Concerning the with-styles setting. Would it make more sense to just do this by default? Im wondering because its something that the developer now has to add to the tab template to make it work. Or can it by tied too the ids-tab (:slotted?)

**Comment by andriivarhanov** [comment]
@tmcconechy everything makes sense, I will make those changes

**Comment by andriivarhanov** [comment]
- fixed the icon to be in the middle of the left edge and text start
- no luck with styling `ids-tab` by dragging attribute with existing `ids-swappable-item` styles, parent component styles still interfere with child component, had to add CSS classes to ids-swappable-item

**Review by tmcconechy — APPROVED** [review]
Looks 👍🏻 Now. Thanks @andriivarhanov

**Pull request merged**
