### PR TITLE
734 - Add rtl support with charts

### LINKED ISSUE #734: IdsAxisChart: RTL axis on the wrong side
**Describe the bug**
RTL is not fully working on charts.

**To Reproduce**

1. Go to   http://localhost:4300/ids-bar-chart/example.html
3. Change to Hebrew or Saudi
5. Hover a bar

**Expected behavior**

- Y axis should be on the right side and
- The items should be inverted in order
- one toolbar

**Additional Info**
Need to change it in pie chart and axis chart maybe this helps https://stackoverflow.com/questions/42147119/how-to-flip-svg-coordinates

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
Added RTL support to area, bar, line, and pie charts.

**Related github/jira issue (required)**:
Closes #734

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300/ids-area-chart/example.html
- http://localhost:4300/ids-bar-chart/examplehtml
- http://localhost:4300/ids-line-chart/example.html
- http://localhost:4300/ids-pie-chart/example.html
- Click on action button `...` (top right) to switch RTL locale
- Change to `Hebrew (he-IL)` or `Arabic (ar-EG)`
- See items like axis, svg items, legends should be inverted in order

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@deep7102 i checked out http://localhost:4300/ids-area-chart/example.html andsee two things:

a) shouldn't the labels be reversed (jun-jan)
b) for the text on the left in RTL mode there should be a bit more padding (also might have too use the textWidths setting)

Otherwise looks like a nice fix 👍🏻

**Comment by deep7102** [comment]
@tmcconechy updated now, it's ready for review

**Comment by tmcconechy** [comment]
@deep7102 do the visual changes seem ok? Maybe just a pixel off? Do you use the margins and textWidth still? Or is it now auto based on the text size?

Note i fixed some tests here for ones acting wierd https://github.com/infor-design/enterprise-wc/pull/798

**Comment by deep7102** [comment]
> @deep7102 do the visual changes seem ok? Maybe just a pixel off? Do you use the margins and textWidth still? Or is it now auto based on the text size?
> 
> Note i fixed some tests here for ones acting wierd #798

Hi @tmcconechy 
yes, it use now combination of auto text size and margins -so that why you see that pixel off.

**Review by tmcconechy — COMMENTED** [review]
@deep7102 everything looks good except for http://localhost:4300/ids-bar-chart/example.html doesnt seem to be loading anymore (blank page?)

**Review by danielortiz1982 — APPROVED** [review]

**Pull request merged**
