### PR TITLE
4458 - Update ids-input, rename ids-label, removed ids-validation-message and other cleanup

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
- Fixed label, size and validate attributes
- Fixed `ids-trigger-field` alignments for all input sizes
- Renamed `ids-label` component to `ids-text`
- Removed `ids-validation-message` component and merge logic with `ids-validation-mixin` to keep simple
- Updated the logic for remove events with `ids-validation-mixin` and `ids-dirty-tracker-mixin
- Updated `ids-constants` content to be sorted alphabetically
- Added docs (readme.md)
- Added functional and e2e tests

**Related github/jira issue (required)**:
Fixes infor-design/enterprise#4458

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4300
- http://localhost:4300/ids-input
- http://localhost:4300/ids-input/test-validation-message.html
- See the styles for validation message (inputs, icons, color and audible text for each type)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
Waiting for
- e2e tests (percy)
- more coverage
- anything else?

**Comment by deep7102** [comment]
and `ids-trigger-field`  button alignment for all input sizes

**Comment by deep7102** [comment]
Hi @tmcconechy this updated now as:
- Fixed `ids-trigger-field` alignments for all input sizes
- Fixed e2e skipped tests (percy)
- Added more functional test for jest coverage

**Review by EdwardCoyle — APPROVED** [review]
Looks great! 🍌

**Pull request merged**
