### PR TITLE
2092 - Fix IdsMasthead layout and responsive behavior

### LINKED ISSUE #2092: Masthead: Buttons and icons are not visible in responsive and mobile view
**Describe the bug**
Masthead: Buttons and icons are not visible in responsive and mobile view

**To Reproduce**

1. Go to http://localhost:4300/ids-masthead/example.html
2. Switch to Responsive / Mobile view 

**Expected behavior**
Masthead should be responsive & buttons and icons should be visible.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
https://github.com/infor-design/enterprise-wc/assets/45757016/bcfe8450-49d1-40a9-9923-3aaf2660a937

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR simplifies the structure of the `ids-masthead` by reducing the number of slots to a single slot. This allows for the addition of an `ids-toolbar` to manage button placement and toolbar functionality within the masthead.

- **Refactored Layout**: Updated the layout to support a more flexible and customizable toolbar integration within the masthead using the `ids-toolbar` component.
- **Enhanced Customization**: The new structure enables users to customize the toolbar's content and organization within the masthead without predefined slot constraints.
- **Backward Compatibility**: Ensured backward compatibility by maintaining existing methods and properties, while streamlining the usage of the masthead component.

**Related github/jira issue (required)**:

closes #2092 

**Steps necessary to review your pull request (required)**:

- pull and run branch
- go to http://localhost:4300/ids-masthead/example.html
- Resize browser
- Buttons should overflow into the "More" button when on smaller screens

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
I just see two things

a) On http://localhost:4300/ids-module-nav/with-masthead.html its fully black
b) A bit more space here between the buttons and overflow

Screenshot 2024-09-10 at 1 19 06 PM

**Comment by jdilag90** [comment]
looks good, just the infor logo is a little off center vertically 
image

**Review by jbrcna — APPROVED** [review]
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Looks great! Seems like that there's an issue when the button is clicked when the button is included in the more options.

https://github.com/user-attachments/assets/b8ea8b8b-8970-4857-8902-fee94a3feb45

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Still failing on my end. Buttons are still not visible in a smaller viewport.

image

image

image


https://github.com/user-attachments/assets/f0cba82d-fa9a-46a0-8a8f-8dbdeebee6f2

**Comment by tmcconechy** [comment]
@jmacaluso711 also still see that the masthead is all black here http://localhost:4300/ids-app-menu/with-masthead.html (maybe need to recopy the examples?)

**Comment by jmacaluso711** [comment]
> Looks great! Seems like that there's an issue when the button is clicked when the button is included in the more options.
> 
>  Screen.Recording.2024-09-12.at.4.27.42.PM.mov 
> image

@n-ace-ancog I'm not able to re-create this issue. Did you pull and re-run the branch?

**Review by tmcconechy — APPROVED** [review]

**Review by jdilag90 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@n-ace-ancog we think everything is fixed. Since we are rushing this gitlab transition. Merged. Any additional issues raise a new bug

**Pull request merged**
