### PR TITLE
2388 - ids-data-grid inline editor cursor

### LINKED ISSUE #2388: IdsDataGrid: Clicking on inline editor does not move cursor
**Describe the bug**
Cannot move cursor on text when clicking on inline editor.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/editable-inline.html
2. Edit "101" to "test"
3. Click between "t" and "e"
4. See text selection behavior

**Expected behavior**
Text cursor should be shown and moved in between "t" and "e"

**Version**

- enterprise-wc: v1.1.0

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/120151603/71b081a1-b0a4-4e57-a85f-9001087a564d

**Additional context**
Clicking anywhere on the text always highlights it.

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fix cursor on inline editor.

**Related github/jira issue (required)**:

Closes #2388 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm i && npm run start`
2. Go to: http://localhost:4300/ids-data-grid/editable-inline.html
3. Edit "101" to "test"
4. Click between "t" and "e"
5. See text selection behavior
6. Compare against: https://main.wc.design.infor.com/ids-data-grid/editable-inline.html

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@clayinfor looks like it works but I changed the zindex to match the system.

```
20 - Contextual Toolbar
500 - Side Menu, Status Bar
600 - App Menu, Module Nav
1000 - Overlay
1010 - Busy Indicator
1015 - Popdown
1020 - Dialogs (Modals)
3000 - Popovers 
4000 - Lookup
4500 - Drop Down
6000 - Tooltips
7000 - Draggables
8000 - Slide in Message Dialog/Toast
9000 - Sticky Nav / Context Menus
10000 - Full Page Sticky Nav, Search Results
10020 - Skip link
```

Also noted: https://github.com/infor-design/enterprise-wc/issues/2453 but made a new issue

**Review by tmcconechy — DISMISSED** [review]

**Comment by tmcconechy** [comment]
@clayinfor can you check those data grid tests?

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
This is now working as expected. However, when changing the Row Height (_Extra Extra Small_) the dirty tracker and focus state are misaligned.

https://github.com/infor-design/enterprise-wc/assets/102151352/fc4c4037-ffc2-424d-b660-dfc4a5cd87dd

image

_Compared to main_
image

**Comment by tmcconechy** [comment]
@clayinfor can you add this fix as noted by @glenlieorillo and fix the tests? If you want to fix the css issue on a new issue we can do that, just us know.

**Comment by jbrcna** [comment]
the issue exists on my end as well
image

**Comment by tmcconechy** [comment]
@clayinfor action items:

a) Address tests
b) Fix QA noted issue css issue (if quick if not we punt)

**Comment by jbrcna** [comment]
the dirty tracker issue still exists
image

**Review by tmcconechy — APPROVED** [review]
@clayinfor looks good aside from the xxs issues reported

**Comment by clayinfor** [comment]
hey @jbrcna , @tmcconechy , the dirty-tracker issue is fixed now

**Review by tmcconechy — APPROVED** [review]
@clayinfor looks good just a lint error

**Review by jbrcna — DISMISSED** [review]
thanks @clayinfor , great work!
image

**Review by glenlieorillo — APPROVED** [review]
This is now working as expected.

image

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
