### PR TITLE
1072 - Add xxs row height

### LINKED ISSUE #1072: IdsDataGrid: Shorter Row Height
**Describe the bug**
M3 wants even more room in the data grid. 25px rows and smaller font size. Header height stays as is to avoid too much variation and bugs.

- [x] Reduce font by 2 for XS and XXS
- [x] Fix alignment on header to match rows
- [x] Effective Row Height is 25px instead of 31
- [ ] Test editing and other features
- [ ] Can change this example to XS: http://localhost:4300/ids-data-grid/m3-features.html

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/row-height.html
3. Set row height -> should be 25 now

**Expected behavior**
They want it even smaller down to 25px
**Additional context**
M3 

Untitled

image

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds XXS row height to the data grid and related features and corrections. Some notes:

- hyperlink was updated due to alignment issues with the padding
- in smaller row heights the drag indicator wont fit but you can drag the columns by now dragging the entire column

**Related github/jira issue (required)**:
Fixes #1072 

**Steps necessary to review your pull request (required)**:
- in the following list of datagrid examples try the row heights. they have been cleaned up and xxxs is added
- try modes, themes, RTL and dragging and resizing columns, make sure things look well aligned.
- http://localhost:4300/ids-data-grid/editable.html
- http://localhost:4300/ids-data-grid/editable-inline.html
- http://localhost:4300/ids-data-grid/row-height.html
- http://localhost:4300/ids-data-grid/m3-features.html

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by EdwardCoyle** [comment]
On http://localhost:4300/ids-data-grid/editable.html, there's some kind of size discrepancy on the Date/Time fields -- seems like some missing/extra padding somewhere causes the size to change:

[Untitled_ May 24 2023 10_04 AM.webm](https://github.com/infor-design/enterprise-wc/assets/3249601/fbe6f2af-1ff8-453b-a571-8ebaea585440)

**Comment by tmcconechy** [comment]
@EdwardCoyle fixed this somewhat for what i could. But we will need:

https://github.com/infor-design/enterprise-wc/issues/1298
https://github.com/infor-design/enterprise-wc/issues/1297
https://github.com/infor-design/enterprise-wc/issues/1291

**Review by deep7102 — APPROVED** [review]
Looks good 🍌 
One thought for drag state where we not have icon, could be change cursor like `move` or `grab` might have some visual, but then thinking we also have in sort icons in same area so might be hard and not good idea.

**Comment by tmcconechy** [comment]
yeah i thought of that @deep7102 but it wasnt possible

**Pull request merged**
