### PR TITLE
587 - Sortable ListView and ListBuilder todos

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR refactors the sortable `ids-list-view` and `ids-list-builder` to use `ids-swappable` which implements the native drag/drop api.

**Related github/jira issue (required)**:
related to #587 

**Steps necessary to review your pull request (required)**:
- pull and run branch
- go to http://localhost:4300/ids-list-view/sortable.html 
- select and drag an itemt to sort
- go to http://localhost:4300/ids-list-builder
- select and drag an item to sort
- make sure all toolbar features are working (add, up, down, edit, delete)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
~- [ ] A note to the change log.~

### CODE REVIEW

**Comment by jmacaluso711** [comment]
@tmcconechy -- Looks like in enterprise you have to select first so I was going off of that. On WC main though you don't need to select first.

I didn't notice any issues with the header color, but there were a few dark theme styles that were missing, so I added those.

**Comment by tmcconechy** [comment]
I just mean that this image https://percy.io/00aaa841/enterprise-wc/builds/17912965/changed/1005054429?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280 (for contrast) doesnt have the same toolbar color as the actual page when contrast mode is on

**Review by andriivarhanov — COMMENTED** [review]
it's weird Percy didn't reflect recent toolbar color change in contrast mode, maybe we should re-run the build, but also could you please check color or width of toolbar separator lines in contrast mode
image.

**Comment by tmcconechy** [comment]
I think i may have approved the wrong color - if we can see find the reason its wrong

**Review by andriivarhanov — APPROVED** [review]
yeah, it looks like it's out of scope since the PR is about sortable functionality and there is another todo item related to styling in https://github.com/infor-design/enterprise-wc/issues/587 . Sortable functionality looks good, approved

**Comment by tmcconechy** [comment]
Ok its probably a timing issue - not that worried about it right now either. Approved

**Pull request merged**
