### PR TITLE
866 - IdsColorPicker warning in the console

### LINKED ISSUE #866: IdsColorPicker: Warning in the console typing invalid values
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-color-picker/example.html
2. Click in any picker
3. Type a
4. See error in the console:

```
The specified value "a" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
```

**Expected behavior**
See if we can get around this showing. Also could add a mask to solve it possibly. Or do both

**Platform**
 - Chrome
 - 1.0 - beta1
 
**Additional context**
#357

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds mask to the advanced `ids-color-picker` and updates color input value only when it meets the format, removes input type color from regular color picker. Adds slight adjustment to the required input label "*" sign so it doesn't change label's height.

**Related github/jira issue (required)**:
Closes #866 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-color-picker/example.html
- open browser's console
- click in any picker
- type any letter
- check the console, should be no warning
- check "Advanced Color Picker" example
- see the input is masked
- change value, open browser's color picker

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
The only problem with this is if you:

http://localhost:4300/ids-color-picker/example.html
- click advanced picker
- now it wont open

I.E. this was for the advanced picker so its needed there. Maybe there is some other way to fix this or mask it and catch the error?

Also i think something might be wrong in the example layout if you make it this size it looks strange? (Saw this in the percy tests too) (about 573px width)

Screen Shot 2022-09-09 at 10 21 19 AM

**Comment by andriivarhanov** [comment]
@tmcconechy 
- added mask to advanced color picker
- removed input type color from regular color picker
- adjusted required input label "*" sign so it doesn't change label height (that's why there are a lot of visual changes in Percy)

**Review by tmcconechy — APPROVED** [review]

**Review by danielortiz1982 — APPROVED** [review]

**Comment by danielortiz1982** [comment]
@andriivarhanov This looks great! When you have a moment can you please merge main into your feature branch to bring it up to date. Thanks!

**Comment by tmcconechy** [comment]
Try running the tests again @andriivarhanov -> i think that one has occasionally failed (but not that often)...you can rerun on the details of it.

**Comment by andriivarhanov** [comment]
@tmcconechy done

**Pull request merged**
