### PR TITLE
2347 - IdsSwitch design update

### LINKED ISSUE #2347: Switch: Design Update
New Designs in for the Switch component: https://www.figma.com/design/XALiPBQAENSzcZCCosNbW6/Toggle---Updated-Switch-IDS-Component?node-id=314-9034&t=LbzJmPB1udDE7smO-0

We want to do this in WC, and then mirror in jQuery

### PR DESCRIPTION
**Pull request by jdilag90**
**Explain the details for making this change. What existing problem does the pull request solve?**
Update IdsSwitch design

**Related github/jira issue (required)**:
Closes #2347 

**Steps necessary to review your pull request (required)**:
1. Checkout branch
2. Go to http://localhost:4300/ids-switch/example.html
3. Compare to [figma spec](https://www.figma.com/design/XALiPBQAENSzcZCCosNbW6/Toggle---Updated-Switch-IDS-Component?node-id=314-9035&t=cp8LVG2YEZMzWy9O-0)
4. Check styles in different themes
5. Check styles in RTL language
6. Check if disabled state is ok
7. Check if focus state is ok

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@jdilag90 only one thing. Can you check the padding between switches it looks tight now. Should be 20px padding on bottom.

**Comment by jdilag90** [comment]
@tmcconechy I increased the margin bottom for switches. 

I'm not seeing anything wrong with the the example pages though.
Layout Grid/Cells look to be ok on both main.wc and local

**Review by tmcconechy — DISMISSED** [review]

**Review by clayinfor — APPROVED** [review]

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
1. In http://localhost:4300/ids-switch/side-by-side.html, the lower switches design are not updated.

image

2. The "highlight" is not working in Safari
**Chrome**
image

**Safari**
image

**Comment by tmcconechy** [comment]
@n-ace-ancog FYI we didnt add the switches to enterprise yet but thats coming on another issue. So ignore that for now 👍🏻  the safari issue should be addressable. cc @jdilag90

**Comment by jdilag90** [comment]
@n-ace-ancog @tmcconechy fixed switch focus state in Safari, thanks!

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]
Safari highlight issue is now fixed on my side.

image

**Pull request merged**
