### PR TITLE
webpack: share runtime for normalized modules & update the source-map-loader

### LINKED ISSUE #290: Chore: Improve Bundling to reduce consistency
**Describe the bug**
Something (may) be wrong with our bundling but not sure. 

**To Reproduce**
1. Go to ids-theme-mixin and add
```
import { attributes } from '../ids-base/ids-attributes';

console.log('In IdsThemeMixin');

/**
 * A mixin that adds theming functionality to components
 * @param {any} superclass Accepts a superclass and creates a new subclass from it
 * @returns {any} The extended object
 */
const IdsThemeMixin = (superclass) => class extends superclass {
  constructor() {
    super();
  }
```
2. Go to http://localhost:4300/ids-button
3. Check console

**Requirements**
- We do have the requirement that each component can be imported by itself with what it needs to run standalone/side by side
- We also need each mixin to have its own shared instance i.e. the events mixin has a map and event 
- should not give CSP errors (some bundlers did use an eval which was flagged)

**Expected behavior**
We do have the requirement that each component can be imported by itself. But is there someway to reduce the redundancy?

**Additional context**
We could use import instead and import from the npm folder like the locale scripts do https://webpack.js.org/api/module-methods/#import-1

Or better perhaps changing to ESM will work https://github.com/infor-design/enterprise-wc/blob/main/webpack.config.js#L55-L57

### PR DESCRIPTION
**Pull request by rob2d**
**Explain the details for making this change. What existing problem does the pull request solve?**

(1) changes a parameter to share the runtime across app entry-points as the nature of our library is one global set of instances (#290). 

Fixes a few hidden quirks about using `instanceof` or `Ids{Component}.prototype` consistency in mixins/callbacks and saves a tiny bit of RAM/time executing JS on-load.

(2) adds `source-map-loader` to debug some types of problems a bit quicker.

**Related github/jira issue (required)**:

Fixes #290 

**Steps necessary to review your pull request (required)**:

- pull this branch
- run `npm i`
- close browser or run in incognito/hard refresh

- open Chrome Dev Tools => Source Tab => Ctrl + P  and search an ids component
image
- should see the compiled source map vs the webpack dist
- breakpoints work (but one caveat: since the code is source-mapped on first load, going another level now does not work oddly. But the source-maps seem to be correct/loaded by default now)

- visit http://localhost:4000/ids-pager
- open Chrome Dev Tools => Sources Tab => Ctrl + P and search for `ids-theme-mixin`
- put a breakpoint by clicking line number 8 and refresh page
- theme mixin module should run the line declaring 1x instead of repeat for each/every component in the app
(does call super class so may need to add parens as that's how I was testing to be sure; alternate method to debug is just old fashioned console.log above the `IdsThemeMixin` declaration)
image

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.
N/A

### CODE REVIEW

**Review by danielortiz1982 — APPROVED** [review]
@rob2d This is a great solution for this issue, good find adding the **source-map-loader** plugin and changing the runtimeChunk to a single app. I think there could be some small improvements on the code splitting strategy but for now I think this will work fine.

**Review by tmcconechy — CHANGES_REQUESTED** [review]
1) Great find on the single part ❤️ 
2) But have some questions about the source-loader addition.

- i read up on it but i dont get what it does?
- we were using terser for the source maps already...so how does it ensure that works properly?
- worse is i can no longer debug the way im used to (or at all?) see attached video

https://drive.google.com/file/d/1zgsg9ZHqSWN-h_OeOymZPHBHxZqrUekn/view

**Review by tmcconechy — APPROVED** [review]
After clarifying what this added with @rob2d i misunderstood part of this. So seems good 👍🏻

**Review by EdwardCoyle — APPROVED** [review]
Really nice to be able to debug the compiled page files, thanks for this @rob2d!

**Pull request merged**
