### PR TITLE
1328 - Update splitter to new design

### LINKED ISSUE #1328: IdsSplitter: Add design changes
**Describe the bug**
Add the new changes from https://github.com/infor-design/enterprise/pull/7587 here. 

**To Reproduce**
- splitter should get this look
- add new examples

**Additional context**
https://github.com/infor-design/enterprise/pull/7587 and attached issues and figma

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Syncs the splitter with the new designs. Also

- changed draggable events to remove prefix
- remove align setting (uneeded since no longer left and right on the splitter)

**Related github/jira issue (required)**:
Fixes #1328 

**Steps necessary to review your pull request (required)**:
- test out examples on http://localhost:4300/ids-splitter
- try themes / rtl ect

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by jdilag90** [comment]
In the Multiple example

1) Move all three splitters to a different position
2) Change Theme
3) Again, move all three splitters to a different position
3) Change Theme

The splitters suddenly stack to one side and can't be dragged afterwards

**Comment by tmcconechy** [comment]
@jdilag90 ~ that issue is fixed now

**Comment by jdilag90** [comment]
@tmcconechy looks like the draggable splitter bars are missing in RTL languages. 
Might be an a issue that deserves its own ticket. The css design changes looks good for approval

**Comment by tmcconechy** [comment]
@jdilag90 good catch. I fixed that as well. (Removed something i should not have)

**Review by jdilag90 — APPROVED** [review]
awesome, lgtm

**Review by clayinfor — APPROVED** [review]
Looks really good 👍

**Pull request merged**
