### PR TITLE
1247 - Add support for two digit year

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Adds two digit year support to datepicker and datagrid filter. Also fixed some UI bugs experienced in the examples i worked on.

Note that any year over 40 is considered in the 1900s and any year under 39 is considered in the 2000s. For example: `21/07/39 = 21/07/2039` and `21/07/40 = 21/07/1940`.

**Related github/jira issue (required)**:
Fixes #1247 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-date-picker/sandbox.html
- try the last two pickers for digit year
- go to http://localhost:4300/ids-data-grid/filter-trigger-fields.html
- try to filter on the two digit year column

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by deep7102** [comment]
Looks good, found one as below
- month/year picker not have current month/year selected
- just a thought, in those demos only should have set setting min/max dates so they do not go over the limit. Currently if choose any out of limit date and open it back it looks weird because it have different year.

`2000s-picker max-date:12/31/2039`, and `1900s-picker min-date:01/01/1940`

**Comment by jdilag90** [comment]
In the [sandbox example](http://localhost:4300/ids-date-picker/sandbox.html), the date-picker popups are closing immediately after they're opened a second time

**Comment by clayinfor** [comment]
hey @tmcconechy , I see the same thing that @jdilag90 sees--the date picker popup is immediately closing when trying to interact with it again, after selecting a date the first time.

**Review by clayinfor — DISMISSED** [review]
Code looks good 👍 ... popups works fine on first interaction, but starts closing immediately on subsequent interactions... not seeing where this might have been caused in code.

**Comment by tmcconechy** [comment]
ok guys i fixed the popup issue ~ please try again @clayinfor @jdilag90

**Review by jdilag90 — APPROVED** [review]

**Review by deep7102 — DISMISSED** [review]

**Pull request merged**
