### PR TITLE
2701 - Add fixes to the listbuilder styles

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-wc/issues/2701

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-list-builder/example.html
- click edit and edit the items
- notice the height and style is fixed
- select another item by both clicking the text and farther down to the right
- after selecting edit should edit the right item

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by jdilag90** [comment]
looks good, just some tests failed

**Review by jbrcna — DISMISSED** [review]
image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Looks good.

https://github.com/user-attachments/assets/b4c5e332-7d3d-470e-8bec-6d33dcf7fb5c

But, opening the example link on a new tab results in an uncaught error.

image

https://github.com/user-attachments/assets/3abf9258-8f26-4868-b345-e712e4d1587a

**Comment by tmcconechy** [comment]
@n-ace-ancog can you explain how to get that error (open on a new tab?)

**Comment by n-ace-ancog** [comment]
@tmcconechy, on your steps to review this PR. Right click the example page link you've provides and open in a new tab.

**Comment by tmcconechy** [comment]
@n-ace-ancog pushed a fix for the right click issue.. please try (wierd one)

**Pull request merged**
