### PR TITLE
871 - Fixed dirty tracker with lookup

### LINKED ISSUE #871: idsLookup: Dirty tracker cannot be reset
**Describe the bug**
Dirty tracker cannot be reset

**To Reproduce**

1. https://main.wc.design.infor.com/ids-lookup/example.html
2. remove 3 on dirty tacker lookup
3. lose focus or click anywhere on the page
4. type 3 again to reset dirty tracker
5. lose focus or click anywhere on the page
6. click search icon
7. select an item
8. see error
9. notice that dirty tracker is not shown

**Expected behavior**
dirty tracker should be reset and shown

**Version**
(https://main.wc.design.infor.com/)

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://www.screencast.com/t/4pwQGMXf

**Platform**
 - Browser Name: [All Browsers]

**Additional context**
None

### PR DESCRIPTION
**Pull request by deep7102**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed the dirty tacker was not able to reset with lookup

**Related github/jira issue (required)**:
Closes #871 
Fixes https://github.com/infor-design/enterprise-wc/issues/806

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app
- Navigate to: http://localhost:4300/ids-lookup/example.html
- Use 1st lookup titled `Normal Lookup (dirty-tracker)`
- Remove `3` (last char)
- Lose focus or click anywhere on the page
- Dirty tracker icon will display
- Type back `3` again
- Lose focus or click anywhere on the page, it should reset (remove dirty tracker icon)
- Click on search icon, to open lookup modal
- Select any item/s
- It should add/remove dirty tracker icon as need

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Looks great. @deep7102 but i did see some tests fail, but i updated the branch and am trying again

**Comment by tmcconechy** [comment]
@deep7102 this is the build error https://github.com/infor-design/enterprise-wc/runs/8158487789?check_suite_focus=true#step:11:286 maybe you introduced a leak? Or we have to skip these for now?

**Comment by clayinfor** [comment]
@tmcconechy @danielortiz1982 , hey guys, sorry to message you here (will delete soon after)... please let Luca know that I'm trouble logging into my account... Many thanks!

**Review by andriivarhanov — COMMENTED** [review]
I can confirm #806 is fixed, the only issue is datagrid selection doesn't sync when you trying to change lookup value programmatically, steps to reproduce:
- go to http://localhost:4300/ids-lookup/example.html
- `document.querySelector('#lookup-1').value = '101'` in the console
- open the datagrid modal, see 102,103 selection is still there

**Comment by deep7102** [comment]
> I can confirm #806 is fixed, the only issue is datagrid selection doesn't sync when you trying to change lookup value programmatically, steps to reproduce:
> 
>     * go to http://localhost:4300/ids-lookup/example.html
> 
>     * `document.querySelector('#lookup-1').value = '101'` in the console
> 
>     * open the datagrid modal, see 102,103 selection is still there

Thanks! @andriivarhanov, good found.
Please review It's updated and should fixed now

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
