### PR TITLE
1010 - Add schema data for better intellisense

### LINKED ISSUE #1010: Component schemas for IDE intellisense
**Is your feature request related to a problem or use case? Please describe.**
When writing HTML that uses the `ids-enterprise-wc` components, there is no help from the IDE (vscode). There is no way to know whether something is miss-spelled, or if using an attribute that doesn't exist. There is also no way to "discover" the API of a component other than reading the documentation.

**Describe the solution you'd like**
There is [a (in progress) standard/schema](https://github.com/webcomponents/custom-elements-manifest) for how a module should describe the custom elements that it provides. There is also a way to [configure VS Code](https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md) to read a file containing the schema for a component library. The JSON Schema can be found [here](https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.schema.json).

I propose that such a file be generated automatically when building the `ids-enterprise-wc` library and included in the package. It could of course be written by hand, but I imagine that would require a lot of work and be error prone.

**Describe alternatives you've considered**
If there was a way to achieve this through TypeScript typings, I guess that would be preferable. That would allow type-checking and completion for things like `document.createElement("ids-<Ctrl+Space for completion>` and `someCustomIdsElement.addEventListener("customEve<Ctrl+Space>"`-

I tried the following locally in my project, just to see if it worked:

.vscode/settings.json:
```json
"html.customData": [
  "./ids-enterprise-wc.json",
]
```

and ./ids-enterprise-wc.json:
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vscode-html-languageservice/main/docs/customData.schema.json",
  "version": 1.1,
  "tags": [
    {
      "name": "ids-button",
      "description": {
        "kind": "plaintext",
        "value": "The IDS Button component is a simple wrapper around a standard HTMLButtonElement that is styled with Infor branding, and contains some additional API that makes it easy to set text, icons, and functionality."
      },
      "attributes": [
        {
          "name": "type",
          "values": [
            {
              "name": "primary"
            },
            {
              "name": "secondary"
            },
            {
              "name": "tertiary"
            }
          ]
        }
      ],
      "references": [
        {
          "name": "GitHub",
          "url": "https://github.com/infor-design/enterprise-wc/tree/main/src/components/ids-button"
        }
      ]
    }
  ]
}

```
Which makes the "ids-button" component slightly easier to use:

**Additional context**
image
image

And what application do you work on? Homepages & Portal

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Adds a custom schema https://github.com/webcomponents/custom-elements-manifest in standard form and visual studio form to the install package and for use by us as developers.

Added docs on how to use it (will add to the examples as well)

**Related github/jira issue (required)**:
Fixes #1010 

**Steps necessary to review your pull request (required)**:
 - `npm i`
 - `npm run build`
 - open any html file
 - type `<ids` to see all our components are available

 Screenshot 2023-06-27 at 1 12 22 PM

 - type `ids-tag` and then `color` and hover it for intellisense

 Screenshot 2023-06-27 at 1 13 07 PM

 - hover the component name

 Screenshot 2023-06-27 at 1 13 13 PM

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
cc @anhallbe

**Review by jdilag90 — APPROVED** [review]
nice feature to have

**Comment by anhallbe** [comment]
> cc @anhallbe 

I can't test this right now as I'm on vacation. But the code looks good to me!

Really nice feature ❤️

**Review by clayinfor — APPROVED** [review]
🚀

**Pull request merged**
