### PR TITLE
1157 - IdsInput/IdsTriggerField - fix box model

### LINKED ISSUE #1157: IdsTriggerField: Use `display: inline-block` on main elements
**Describe the bug**
IdsTriggerField is currently set up to display its host element and shadow root container as `display: block;`. The result of this is that trigger fields stretch to fill the width of their parent elements.

This behavior doesn't seem problematic until trying to combine the trigger field with elements such as IdsPopup, that use them for anchoring themselves in the page.  In some cases, Popups can appear to be placed "incorrectly" because they are actually aligning against the blank space inside the component, instead of the real parts of the component.

**To Reproduce**
1. Go to https://main.wc.design.infor.com/ids-time-picker/sizes.html.  Make sure the browser window is wide.
2. Click on the "Large (width)" input field's trigger button to activate the popup.
3. See the incorrect placement of Popup (arrow is positioned as intended)

**Expected behavior**
The Popup should be placed correctly.  I suspect changing the display type to `inline-block` on the main trigger field elements will cause the size/location to be correct, but since many components use IdsTriggerField beneath, we need to test them all to prevent any downstream effects.

**Screenshots**
Screen Shot 2023-02-28 at 11 33 45 AM

**Additional context**
Originally discussed in https://github.com/infor-design/enterprise-wc/issues/1155#issuecomment-1448417475 with @andriivarhanov

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR makes some changes to the box model of input/trigger fields for a few reasons:
- Some inner elements of these web components were displaying "too wide"
- Extra width was causing hit area issues (it was possible to click outside these fields and activate them unexpectedly)
- Extra width was also causing attached elements like popups to display in the wrong place on "long enough" input fields

Some changes made include:
- Normalization of host elements, or "outer" elements (css-only) to be `display: block;`
- Changing internal elements (shadow root or nested components) to be `display: inline-block;` in some cases
- Added `max-width` to control size on some elements
- In some cases, needed to support the "full" size attribute with a CSS class on some field types (arguably need to move this behavior to a mixin and DRY it up, but out of scope for this)
- Normalized some internal IdsPopup x/y offsets being automatically set by some components (arguably need an API for doing this at the IdsPopupMenu/IdsPickerPopup level)

The end result of all this should be more accurate field layout, and more accurate popup placement.

**Related github/jira issue (required)**:
Closes #1157

**Steps necessary to review your pull request (required)**:
_Test popup placement on wide input fields:_
- Open http://localhost:4300/ids-date-picker/sizes.html and http://localhost:4300/ids-time-picker/sizes.html
- Stretch the browser window to be wide
- Open the "Large" example on each page.  The Popup should appear aligned against the field (arrow shouldn't be separated)
- Open the "Full" example, and the same should be true
- Shrink the browser viewport to make sure all field sizes that are too big for the column width collapse and fit nicely into the column.

_Test hit area adjustments:_

- Open http://localhost:4300/ids-input/test-sizes.html
- Click the "empty space" at the top-right of where the label should be on any of the IdsInput fields.  Focus should move to the corresponding input field
- Click the "empty space" outside of the "red box" in the screenshot below.  This should NOT focus the field.

Also try this on other component "size" pages and label-state examples:
- http://localhost:4300/ids-dropdown/sizes.html
- http://localhost:4300/ids-date-picker/sizes.html
- http://localhost:4300/ids-time-picker/sizes.html
- http://localhost:4300/ids-lookup/sizes.html

_General smoke test:_
Pick your favorite IdsInput examples, or choose the ones below.  This change hit a lot of low-level code so its possible some changes cascaded that I haven't yet addressed.  So far, I've looked at the examples below and haven't seen anything drastically different (its possible padding/margins/borders adjusted slightly):
- http://localhost:4300/ids-input/example.html
- http://localhost:4300/ids-input/label-state.html
- http://localhost:4300/ids-input/test-sizes.html
- http://localhost:4300/ids-input/standalone-css.html
- http://localhost:4300/ids-trigger-field/example.html
- http://localhost:4300/ids-data-grid/filter-trigger-fields.html
- http://localhost:4300/ids-dropdown/sizes.html
- http://localhost:4300/ids-date-picker/picker-only.html
- http://localhost:4300/ids-time-picker/picker-only.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
looks good, here is some findings, nothing major:
- timepicker dropdown labels (hours, minutes, seconds, period) are not centered
image

- pager input size is bigger
http://localhost:4300/ids-pager/example.html
image

**Comment by tmcconechy** [comment]
@EdwardCoyle I did see an issue and it was around 1368x813 

If you click:
- Small - Medium -> pretty far away

Screenshot 2023-04-05 at 1 06 20 PM

- Medium / Large /Full -> It goes a little too high up.

Screenshot 2023-04-05 at 1 06 46 PM

Also i didnt mean to approve percy but it had a few things to check the ones i see are:
1. https://images.percy.io/6e14cc386648bf24fe7785c3ac940a73619517b345704d30646d4ea7f22d75b3 (looks cut off now)
2. https://images.percy.io/7077aba386f0a180c2451fdafa98388981749feb8686a25740370a3a64634f53 (pager size as mentioned)
3. https://images.percy.io/e11207691804d57464ab3029af3626b32e59f8bae0bfdd0c7efeaa53cab0db64 ( did it get closer)

**Comment by EdwardCoyle** [comment]
@tmcconechy @andriivarhanov I think I've addressed all of your comments.  Popup alignment on these fields should be much better in those edge cases:

Screen Shot 2023-04-06 at 1 10 40 PM
Screen Shot 2023-04-06 at 12 31 16 PM

**Review by andriivarhanov — APPROVED** [review]

**Comment by tmcconechy** [comment]
This may be ok but i see the labels will wrap now.

Screenshot 2023-04-07 at 12 09 10 PM

Just to think about? Maybe its better? http://localhost:4300/ids-dropdown/sizes.html on mobile size

**Comment by EdwardCoyle** [comment]
For other reviewers -- punted that last one to #1223 for now

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
