### PR TITLE
1599 - Change lifecycle

### LINKED ISSUE #1040: IdsTextarea : dirty tracker position is not properly aligned
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-textarea/example.html
2. Type a text in `Dirty Tracking `field
3. See error

**Expected behavior**
image

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image
image

**Platform**
Safari & Firefox

**Additional context**

### LINKED ISSUE #1263: IdsCalendar: Legend expanded but content not visible on first load
**Describe the bug**
When the `ids-calendar` is first loaded the Legend accordion is set to expanded but the content is not visible. After closing then re-opening the accordion the content appears. See attached video of the bug.

**To Reproduce**

1. Go to http://localhost:4300/ids-calendar/example.html
2. Check the legend and see the header is in expanded state but the content is not visible
3. Click on the header and the accordion will close.
4. Click on the header again and the content will be visible.

**Expected behavior**
The content in the legend should be visible on first load.

**Screenshots**
https://user-images.githubusercontent.com/1084735/235226323-1d9aa795-9290-466e-bf88-4b010da01c94.mov

**Additional context**
n/a

### LINKED ISSUE #1466: IdsDatagrid: popupmenu highlight is cut off on first load
**Describe the bug**
in first open, the highlight is cut off. when opening it again the highlight is now fine
try in Safari browser

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-data-grid/filter-custom.html
2. Click to open a filter (color or product id)
3. See error
4. Enter to close
5. Click to open a filter again
6. Notice that the highlight is now fine

**Expected behavior**
highlight shout not be cut off

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

https://github.com/infor-design/enterprise-wc/assets/56722184/a332787d-1798-4e0f-a54b-216ead7f571f

**Platform**
Safari

**Additional context**

### LINKED ISSUE #1488: IdsMultiselect: tag overlaps dirty tracker
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-multiselect/example.html
2. Select items on each drop down
3. See error
4. notice that the tag overlaps dirty tracker 

**Expected behavior**
should have enough room for dirty tracker to show up

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
All major browser

**Additional context**
In safari the X icon looks way more bigger compare to other browsers
image

### LINKED ISSUE #1540: IdsErrorpage: modal container not displayed
**Describe the bug**

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-error-page/example.html
2. See error

**Expected behavior**
image

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
Safari

**Additional context**

### LINKED ISSUE #1590: IdsUploadAdvance: disabled item does not look disabled
**Describe the bug**
In Safari browser, disabled item does not look disabled.
The disabled function is working however. it just don't look disabled

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-upload-advanced/example.html
2. See error

**Expected behavior**
image

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
Safari
**Additional context**

### LINKED ISSUE #1599: IdsStats: Component broken in Safari (17.1)
**Describe the bug**
In safari 17.1 Stats component appears broken. 

See below screenshots:

CleanShot 2023-11-02 at 10 37 55@2x

CleanShot 2023-11-02 at 10 37 58@2x

**To Reproduce**

- open https://main.wc.design.infor.com/ids-stats/example.html in safari

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Changes the way IdsElement works so that the template and styles are appending in the constructor. Along with that a host of needed changes to make everything work.

This improved parenting (moving DataGrid in the DOM) and solves a host of bugs in safari related to this. For future will add #428 to further improve.

WIP: Trying the build out

**Related github/jira issue (required)**:
Fixes #1599
Fixes #1590
Fixes #1540
Fixes #1488
Fixes #1466
Fixes #1263
Fixes #1040

**Steps necessary to review your pull request (required)**:

***Main Changes***
- smoke test component pages
- `npm run build:dist` and copy to the NG and react examples to test

***Safari Bugs Changes***
- test http://localhost:4300/ids-stats/example.html in safari and chrome and should look similar
- test http://localhost:4300/ids-upload-advanced/example.html  in safari and chrome and should look similar (disabled one)
- test http://localhost:4300/ids-error-page/example.html in safari and chrome and should look similar
- test  http://localhost:4300/ids-multiselect/example.html in safari and chrome and should look similar (x is same size now, dirty example removed)
- test http://localhost:4300/ids-data-grid/filter-custom.html (dropdown is correct with in safari)
- test http://localhost:4300/ids-calendar/example.html in safari and chrome and should look similar
- test http://localhost:4300/ids-textarea/example.html (dirty indicator is correct with in safari)

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [ ] A note to the change log (TBD)

### CODE REVIEW

**Comment by jdilag90** [comment]
Still testing but noticed the 'Currency' column dropdowns are out of place (http://localhost:4300/ids-data-grid/editable-inline.html). It's possible it'll get fixed by this PR (https://github.com/infor-design/enterprise-wc/pull/1684) though.

Side note, I found this article helpful
https://medium.com/patternfly-elements/web-components-the-constructor-and-patternfly-elements-606bc51938c9

It warns against doing `attribute manipulation` in the constructor (also in our `template` function)
Just a heads to look out for anything that might do that, you can test via `document.createElement('ids-component')`
image

**Comment by tmcconechy** [comment]
@jdilag90 good article. its fortunate it does give an error if you do it wrong. I think this lifecycle may not be perfect but it works and solves the issues for now. Maybe with @props we can make a new base in the future that is cleaner

`delayRender` is very interesting did not know about it and I can see use cases.

Should we try with https://github.com/infor-design/enterprise-wc/pull/1684 on regarding http://localhost:4300/ids-data-grid/editable-inline.html

**Comment by jdilag90** [comment]
@tmcconechy 
`delayRender` is a custom implementation from that writer for their `PFElement`, not native wc spec.
It basically skips PFElement's `render()` call, and leaves it to the base components to decide when to invoke it.

I checked his library and it looks like he switched to LitElement, which has some features in v3 for async property updates.
Might be worth looking into to implement something similar later on.
https://lit.dev/docs/components/lifecycle/#reactive-update-cycle

**Review by EdwardCoyle — APPROVED** [review]
I tested a lot of pages and haven't seen any issues besides the one @jdilag90 pointed out, and additionally the Dropdowns inside of Timepicker cells doing the same thing (however this was an issue before the changes and is present on `main`).  Tested in both Chrome and Safari.

Screenshot 2023-12-12 at 4 13 44 PM

**Comment by tmcconechy** [comment]
Screenshot 2023-12-13 at 9 57 49 AM

So the problem is this? http://localhost:4300/ids-data-grid/editable-inline.html does seem to be specific to this branch?

**Comment by tmcconechy** [comment]
@EdwardCoyle @jdilag90 -> should be ok now

**Review by jdilag90 — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
LGTM!

**Pull request merged**
