### PR TITLE
Expandable test conversion

### LINKED ISSUE #1935: Tests: Convert Expandable Area Tests
**Describe the task**
Convert Expandable Area tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-expandable-area to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-expandable-area/ids-expandable-area.spec.ts

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by janahintal**
**Explain the details for making this change. What existing problem does the pull request solve?**

Expandable test conversion 

**Related github/jira issue (required)**:

Closes #1935 

**Steps necessary to review your pull request (required)**:

Pull this branch, build, and run the app
Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by ericangeles — CHANGES_REQUESTED** [review]
@janahintal 
- A couple of build issues need to be fixed.
- Add changelog.
- Remove old test.

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Some test case regarding expandable area is flaky in the build run.

**Review by n-ace-ancog — APPROVED** [review]
Seems the test that failed is with the IdsDrawer component.

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Comment by tmcconechy** [comment]
@ericangeles you good here?

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
