### PR TITLE
633 - Add css defaults for no mode

### LINKED ISSUE #633: IdsButton: Requires ids-theme-switcher to work
**Describe the bug**
Some types of buttons (not all tested) do not work (do get the right style) unless a theme switcher is added to the page.

**To Reproduce**

1. Go to http://localhost:4300/ids-about and notice it works
1. edit src/components/ids-about/demos/index.html and remove ids-theme-switcher
1. Go to http://localhost:4300/ids-about and notice it doesnt work
1. See missing styles

This doesnt work on secondary buttons - but does work on primary buttons. So please test all button types for this issue

**Expected behavior**
Should get light theme styles even if there is no ids-theme-switcher

### LINKED ISSUE #649: IdsThemeMixin: Mode change not applying to elements in shadowRoot
**Describe the bug**
Components within the shadowRoot are not receiving mode changes when using the theme-switcher. (noticed in `ids-autocomplete` and `ids-dropdown`

**To Reproduce**

1. Go to http://localhost:4300/ids-dropdown
2. Click on theme-switcher and change to dark mode
3. Open the first dropdown

**Expected behavior**
Dark mode should be properly applied to components inside the shadowRoot.

**Screenshots**

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**
For anything in scss targeting light/new theme and mode added a default for no mode - for if there is no theme mixins.

**Related github/jira issue (required)**:
Fixes #633
Fixes #649

**Steps necessary to review your pull request (required)**:

*Issue Part One*
- edit components/ids-accordion/demos/index.html and comment out `ids-theme-switcher`
- run the page
- the button should look the same with it commented and not commented and when you open the modal the inner text area should be styled in new-light mode with no `ids-theme-switcher`
- see if i missed anything/made a mistake?

*Issue Part Two*
- go to http://localhost:4300/ids-dropdown
- change to dark mode
- open the list and it should look good

### CODE REVIEW

**Review by danielortiz1982 — DISMISSED** [review]

**Review by andriivarhanov — COMMENTED** [review]
I've checked all components and it looks like `ids-progress-chart` needs adjustments 
 http://localhost:4300/ids-progress-chart

Steps:
- go to `src/components/ids-progress-chart/demos/index.html`
- remove theme switcher
- http://localhost:4300/ids-progress-chart
- no backgrounds

**Comment by tmcconechy** [comment]
Thanks @andriivarhanov i have fixed that issue - missed one rule there.

**Review by andriivarhanov — APPROVED** [review]
@tmcconechy looks good, thanks

**Review by jmacaluso711 — APPROVED** [review]
👍  looks good

**Pull request merged**
