### PR TITLE
2411 - IdsLayoutGrid responsive layout inside splitter

### LINKED ISSUE #2411: General: Need an example of a responsive layout
**ISSUE:**

Version: "ids-enterprise-wc": "^1.1.0",

The implemented service (using window.matchMedia) recognizes the device type when resizing the browser, but the HTML is not updated. I tried using CSS media queries, but the same issue occurred. I also tried using Angular CDK breakpoint observer, but the issue persisted.

Please observe the videos below:
https://github.com/infor-design/enterprise-wc/assets/105051938/2013e475-b140-4973-a860-14d7e988fa99
https://github.com/infor-design/enterprise-wc/assets/105051938/b39253cd-003c-441f-9b11-f16dca511dcb

**Expected Behavior:**

Please show how we can make an example like this:

https://github.com/infor-design/enterprise-wc/assets/105051938/5b1d59da-565a-42a9-a79a-a7abccd3e254

### LINKED ISSUE #2454: IdsLayoutGrid: Set individual height for rows
**Is your feature request related to a problem or use case? Please describe.**
Using `IdsLayoutGrid`, I want to be able to specify height for the grid cells.
Here's an example with using only CSS https://jsfiddle.net/kfzh2w08/1/

First row takes only required space, while the second row will take up the remaining space

**Describe the solution you'd like**
image

**Describe alternatives you've considered**
Alternative would be to use CSS grid directly.

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds an example of a responsive layout inside a splitter pane. 

- **Added Container Queries for Responsive Layout**: This PR introduces container queries to the layout within the splitter pane. Container queries allow the layout to adapt dynamically to the size of its container rather than the viewport.

- **hide Attribute in layout-grid-cell**: A new hide attribute has been added to the layout-grid-cell component. This attribute leverages predefined breakpoints to control the visibility of elements within the grid. By setting the hide attribute, specific cells in the layout grid can be hidden or shown based on the size of the container.

- **Enabling Container Queries in the IdsHidden Component**: The PR enhances the IdsHidden component by adding the capability to use container queries. In this specific implementation, the IdsHidden component is utilized to toggle the visibility of the menu button and the caret button in the toolbar, based on the container's size. 

Additionally, this PR introduces a new feature that allows users to define the row structure of a grid layout directly through an attribute in the ids-layout-grid component. Specifically, it adds the capability to set the `template-rows` property, which controls the height of each row in the grid.

```
<ids-layout-grid template-rows="auto 1fr">
  <!-- Grid items go here -->
</ids-layout-grid>
```

**Related github/jira issue (required)**:

closes #2411 
closes #2454 

**Steps necessary to review your pull request (required)**:

- Pull and run branch
- Go to http://localhost:4300/ids-layout-grid/example-inbox.html
- Resize the splitter pane, the form should appear when the container is above the medium breakpoint
- Resize the splitter pane back to below the medium breakpoint. Click the caret button in the toolbar, the form and sidebar should toggle visibility
- Go to http://localhost:4300/ids-layout-grid/example.html
- Scroll down to the Grid Template Rows example.
- The first row should be `auto` and the second should be `1fr`

**Included in this Pull Request**:
- [X] Some documentation for the feature.
- [X] A test for the bug or feature.
- [X] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
@jmacaluso711 this looks really good. Maybe a few minor things in order

1. When loading the page i see a flash where the list is on the wrong side then it shifts over
2. I think the back button behavior is backwards compared to https://main-enterprise.demo.design.infor.com/components/page-patterns/example-list-detail.html in that back goes forward to the page. I think simply clicking a list item would open the detail page instead?
3. The icon could be the arrow back button instead but i dont mind it as is
4. Maybe just shorten the label (something QA would flag)

Screenshot 2024-06-25 at 10 21 13 AM

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
In http://localhost:4300/ids-layout-grid/example-inbox.html, when the form appears and clicked on the dropdown button the popup menu is way off where it appears. The time picker popup menu doesn't show up or far away off the screen.

https://github.com/infor-design/enterprise-wc/assets/156752175/eb913db8-2960-4eba-86d5-24e11a6cef71

In RTL, setting via `IdsGlobal.locale.setLocale('ar-SA')` in console, clicking the time picker results in error.

image

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Same observation with @n-ace-ancog.

https://github.com/infor-design/enterprise-wc/assets/102151352/0a51e237-b8f9-44e3-b117-dfc474b8710e

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

image
image


Also,
- Resize the splitter pane back to below the medium breakpoint. Click the caret button in the toolbar, the form and sidebar should toggle visibility
- Click the time picker
- Resize the splitter pane again
image

**Review by tmcconechy — APPROVED** [review]

**Comment by jbrcna** [comment]
> image image image
> Also,
> 
> * Resize the splitter pane back to below the medium breakpoint. Click the caret button in the toolbar, the form and sidebar should toggle visibility
> * Click the time picker
> * Resize the splitter pane again
> 
> image

this is now fixed. 
image

**Comment by tmcconechy** [comment]
@n-ace-ancog @jmacaluso711 lets make new issues for anything else here

**Pull request merged**
