### PR TITLE
1456 - Add example for IdsDataGrid `setActiveCell()`

### LINKED ISSUE #1456: Datagrid: SetActiveCell do not work if rowNavigation is set to false
**Describe the bug**
SetActiveCell do not work if rowNavigation is set to false

**To Reproduce**

1. Go to http://localhost:4300/ids-data-grid/example.html
2. Open Dev tool 
3. Make sure rowNavigation is set to false (document.querySelector("#data-grid-1").rowNavigation = false)
4. Then set any cell active through dev tools: document.querySelector("#data-grid-1").setActiveCell(0, 4)
5. Notice nothing happens
*Note : When row navigation is set to true setActiveCell works as expected

**Expected behavior**
A cell should be activated

**Version**

- ids-enterprise-wc: Sept. 5, 2023 main

**Screenshots**
https://github.com/infor-design/enterprise-wc/assets/122866382/15f43e7b-3a1d-484f-9b31-361f9d0c83a0

**Platform**
- Infor Application/Team Name: M3 UX
- OS Version: Windows 11
- Browser Name: chrome
- Browser Version: Version 116.0.5845.140 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds a demoapp example for the data grid's `setActiveCell` method, which "focuses" cells but doesn't appear to do so when testing with dev tools.  The example page provides a few controls to make it easier/obvious to test that the cell is in fact being activated.

**Related github/jira issue (required)**:
Closes #1456

**Steps necessary to review your pull request (required)**:
- Pull/build/run
- Open http://localhost:4300/ids-data-grid/set-active-cell.html
- Use the form controls to activate different cells.  Try both enabling/disabling the `rowNavigation` for different results.

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — DISMISSED** [review]
Looks good. Just some lint errors (multiple imports)

**Review by tmcconechy — APPROVED** [review]

**Review by jdilag90 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@EdwardCoyle up to you if you can fix that or make a new issue?

**Review by tmcconechy — APPROVED** [review]
Fixed it @EdwardCoyle your fix did work but i needed to change the background color in dark mode as well as the cell.

The main reason i just recalled is for http://localhost:4300/ids-data-grid/columns-frozen.html when you scroll the frozen column. If it was transparent it didnt work. So needed this on the frozen cells still

**Review by jdilag90 — APPROVED** [review]

**Comment by tmcconechy** [comment]
Merging as previously approved. Coverage threshhold changed to 75% for now

**Pull request merged**
