### PR TITLE
759 - IdsDropdown clearable example/feature

### LINKED ISSUE #759: IdsDropdown: Add clearable example/feature
**Is your feature request related to a problem or use case? Please describe.**
Add an example of a clearable x on the dropdown in addition the ability to clear via a blank item

- hopefully works via trigger field having it (for the x)
- add example to both multiselect and dropdown. 
- delete/backspace should activate the button
- for blank option, selecting it with the keyboard should be possible

**Describe the solution you'd like**
Clearable like https://main-enterprise.demo.design.infor.com/components/dropdown/example-clearable.html

**Describe alternatives you've considered**
N/A

**Additional context**
#601

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
The PR adds clearable functionality to `ids-dropdown` and `ids-multiselect`. 

**Related github/jira issue (required)**:
Closes #759 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-dropdown/clearable.html
- focus any of the examples and press Backspace or Delete on your keyboard
- see the value being cleared
- check Clearable (Custom Text) example with custom blank option text
- go to http://localhost:4300/ids-multiselect/clearable.html
- focus second example (empty)
- select some tags and press Backspace

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
~- [ ] A note to the change log.~

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Looks good. I was thinking that in the case of dropdown "clearable" means the way it was in the previous examples with keyboard to clear and blank item instead of an X. I do like the way you did it but:

- I wonder if the backspace / delete should just remove it instead of doing two actions (as it means you cant clear it only with the keyboard). So maybe we skip the x like before and just remove/blank on delete/backspace?
- in the "regular clearable" if i do: delete and click the X then open the list, it now has a blank item in it when it didn't initially
- should we add the ability to set the text of the blank item like before?

**Comment by tmcconechy** [comment]
@andriivarhanov quick heads up i merged that big PR and some small merge conflicts now to review for you.

**Comment by andriivarhanov** [comment]
>  quick heads up i merged that big PR and some small merge conflicts now to review for you.

@tmcconechy sure, no problem

**Comment by andriivarhanov** [comment]
- changed the ability to remove value from x button to delete/backspace keyboard press
- added `clearable-text` attribute to add custom text to the blank option

**Review by EdwardCoyle — COMMENTED** [review]
@andriivarhanov This is looking good, but a couple things:

- I can't seem to clear the "Clearable (Custom Text)" example on http://localhost:4300/ids-dropdown/clearable.html with the keyboard.  Everything else seems ok.
- On the multiselect examples, after you clear the contents of the input field, it seems that the list still contains checked items.  I dug into this a bit to see, and it looks like there's an incorrectly named custom element in the Multiselect's light DOM.  Not sure if this affects it or not:

Screen Shot 2022-08-12 at 10 24 17 AM

**Comment by andriivarhanov** [comment]
@EdwardCoyle thanks for the feedback, I've added ability to clear custom text example and fixed multiselect has selected items in the list after value was cleared

**Review by EdwardCoyle — APPROVED** [review]
Thanks @andriivarhanov, looks great 👍

**Review by tmcconechy — APPROVED** [review]
Thanks again @andriivarhanov !

**Pull request merged**
