### PR TITLE
IdsElement ::host support and mock test decoupling

### PR DESCRIPTION
**Pull request by rob2d**
**Explain the details for making this change. What existing problem does the pull request solve?**

There were potential issues with `::host` (vs `:host`) not tested that make IdsElement unpredictable in some use cases, since this is a criteria. So added support for that small variant + de-hardcoded/coupled stylemock from some related tests that were also having issue there on another branch.

Pushing this here separately as not to further bloat upcoming PRs.

**Related github/jira issue (required)**:

Related to work on enterprise/issues/5026 -- but can help others not figure out what went wrong on tests in future scenarios.

**Steps necessary to review your pull request (required)**:

- pull `ids-element-host-css-and-mock-iteration`
- `npm run test -- ids-base-func-test`

Should work as expected.

**Included in this Pull Request**:
- [X] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by rob2d** [comment]
Example of why code-coverage == 100% is not a good barometer for builds passing in this PR: 

simple change for quality of test increased => coveraged decreased.

**Comment by rob2d** [comment]
Things I tried: 

- double-checked logic
- debugged tests, 
- ran locally. 
- changed logic for regex it fails on to match "absolutely anything or nothing @ IdsElement.js => LN 116 " (`[\s\S]*`)

It seems to be a bug in coveralls reporting here  @ `IdsElement.js` since `:host`, and `::host` are set on the `ids-tag` and clearly converted to `.ids-tag`. 

So it's not running through the conditional found in `IdsElement.appendStyles` for some reason or another even though it clearly replaces content, and then does not report that it went through this.

Seems unideal/unoptimal but I'll just do as we did before PR and `.replace()` with tag name on the entire stylesheet string without conditionals.

**Comment by rob2d** [comment]
With some help from Ed to understand the coverage tool, got it solved: 

Seems that the Jest environment was already mimicking Firefox behavior with (missing) support for some W3C things vs the inverse as we may have thought. 

After setting cssStyles to end-result before re-render() manually, coverage is 100% now.

**Review by tmcconechy — DISMISSED** [review]
Looks good - assuming checks pass...

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — DISMISSED** [review]

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
