### PR TITLE
1417 - Add more features to IdsModuleNav

### LINKED ISSUE #1417: IdsModuleNav: Remaining Features/Issues
**Original Issue: #1226**
**PR: #1416**

**Major:**

- [x] Enhance IdsIcon to support Module Nav app icons, or create example using custom icon system to implement these icons
- [x] Implement tooltip support in "collapsed" display mode
- [x] Implement empty state when no filter results are available
- [x] Add IdsModuleNavItem styles to make text appear beneath ellipsis when cut off by overflow
- [x] Dark/Contrast modes
- [x] Complete Design Q/A from last round of EP module nav ([Figma doc](https://www.figma.com/file/bL4EBYtWjgfBsvTVI9seXU/branch/eHul2nKNMdypFLSb55ZwR1/Module-Nav-%7C-Application-Menu?type=design&node-id=5833-86117&mode=design&t=Mvmyyo78nc1YakaX-0))
- [ ] In RTL Mode when expanded the settings doesnt work https://github.com/infor-design/enterprise-wc/issues/1226#issuecomment-1683601386

**Minor:**

- [ ] Enhance IdsModuleNavItem's support for 6-level-deep accordion nesting
- [x] Check hover state on IdsSearchField when filtering is active vs when it's not

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds a number of changes to IdsModuleNav:
- Adds/Integrates abbreviated app icons
- Adds the "no results" empty state icon when a filter occurs and no results are provided
- Adds tooltip support for truncated text on Expanded display mode, and in all cases on Collapsed display mode
- Adds Dark/Contrast themes
- Fixes many styles to be in-line with latest design Q/A

**Related github/jira issue (required)**:
Fixes #1417 

**Steps necessary to review your pull request (required)**:
Pull/build/run, then test the following scenarios

_App Icon:_
- Open http://localhost:4300/ids-module-nav/example.html
- See the currently-selected app icon.
- Use the Role Switcher dropdown to select a different icon
- Also see these icons on http://localhost:4300/ids-icon/custom-icon.html

_Empty state icon:_
- Open http://localhost:4300/ids-module-nav/example.html
- Switch to "Expanded" display mode
- Use the search input to search for a term that doesn't match the accordion headers (I used "popup")
- See that there is a "no results" icon that appears

_Filter behavior:_
- Open http://localhost:4300/ids-module-nav/example.html
- Switch to "Expanded" display mode
- Filter for any search term
- Use the "Display Mode" dropdown OR the hamburger button to switch back to collapsed mode, then switch to expanded mode again.  The filter should be clear, and no search term should be present in the search field.

_Tooltip support:_
- Open http://localhost:4300/ids-module-nav/example.html
- In collapsed mode, hover the App icon, any of the module buttons, or the settings button.  All should produce a tooltip with their corresponding text
- In expanded mode, hover the "My configuration and personalization" header.  This one should produce a tooltip, but the other top-level headers should not due to their text not appearing within ellipsis

_Theme support:_
- Open http://localhost:4300/ids-module-nav/example.html
- Use the theme switcher to check the Dark/Contrast themes.  Compare with https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html (this example isn't perfect but most of the colors should match)

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
Looks great! Some smaller suggestions:

1. There is a lint warning on [ids-module-nav-common.ts](https://github.com/infor-design/enterprise-wc/pull/1496/files#diff-57c0965cce7f9a6eb3bf4116f4b2dc7c97bf8be6f3f4ab92c8ac3ab2d6c97ede) (jsdoc)
2. I think this tooltip would look better not wrapped on 3 lines

Screenshot 2023-09-22 at 12 02 50 PM

3. The background color of the text on the search was white on https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html

Screenshot 2023-09-22 at 12 01 37 PM

4. Something seemed to have changed effecting the focus state on dropdown

Screenshot 2023-09-22 at 12 05 32 PM
Screenshot 2023-09-22 at 12 05 36 PM

**Comment by EdwardCoyle** [comment]
@tmcconechy good catches, all should be fixed

**Review by tmcconechy — APPROVED** [review]

**Comment by jdilag90** [comment]
Looks nice!
Only thing I could find is that tooltips don't show for module buttons when in RTL language

**Comment by EdwardCoyle** [comment]
@jdilag I think the RTL problem is something deeper we need to deal with in the IdsPopup.  It's also an issue with the collapsed mode's settings menu.  Will raise another issue for this

**Review by jdilag90 — APPROVED** [review]

**Pull request merged**
