### PR TITLE
2527 - IdsSplitter Fix pane position when collapsed/expanded

### LINKED ISSUE #2527: IdsSplitter - splitter position isn't retained when expanding and collapsing.
**Describe the bug**
The splitter position seems to get lost when expanding and collapsing. It seems to return to the initial 25% in the example only it puts that 25% on the right pane.

This is related to https://github.com/infor-design/enterprise-wc/issues/2083

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-splitter/expand-collapse.html - Notice the left split pane is at 25%.
2. Click on expand collapse button to collapse the left split pane and again to expand it
3. Notice the splitter is not it the original position. It seems to be setting the right split pane to 25%

**Expected behavior**
Expect calling expand to restore splitter to it's previous location.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

Animated GIF showing the issue

splitter-position

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11 
 - Browser Name: chromeVersion 126.0.6478.61 (Official Build) (64-bit)126.0.6478.61

**Additional context**

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed right pane width when collapsing/expanding and included right pane to the expand/collapse test

**Related github/jira issue (required)**:
Closes #2527

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4300/ids-splitter/expand-collapse.html
- click on expand/collapse button to collapse the left pane
- click again to expand it
- see the left pane and right pane retain their original position i.e. width

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Seems to have an issue when in RTL. The list disappears even after expanding.

https://github.com/user-attachments/assets/b7cf6b84-854a-4e6a-872d-75a0e963d812

Seems like this is also in baseline.

https://github.com/user-attachments/assets/5ba37c2f-9ce2-4710-bbc7-c30f2a111d7e

**Review by jbrcna — DISMISSED** [review]
the issue still exists 
Large GIF (1602x804)

**Comment by andrivarhanov** [comment]
fixed collapse/expand for **RTL**, steps to review the same just switch locale 
@n-ace-ancog thanks for spotting it

**Review by n-ace-ancog — APPROVED** [review]
Very nice! Looks good now on my side.

https://github.com/user-attachments/assets/d66235a5-e0d7-4fb2-9cdc-5593c33ddaa8

**Review by glenlieorillo — APPROVED** [review]
https://github.com/user-attachments/assets/8e5ecd70-0169-4f17-9d7c-b93a79d9fd90

**Review by jbrcna — APPROVED** [review]
Large GIF (1342x876)

**RTL** 
Large GIF (1342x876)

**Review by jdilag90 — APPROVED** [review]

**Pull request merged**
