### PR TITLE
2382 - ids-card ids-data-grid styles

### LINKED ISSUE #2382: IdsDataGrid: Freeze header when scrolling inside IdsCard
If you put datagrid inside ids-card, the card-content slot will then have a scroll and this will make the column header move with when scrolling.

Also, I tried attaching listener to scrollend event, both to IdsDataGrid and the ```<div slot="card-content">```, but it doesn't work since the scroll belongs to template slot ```<div class="ids-card-content" part="content">``` and I have no way to access that. I was trying to implement infinite scroll from https://main.wc.design.infor.com/ids-data-grid/infinite-scroll.html

Please see [stackblitz](https://stackblitz.com/edit/ids-enterprise-wc-v1-visymm?file=main.js) for demo.

**Describe the solution you'd like**
It would be better if the column headers stay in place while scrolling.

As for infinite scrolling, please advise if there is a way to implement the IdsDataGrid inside IdsCard.

**Additional context**
https://stackblitz.com/edit/ids-enterprise-wc-v1-visymm?file=main.js

IdsDatagridHeader

Label is **team: M3**

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixed `ids-card` styles when `ids-data-grid` is embedded within the card-content slot. 

**Related github/jira issue (required)**:

Closes #2382 

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm i && npm run start`
2. Go to: http://localhost:4300/ids-card/data-grid.html
3. Scroll all the way to the bottom of the grid, and side-to-side.
4. Ensure the `ids-card` and `ids-datagrid` styles and header look good.
5. Compare to stackblitz: https://stackblitz.com/edit/ids-enterprise-wc-v1-visymm?file=main.js

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image

**Comment by n-ace-ancog** [comment]
The datagrid over the card is working, but the bottom sides of the grid seems to overlap beyond the card.

image

**Review by tmcconechy — APPROVED** [review]
@jbrcna I fixed the Gap since Clay is out.

**Review by jbrcna — APPROVED** [review]
image

**Pull request merged**
