### PR TITLE
2484 - Fix Misc Slider Bugs

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes a 3-pack of slider bugs. See steps below.

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-wc/issues/2751
Fixes https://github.com/infor-design/enterprise-wc/issues/2733
Fixes https://github.com/infor-design/enterprise-wc/issues/2484

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-slider/min-max-step.html
- test out the sliders with min/max and larger max totals on this page
- go to http://localhost:4300/ids-slider/vertical.html
- try dragging the range vertical slider. once done dragging it should stop and not change value like the video before

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by andrivarhanov — COMMENTED** [review]
there is some issue with 0-10000 range slider (the last one) on the page http://localhost:4300/ids-slider/min-max-step.html once done dragging it returns to the 0 position

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Found the following issues:

**Horizontal**
1. The last slider is not working

https://github.com/user-attachments/assets/07833f65-d90e-449e-8254-99b3de8e6227

2. The 3rd slider is ahead of some steps. Change the value to 20, 30, 40 and 50, the slider seems to be in front of the steps.

image

3. Changing the `type` to `range` seems to be not working. Enter `document.querySelector('ids-slider').type = 'range'` in the console.

https://github.com/user-attachments/assets/1420ad14-def0-418c-a18b-fbde3ad6f8a5

**Comment by tmcconechy** [comment]
@andrivarhanov @n-ace-ancog I fixed the issue you both reported with the 10000 slider at the bottom. I also fixed issue 2) about the thumb not being right on the slider tick. But i cant seem to fix being about to change it to  `range` this is something that has to be done at the first initialize and doesnt seem like a use case right now so punting that for later.

**Review by andrivarhanov — DISMISSED** [review]

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
The slider doesn't stop at the exact number.

https://github.com/user-attachments/assets/6bee0ced-2ea4-4da5-ad68-b746132085df

image

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Still found some issues regarding the sliders:

1. The last slider seems to be able to change value, but its "super sensitive" while changing it. It can sometimes revert the value to zero on its own even when changing to almost the max value.

https://github.com/user-attachments/assets/2c0118dc-e371-4f72-a8f3-5e08a6720021

2. The alignment issue still seems to be existing

image

**Review by jbrcna — CHANGES_REQUESTED** [review]
the slider seems to work with intervals. However, I find it difficult to navigate between range
Large GIF (1592x798)

**Comment by tmcconechy** [comment]
@jbrcna i think your issue was fixed if you pull and try again. @n-ace-ancog i'll look at those. The alignment one is proving difficult to figure out

**Comment by tmcconechy** [comment]
@jbrcna @glenlieorillo @n-ace-ancog -> Can you retest i think i fixed everything

**Review by glenlieorillo — CHANGES_REQUESTED** [review]
Still failing on my end. Upon moving the slider from `80`/`85` going to the next point, it stops at `81`/`86`.
image

image


https://github.com/user-attachments/assets/c58951e5-c29e-4719-a111-c1161a6304ff

**Comment by tmcconechy** [comment]
@glenlieorillo Thank  you. Fixed that issue (rounding error)

**Comment by jbrcna** [comment]
notice that it is possible to select 86 but what is shown is 85. this can't be done in other numbers
image

**Review by glenlieorillo — DISMISSED** [review]
This is now working as expected on my end. Thanks, @tmcconechy!

https://github.com/user-attachments/assets/451f3ee8-1682-4fdd-ad5b-85123778e34d

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Seems like there's this issue now on smaller scale values.

Clicking on the first step sometimes doesn't work, but clicking on consecutive steps always works.

https://github.com/user-attachments/assets/30f02bc7-3c4a-40bc-a9fe-cffb37065132

On the 3rd slider, you need to click in advance to go to the actual step.

https://github.com/user-attachments/assets/8464ce96-21c3-48ff-93c9-72469bc3ff6d

**Comment by tmcconechy** [comment]
@n-ace-ancog i think i fixed the very last point you mentioned about clicking right on it

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
@tmcconechy the horizontal issues are now resolve on my end. Seems like on the vertical, there's an issue on the step slider.

**Horizontal**

https://github.com/user-attachments/assets/eb3311ff-6bb4-4634-a748-d07a91f07757

**Vertical**

https://github.com/user-attachments/assets/bf61f5e2-6467-4ae6-9a32-61bd8e3cb649

**Comment by jbrcna** [comment]
same observation on my end.
Large GIF (1058x666)

**Comment by tmcconechy** [comment]
Added yet another fix @n-ace-ancog for that last issue

**Review by jbrcna — APPROVED** [review]
Great work! @tmcconechy , works on my end. 
Large GIF (1058x666)

**Review by n-ace-ancog — APPROVED** [review]
Working on my end. Great work @tmcconechy!

https://github.com/user-attachments/assets/f14826f4-fa76-4578-8597-6b06f6b9ee05


https://github.com/user-attachments/assets/7c7ccd85-28ec-4bae-8366-a5575ca6ef35

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
