### PR TITLE
1131 - Adds events that render each time an event is added/removed

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Adds a `beforeeventrendered` and `aftereventrendered` respectively to the weekview, monthview and calendarview component. In addition renamed the weekview events from render to rendered.

CC @LilBiggs -> this needs confirming it can solve the use cases. I tried setting the height on the event element and it seemed to work

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-wc/issues/1131

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-calendar/example.html -> whatch the console fire for each event  (it can fire a lot)
- switch between day and month view -> whatch the console fire for each event (it can fire a lot)
- go to http://localhost:4300/ids-week-view/example.html -> whatch the console fire for each event  (it can fire a lot)
- switch between day and month view -> whatch the console fire for each event (it can fire a lot)
- for http://localhost:4300/ids-month-view/example.html the events are not rendered for this month but it is covered by tests, can be confirmed if desired by changing the events dates to match the presented date (year = 2018 in the DOM)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by LilBiggs** [comment]
@manoj-kothuri - I think these changes will work for the positioning of our event pills. However we may still have an issue with the isOverflowing logic.

**Comment by jdilag90** [comment]
@manoj-kothuri regarding the overflowing issue, is it that since the pill sizes can vary, the calculation for `isOverflowing` needs to be dependent on the sum of pill heights rather than # of event pills in a day cell?

**Review by clayinfor — APPROVED** [review]
👍

**Review by jdilag90 — APPROVED** [review]

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri - I think these changes will work for the positioning of our event pills. However we may still have an issue with the isOverflowing logic.

@LilBiggs - I have used these listeners and now we can position the custom event pills including isOverflowing logic as expected when switched between views.

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri regarding the overflowing issue, is it that since the pill sizes can vary, the calculation for `isOverflowing` needs to be dependent on the sum of pill heights rather than # of event pills in a day cell?

@jdilag90 - Yes we are "**isOverflowing**" calculation logic is based on the height of event pills and will be decided how many pills can be fitted in a day cell.

**Pull request merged**
