### PR TITLE
2607 - Add validation for range

### LINKED ISSUE #2607: IdsDatepicker: Allows invalid input when manually edited
**Describe the bug**
The IDS date picker is allowing incorrect dates when manually edited. It accepts the invalid dates that are entered manually.

**Steps to reproduce the behavior:**
1. Open https://main.wc.design.infor.com/ids-date-picker/range.html
2. When you try to select any date and click "Apply," then attempt to edit the date with incorrect input, it accepts the input instead of rejecting it. (Please refer to the snippet below.)

**Expected behavior**
Date picker behavior should be that invalid dates are not allowed when manually entered.

**Version**
- ids-enterprise: 1.3.0

**Screenshots**
image

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Ports over the validation from Enterprise for range pickers and adds an example.

**Related github/jira issue (required)**:
Fixes #2607 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-date-picker/range.html
- pick a date in the picker
- change the last day to 33 which is invalid
- see error
- fix the date
- NOTE: There are some mask edits not working on range https://github.com/infor-design/enterprise-wc/issues/2715 punted this to another issue as need some assistance with a fix

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by andrivarhanov — DISMISSED** [review]
looks good

**Review by jbrcna — CHANGES_REQUESTED** [review]
issue still exists
Also, notice the calendar icon focus
image

**Comment by tmcconechy** [comment]
@jbrcna fixed the hover state a bit. But please note i only added the validation message https://github.com/infor-design/enterprise-wc/issues/2715 is still an issue for later. (See steps again)

**Review by andrivarhanov — APPROVED** [review]

**Review by glenlieorillo — APPROVED** [review]
The `Range - Validation` is working as expected.

image

**Comment by jbrcna** [comment]
> @jbrcna fixed the hover state a bit. But please note i only added the validation message #2715 is still an issue for later. (See steps again)

thanks @tmcconechy . approving

**Review by jbrcna — APPROVED** [review]

**Pull request merged**
