### PR TITLE
132 - Add  dropdown component

### LINKED ISSUE #132: IdsDropdown: Add new web component
**Describe the bug**

Bring over the current dropdown component.  See if we can simplify and improve the code at all while improving as we go. Current dropdown component https://master-enterprise.demo.design.infor.com/components/dropdown see https://vaadin.com/components/vaadin-select/html-examples for ideas

```
<ids-dropdown label="Dropdown Example" disabled="false">
 <template>
    <ids-list-box>
      <ids-list-item>Value</ids-list-item>
    </ids-list-box>
 </template>
</ids-dropdown>
```

**Functionality to bring over**
- Supports Accessibility 
- Supports Ajax (callbacks)
- Supports Dataset
- Supports Groups
- Supports Icons
- Supports Tooltip
- Supports Placeholder
- Supports Basic States Disabled 
- Supports Virtual Scrolling

**Additional context**
- 100% test coverage
- DOCS, CHANGE log ect. 
- https://github.com/infor-design/enterprise-wc/blob/master/doc/CHECKLIST.MD
- themes 

See completed components like card, tag, badge, hyperlink as reference

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR mainly adds the dropdown component and some related fixes needed to support it. The fixes include:

- readonly trigger fields
- popup styling for dropdown
- fixes some bad links in examples
- made the demo page open 
- removes some un-needed ts @type comments
- Adds a list-box component for the list
- fixes to popup menu to add a flipped class
- changes trigger field to not append classes for content border

**Related github/jira issue (required)**:
Fixes #132 

**Steps necessary to review your pull request (required)**:
- test page http://localhost:4300/ids-dropdown
- try keyboard and all features on this page
- test page http://localhost:4300/ids-color-picker  (for trigger changes)
- test page http://localhost:4300/ids-trigger-field (for trigger changes)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by danielortiz1982 — APPROVED** [review]

**Review by EdwardCoyle — DISMISSED** [review]
This looks really good!  I found a couple of minor usability nitpicks that might be better suited for a Phase 2, but figured should note them here:

- Per the current behavior of the No Search dropdown, the typeahead feature should allow selection of the next matching item matching the key phrase typed.  For example, goto https://main-enterprise.demo.design.infor.com/components/dropdown/example-index.html and:
  - Focus the dropdown without opening it (via keyboard or click the label)
  - Tap "t" to select "two"
  - Tap "t" again to select "three"
  - Try tapping multiple letters to half-spell something like "fo" or "fi".
  - In all cases the typeahead works without the list opening.
  - This should also work when the list is open.
- When using the keyboard arrows to open the menu, there's a slight jump in the list scrolling that isn't there when using enter or clicking
- Really minor but if the Dropdown's not using an input field (noSearch mode) it should probably use the pointer mouse cursor instead of the text cursor.

I'm willing to approve in any case 👍

**Comment by tmcconechy** [comment]
ok, im going to take a look at those. The cursor was a pointer as i added an option to ids-input for cursor but i think maybe i merged it out. I'll take a quick pass and update after.

**Comment by tmcconechy** [comment]
@EdwardCoyle fixed all three issues mentioned

**Comment by tmcconechy** [comment]
Merging as this was previously approved

**Pull request merged**
