### PR TITLE
298 - Ids Layout Grid updates

### LINKED ISSUE #298: IdsLayoutGrid - Add more settings and features
**Describe the Enhancement**

Add some more features to ids-layout-grid

**Tasks**

- [x] Add `minColWidth` property. For auto-responsive grids that use `auto-fit` and `minmax` there could be a setting to control where the reflow happens `<ids-layout-grid minColWidth="120px">`
- [x] Make `--grid-min-col-width` at https://github.com/infor-design/enterprise-wc/blob/main/src/ids-layout-grid/ids-layout-grid.scss#L17 a setting
- [x] Add the following columns and breakpoints:
   - XXL 1440px —  12 columns, 24px gutter, 24px margin 
   - XL 1280px — 12 columns,  24px gutter, 24px margin 
   - L 1024px — 12 columns,  16px gutter, 16px margin
   - M 840px — 8 columns, 16px gutter, 16px margin 
   - S 600px — 4 columns, 16px gutter, 16px margin
   - XS 360px — 4 columns, 16px gutter, 16px margin
- [x] Optional 16 column grid XL & above
- [x] Update Readme with new settings

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds additional features to the ids-layout-grid.

- Adds a `min-col-width` setting to auto and custom col grids so you can control the size at which the grid responds to screen size.
- Converts the default grid to a bootstrap style fluid grid with 12 cols (based on this [documentation](https://inforonline-my.sharepoint.com/:w:/g/personal/kevin_white_infor_com/EVtrJ3AzZwZBhaVZegtzqDsBra4MclxnzpZ6h1MvyzYi4Q?e=hJpMrh&isSPOFile=1))
- Adds an optional setting `fluid-grid-xl` to make the grid 16 columns at lg and xl breakpoints.

**Related github/jira issue (required)**:
closes #298 

**Steps necessary to review your pull request (required)**:
- Pull and run branch
- Go to http://localhost:4300/ids-layout-grid and make sure the examples work as expected.
- Make sure all tests pass

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
~- [ ] A note to the change log.~

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
Looks good, just a couple of notes to check/discuss:
- in ids-layout-grid need to add `minColWidth` ts types file ids-layout-grid.d.js
- to move `justify` property to grid cell ts file
- for grid cell need to add all new attributes to ts file ids-layout-grid-cell.d.ts `colSpanXxl colSpanXl colSpanLg colSpanMd colSpanSm colSpanXs`
- should we xss satitize all inputs?
- mix of `max-width` and `min-width` media queries in `ids-layout-grid.scss` at the same `$breakpoint-md` breakpoint, I haven't found any issues at 840px screen width, but need to double check, confirm
- I think need to add some `min-col-width` example and some info to README regarding it should be set in pixels like `min-col-width="200px"` or 'minColWidth = '200px'`
- TODO check `src/components/ids-layout-grid/TODO.md`

**Comment by tmcconechy** [comment]
@andriivarhanov i thought you had a point with xss sanitizing but i tested and the browser is doing this. I tested on these strings https://main-enterprise.demo.design.infor.com/components/datagrid/test-xss-prevention.html in several attributes attached to components. So seems like it would be unneeded / slower to do that when the browser does already.

**Comment by jmacaluso711** [comment]
@andriivarhanov regarding the mix of min/max width media queries. There's basically 2 separate ways to define the grid, either auto or fluid (12 column). Auto uses maxwidth and fluid uses min.. There should not be any conflicts between the 2 types.

**Comment by andriivarhanov** [comment]
@tmcconechy 
> i thought you had a point with xss sanitizing but i tested and the browser is doing this. I tested on these strings https://main-enterprise.demo.design.infor.com/components/datagrid/test-xss-prevention.html in several attributes attached to components. So seems like it would be unneeded / slower to do that when the browser does already.

indeed, we don't have to sanitize attributes, I've removed some xss sanitize from ids about component https://github.com/infor-design/enterprise-wc/pull/327/commits/87b7b699bb9b8354103f1429e2ed51bc132af8ed

**Comment by andriivarhanov** [comment]
> regarding the mix of min/max width media queries. There's basically 2 separate ways to define the grid, either auto or fluid (12 column). Auto uses maxwidth and fluid uses min.. There should not be any conflicts between the 2 types.

@jmacaluso711 I can confirm, there is no conflicts, thanks

**Review by andriivarhanov — APPROVED** [review]

**Comment by tmcconechy** [comment]
@jmacaluso711 - can you try and pull main on. As i fixed the percy checks. So it should be possible to tell what really broke if you build again. I am seeing that there is some layouts still broken in a few examples tho.

**Comment by jmacaluso711** [comment]
@andriivarhanov I see.. just reverted that changed

**Comment by andriivarhanov** [comment]
@jmacaluso711 there is incorrect link `link: ids-list-view` in `index.yaml` but it fixed in https://github.com/infor-design/enterprise-wc/pull/341 , not sure if you need to fix it in your branch

**Comment by tmcconechy** [comment]
Cant hurt to fix it on both PRs @andriivarhanov it will just merge together. but i saw that as well 👍🏻

**Comment by tmcconechy** [comment]
@jmacaluso711 the only image im wondering about is https://percy.io/00aaa841/enterprise-wc/builds/12744381/changed/720100127?browser=chrome&browser_ids=16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280

Is that because of the message/modal bug? @EdwardCoyle or is it because of the grid fixes here?

**Comment by jmacaluso711** [comment]
@tmcconechy @EdwardCoyle I saw that.. looks like percy is taking the snapshot during a window resize or something? The grid isn't being used in that example so was thinking it's not the cause.

**Comment by EdwardCoyle** [comment]
That screenshot may be related to the issue in Popup/Modal.  I'd say ignore and approve that one for now because we'll get it resolved with an upcoming PR for #295.

**Review by tmcconechy — APPROVED** [review]

**Review by andriivarhanov — APPROVED** [review]

**Pull request merged**
