### PR TITLE
2256 - IdsLoadingIndicator set to contained area

### LINKED ISSUE #2256: IdsLoadingIndicator: Overlay and align properties should work over a set area
**Related Issue:**
https://github.com/infor-design/enterprise-wc/pull/1694
**Team: ION Notification Center**
**Current version: "ids-enterprise-wc": "^1.0.0",**

**HTML Tag:**

```
<ids-loading-indicator align="center" overlay></ids-loading-indicator>
```

**Use Case:**

- When sorting is applied to the list view based on the selected criteria, the UI should display a loading indicator while retrieving the API data. This will prevent the user from performing other actions in the list until the data is loaded. At this point, an overlay and alignment should be applied to block the view and show it center.
-When bulk removal of list items is initiated by clicking the button, a loading indicator should appear and the list view should be blocked to prevent other actions from being performed

**Issue:**
Currently, If I use overlay and align center for list view it applies to the whole page Like below
image

**Requirement:**
- [ ] For the ids-loading-indicator, the overlay and align properties should function in the list view.
- [ ] Include a list view example with a loading indicator in Angular, incorporating the overlay and align properties. If feasible, provide examples for the scenarios described above.

**Expected**

If the overlay and align properties of the ids-loading-indicator are applied to the list view instead of the entire page, they should only affect elements within the list view. For example, they should function as follows (overlay and align should work):

**Note: For demonstration purposes, I've added some styles to center it.**

image

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR introduces a new setting, `contained`, to the IdsLoadingIndicator component. The contained setting enables the loading indicator to be confined within its parent element, preventing it from overflowing or extending beyond the intended boundaries.

**Related github/jira issue (required)**:

closes #2256 

**Steps necessary to review your pull request (required)**:

- pull and run branch
- go to http://localhost:4300/ids-loading-indicator/list-view-loading.html
- See example of contained loading indicator.

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by glenlieorillo — APPROVED** [review]
Working now as expected in RTL.

image

**Review by n-ace-ancog — APPROVED** [review]
Now working on my end.

image

**Comment by n-ace-ancog** [comment]
Seems like the build check was cancelled in the middle of running the tests @jmacaluso711

**Review by jbrcna — APPROVED** [review]
image
image

**Pull request merged**
