### PR TITLE
844 - Update dependencies

### LINKED ISSUE #844: General: Update Dependencies
**Describe the bug**

Quick Semi regular update to dependencies..
- [x] Update all dependencies to latest
- [x] Update node LTS in .nvmrc
- [x] In order to update puppeteer changing the package out https://github.com/dequelabs/axe-core-npm/tree/develop/packages/puppeteer which involves a few test updates

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR:

- [x] Updates all dependencies to the latest
- [x] Changes from @wordpress/jest-puppeteer-axe to @axe-core/puppeteer as we were using the "wrong" dependency for Axe tests that was not the one from the core team and was not updated
- [x] Adjusted tests accordingly
- [x] Minor bump in LTS

**Related github/jira issue (required)**:
Closes #844

**Steps necessary to review your pull request (required)**:
- all checks pass on this PR (tests lint ect)
- should also merge with https://github.com/infor-design/enterprise-wc/pull/823 when done (may or may not be needed)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.

### CODE REVIEW

**Comment by tmcconechy** [comment]
cc @corpulent - FYI

**Comment by tmcconechy** [comment]
Ready @danielortiz1982 if you want to test on ubuntu and windows

**Review by danielortiz1982 — APPROVED** [review]
@tmcconechy This looks great! Just one thing minor... On the next deps update let's isolate just the dependencies updates/upgrades. 

Thanks!

**Comment by tmcconechy** [comment]
@danielortiz1982 i didn't add anything here except for the dependencies and the changes needed to make them work (update the tests)

**Review by andriivarhanov — APPROVED** [review]
looks good

**Pull request merged**
