### PR TITLE
Zephyr Scale - Playwright Synchronization - DEMO ONLY - Gathering Feedback

### PR DESCRIPTION
**Pull request by n-ace-ancog**
### **NOTE: DON'T MERGE - DEMO ONLY** 

**Explain the details for making this change. What existing problem does the pull request solve?**
- Added automatic test results upload in Zephyr Scale
- Test case mapping to Zephyr Scale test cases is done via [Playwright annotations](https://playwright.dev/docs/test-annotations#annotate-tests) with having `type: zsID` and `description: '{Zephyr test ID here}'`
```ts
test('should be be possible to copy to clipboard ', { annotation: { type: 'zsID', description: 'IDS-T1' } }, async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);

  await page.locator('#about-example-trigger').click();
  await page.locator('#copy-to-clipboard').click();

  // Get clipboard content after the link/button has been clicked
  const handle = await page.evaluateHandle(() => navigator.clipboard.readText());
  const clipboardContent = await handle.jsonValue();

  // Check that the clipboard contains correct UUID
  expect(clipboardContent).toContain('IDS version');
  expect(clipboardContent).toContain('Controls Example Application Version No. XX');
  expect(clipboardContent).toContain('Platform');
});
```
- Added custom reporter for results gathering and uploading defined in `playwright.config.ts`
  - Generate Zephyr Scale api key [here](https://support.smartbear.com/zephyr-scale-cloud/docs/en/rest-api/generating-api-access-tokens.html)
```ts
reporter: [
  ['html'],
  ['./tests/zephyr/reporter.ts',
    {
      // Zephyr Scale api token
      apiKey: '${Zephyr Scale API key}',
      // Jira project ID
      projectId: 'IDS',
      // Build ID
      buildId: '32452',
      // Branch ID
      branchId: 'Development',
      // Base Zephyr Scale api url
      baseUrl: 'https://api.zephyrscale.smartbear.com/v2',
      // Test cycle folder Id
      testCycleFolderId: '15108775',
      codeBase: 'Web Component',
      codeVersion: '1.3'
    }
  ]
]
```

**Steps necessary to review your pull request (required)**:
1. Pull the branch
2. Generate Zephyr Scale api key and put inside the `playwright.config.ts` file under reporter -> apiKey
3. Run `IdsAbout localization tests` for the about tests component
4. No error/s encountered
5. Check if results is uploaded at [here](https://inforwiki.atlassian.net/projects/IDS?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCycles?projectId=12379)

image

### CODE REVIEW

**Comment by tmcconechy** [comment]
@n-ace-ancog I probably need a demo to understand this, maybe in our next team call?

**Comment by tmcconechy** [comment]
@n-ace-ancog  also can you sync main and put this in a new 1.4.0 change log so it will reflect in the right version when your done with this? Thanks

**Comment by n-ace-ancog** [comment]
> @n-ace-ancog also can you sync main and put this in a new 1.4.0 change log so it will reflect in the right version when your done with this? Thanks

Probably will work on this again if we already setup the test cases in Zephyr Scale.

**Comment by tmcconechy** [comment]
@n-ace-ancog ok should we close for now and reopen later

**Pull request closed without merging**
