### PR TITLE
223 - Fix trigger field layouts

### LINKED ISSUE #223: IdsTriggerField: Allow button on the second side
**Describe the bug**
Add the ability to put a button optionally on either side and style it. This should go in the light dom so you can style it.

This will be used in spinbox and colorpicker to replace what is there now (and maybe others).

Also fix arrow position

**To Reproduce**
1. Go to http://localhost:4300/ids-color-picker

It has 3 issues ... 
1. The label needs a hack to position
1. Focus the field and it doesnt go all around
1. arrow position is off

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds the ability to create a trigger field with buttons on each side of the input. The `ids-color-picker` and `ids-upload` components have been updated to utilize the new trigger-field. Details for the new settings and markup are outlined in the trigger field readme.

**For use with 2 trigger buttons the new markup is as follows:**

```
<ids-trigger-field
    id="trigger-field-1"
    label="Trigger field label"
    tabbable="false"
    content-borders
>
  <ids-trigger-button class="color-preview">
    <ids-icon class="ids-dropdown" icon="dropdown" size="medium"></ids-icon>
    <ids-text audible="true">Call to action</ids-text>
  </ids-trigger-button>
  <ids-input placeholder="Enter Product"></ids-input>
  <ids-trigger-button>
    <ids-text audible="true">color picker trigger</ids-text>
    <ids-icon class="ids-dropdown" icon="dropdown" size="medium"></ids-icon>
  </ids-trigger-button>
</ids-trigger-field>
```

**New attributes added to trigger field include:**
- `content-borders` {boolean} This adds the 'input' border and focus state to the ids-trigger-field-content and removes it from `ids-input`s inside the trigger field.
- `disabled` {boolean} set disabled state.
- `label` {string} This adds a label to the trigger field
- `size` {string} set the input size, it will set md as defaults

**Other bugs addressed**
- The label needs a hack to position
- Focus the field and it doesn't go all around
- arrow position is off

**Related github/jira issue (required)**:
closes #223 

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Comment by deep7102** [comment]
Looks good! few found as:
http://localhost:4300/ids-trigger-field/test-sizes.html
Getting javascript error soon blur/focus-out on example `Small`  in TRIGGER FIELD - SIZES (WIDTH)

http://localhost:4300/ids-upload
1) Last in examples list `Required` looks validation not working
1) Clear icon looks off aligned

**Review by deep7102 — CHANGES_REQUESTED** [review]
.

**Comment by jmacaluso711** [comment]
@deep7102 Thanks.. I addressed those issues you found

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
