### PR TITLE
Added extensibility feature to override IDS calendar event

### LINKED ISSUE #911: IdsMonthView: Add ability to extend and use customized calendar events
**Is your feature request related to a problem or use case? Please describe.**
The IdsMonthView is hard coded to utilize a IdsCalendarEvent Web Component to display each event on the calendar. This isn't very flexible and doesn't allow such customizations as multi-line events, custom colors and other pill options.

**Describe the solution you'd like**
Ideally, we could provide our own Web Component that inherits from the IdsCalendarEvent and overrides the Template or any other methods required. This would allow multi-line text, different icon placement, as well as any other scenario's in the future. 

image

With a quick look at ids-month-view.ts, a couple issues will arise:

- MAX_EVENT_COUNT is hard-coded to 3. If multi-line event pills are allowed, the isOverflowing logic will need to be changed. Possibly add lineCount to idsCalendarEvent defaulted to 1. Override in subclass.
- Multi-Day Events
- Currently hard-coded to IdsCalendarEvent. Needs to be extendable.

**Describe alternatives you've considered**
We could try manually modifying the calendar after rendering. However this is not a sustainable approach as with each update we have a higher chance of breaking something in our application. Providing a extendable framework would allow the IDS library to control most of the code, while allowing unique UI use cases on a per-application basis. 

**Additional context**
**!!Only worrying about the event pill in this ticket!!**
image
image
image

And what application do you work on? Infor WFM

### PR DESCRIPTION
**Pull request by manoj-kothuri**
**Explain the details for making this change. What existing problem does the pull request solve?**
### **IDS Calendar Event Customization**
Providing an entry point to customize the default IDS Calendar Component by extending the IdsCalendarEvent class.

**Related github/jira issue (required)**:
"Fixes #911"

**Steps necessary to review your pull request (required)**:
1. Checkout branch, `npm run start`
2. Go to http://localhost:4300/ids-calendar/example-custom.html
3. Added new example specific for IdsCalendarEvent overriding (ids-custom-calendar-event.ts) under IDS Calendar Demos.
4. The following is the screenshot for the above mentioned calendar event overriding.
Custom Calendar
5. test scenarios -> Added new test file for covering the Calendar event overriding(ids-custom-calendar-event-func-test.ts)
ids-custom-calendar-event-func-test

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
thanks for the contribution @manoj-kothuri overall this looks good. some minor things 

- you can add a change log just add it here https://github.com/infor-design/enterprise-wc/blob/main/doc/CHANGELOG.md#100-beta3-fixes
- looks like you altered the package-lock.json - this usually happens if you are on a different version of node. to fix this just copy the one in the repo over it so the file is uneffected.
- is the setting `is-custom` really needed? i.e. wouldn't there being a custom event in the slot be enough

Also seems like some fixes

**Comment by manoj-kothuri** [comment]
> thanks for the contribution @manoj-kothuri overall this looks good. some minor things
> 
> * you can add a change log just add it here https://github.com/infor-design/enterprise-wc/blob/main/doc/CHANGELOG.md#100-beta3-fixes
> * looks like you altered the package-lock.json - this usually happens if you are on a different version of node. to fix this just copy the one in the repo over it so the file is uneffected.
> * is the setting `is-custom` really needed? i.e. wouldn't there being a custom event in the slot be enough
> 
> Also seems like some fixes

Hi @tmcconechy,
- As suggested I added change log in the specified location.
- I checked the package-lock.json differences and found that only new line at the end of the file is missing apart from that everything is same. So I added a new line at end of the file and committed.
- Removed is-custom attribute from the html.

**Review by andriivarhanov — COMMENTED** [review]
got some errors in the console, could you please check

image

**Comment by manoj-kothuri** [comment]
> got some errors in the console, could you please check
> 
> image

I have fixed the above mentioned issue, could you please check.

**Comment by jdilag90** [comment]
looks good, a couple things

The event details pane (right side accordion pane) isn't populating with events when selecting days on the calendar's month view.
(https://main.wc.design.infor.com/ids-calendar/example.html) Clicking on day cells should populate the event details accordion with events within that day.

Can we update the example with calendar events that look different from default, possibly a real life use case for a custom event?
It could help us see any adjustments we would need to make the calendar related components more extensible/flexible on our end

**Comment by manoj-kothuri** [comment]
> looks good, a couple things
> 
> The event details pane (right side accordion pane) isn't populating with events when selecting days on the calendar's month view. (https://main.wc.design.infor.com/ids-calendar/example.html) Clicking on day cells should populate the event details accordion with events within that day.
> 
> Can we update the example with calendar events that look different from default, possibly a real life use case for a custom event? It could help us see any adjustments we would need to make the calendar related components more extensible/flexible on our end

Hi @jdilag90,

- I have fixed the issue of displaying event details in the right pane for custom calendar event example.
- As suggested I have updated the custom calendar event pill display with multiline.

**Review by andriivarhanov — COMMENTED** [review]
I can confirm the errors were fixed, let's see how the build goes and I'm ready to approve

**Review by jdilag90 — APPROVED** [review]

**Review by EdwardCoyle — COMMENTED** [review]
I reviewed the most recent changeset and it appears the errors/items previously called out have been addressed.  This looks really great @manoj-kothuri!  Just two minor things:

- Please add a changelog entry in this file under the same heading, calling out the original issue #911 (https://github.com/infor-design/enterprise-wc/blob/main/doc/CHANGELOG.md#100-beta3-fixes)
- This one is for our team to discuss:  I'm not sure we've created any examples yet that contain custom components.  Do we want to establish a place that these components should live other than their corresponding demo folder?  Do we need a naming convention?   As it stands I think we should approve, but maybe we come up with some guidelines for this going forward.

**Comment by tmcconechy** [comment]
@EdwardCoyle i think the location is ok. I've been using the name `custom` for some things in data grid examples. So this doesnt feel out of place to me. If it was more "exotic" than just another example like a framework we do have this place as well https://github.com/infor-design/enterprise-wc-examples

**Comment by tmcconechy** [comment]
Just need a change log entry please/thanks. @manoj-kothuri

**Comment by manoj-kothuri** [comment]
> Just need a change log entry please/thanks and one more merge with main @manoj-kothuri a

As suggested added a entry to the change log.

**Review by tmcconechy — APPROVED** [review]

**Review by andriivarhanov — APPROVED** [review]

**Pull request merged**
