### PR TITLE
2682/2770 - Allow dropdown to work on legacy modal

### LINKED ISSUE #2682: IdsDropdown: Does not render correctly inside a scroll container
**Describe the bug**
`<ids-dropdown>` content is not displayed correctly when inside an Enterprise modal (e.g `SohoModalDialogService`). The dropdown list expands the modal content rather than being displayed on top of it, like `<ids-modal>` and similar.

**UPDATE:** This may not be related to the modal at all. The issue can be reproduced when the dropdown is inside any scroll container. See https://github.com/infor-design/enterprise-wc/issues/2682#issuecomment-2272680008

**To Reproduce**

1. Clone https://github.com/anhallbe/enterprise-wc-examples
2. Install & start dev server
3. Go to http://localhost:4200/ids-dropdown/modal
4. Open Modal
5. Open the dropdown
6. Notice that the modal content expands and you have to scroll to see the dropdown list.

**Expected behavior**
The dropdown content should be displayed outside of the modal content area, similar to https://main.wc.design.infor.com/ids-dropdown/in-modal.html

**Version**

- ids-enterprise-wc: 1.4
- ids-enterprise-ng: 18.x

**Screenshots**
image

https://private-user-images.githubusercontent.com/4991954/355401176-7a2f7ffd-077f-4358-a7c0-666f51fa80da.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTM5MTcsIm5iZiI6MTcyMjk1MzYxNywicGF0aCI6Ii80OTkxOTU0LzM1NTQwMTE3Ni03YTJmN2ZmZC0wNzdmLTQzNTgtYTdjMC02NjZmNTFmYTgwZGEubW92P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMTQxMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjkwZTc2ODEyNzcyMzVmNmI5YzNhMWFlZmNmNTMyZTU3NmFkNTM2Yjc3M2U5NDk1OTlmODE5NDI0NjhiOTRhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B3FDQAErnPxuXPD6rRe7BEUMF-22mTDgZclk695eBs8

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Related: https://github.com/infor-design/enterprise-wc/issues/2473

### LINKED ISSUE #2770: IdsDropdown: Typeahead should be enabled by default
**Is your feature request related to a problem or use case? Please describe.**
- When using a HTML `<select>` element, you can type to "search" and select an item
- When using `soho-dropdown`, the dropdown is searchable by default
- When using an `<ids-dropdown>`, you have to explicitly enable searching by adding the `typeahead` attribute.

**Describe the solution you'd like**
It should still be possible to disable searching through `typeahead="false"` or similar. But typeahead should be enabled by default.

Alternatively, the dropdown list should *always* listen for keys to select values, even if the searched text is not visible and items are not filtered (like `<select>` works, at least in Safari).

**Describe alternatives you've considered**
We could add the `typeahead` attribute to all of the `<ids-dropdown>` in our app. But:

1. It is easy to forget, which makes the fields inconsistent within the app.
2. The dropdown will not be consistent across apps, since some may choose to add `typeahead` while others won't. Or they'll forget, too.

**Additional context**
And what application do you work on? Portal

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Moved the offset-container code from ids-popup-menu into ids-popup so it can be used on legacy modals so that the dropdown shows in the right position.

Also made typeahead default

**Related github/jira issue (required)**:
Fixes #2682
Fixes #2770 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-dropdown/side-by-side.html
- NOTE: First time will need to wait for the legacy scripts to cache may be slow
- click the modal button
- open the dropdown and it should be positioned in the correct spot
- re test http://localhost:4300/ids-popup-menu/in-offset-container.html
- go to http://localhost:4300/ids-dropdown/example.html
- tab into the first dropdown and type `a` and it should do typeahead by default now

**Included in this Pull Request**:
- [x] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Working on my side, but noticed that the style for the read only dropdown is not correct.

image

**Comment by tmcconechy** [comment]
@n-ace-ancog good catch there. Fixed!

**Review by glenlieorillo — APPROVED** [review]
Readonly dropdown has now been fixed.

image

image

image

**Review by n-ace-ancog — APPROVED** [review]
Working on my side now. 

image

**Review by ericangeles — APPROVED** [review]

**Pull request merged**
