### PR TITLE
1319 - datagrid context-menu enables cell edit-mode on right-click

### LINKED ISSUE #1319: IdsDatagrid: An option to activate edit mode on an editable cell when right clicked
**Is your feature request related to a problem or use case? Please describe.**
When an editable cell is clicked, it goes to edit mode. But when right clicked, it stays a span. We would like to request a configuration to allow the editable cell to be editable when right clicked.

**Describe the solution you'd like**
When a editable cell is right clicked, set the cell to be editable before triggering the beforemenushow.

**Describe alternatives you've considered**

**Additional context**
Currently, right clicking an editable cell does not change it to editable.
image

And what application do you work on? M3 H5A

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Added an example that shows context-menu with an option to activate cell edit-mode on right-click.

**Related github/jira issue (required)**:

Closes #1319  

**Steps necessary to review your pull request (required)**:

1. Check out branch and run: `nvm use && npm run start`
2. Go to: http://localhost:4300/ids-data-grid/editable-contextmenu-before-show.html
3. Right-click on cells and click `edit, copy, cut, paste` on popup context-menu to ensure they work.
4. Right-click on editable cells and ensure `edit` doesn't appear in popup context-menu.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
The only issue i see that could be an issue @clayinfor is if you...

- click in a cell to edit
- right click and copy
- try to paste -> the cell looses edit mode and focus so cant paste..

Not sure if important but noted. 

Also can you add change log to section 15 now to fix the conflict? Need to establish a fixes section...

**Comment by clayinfor** [comment]
hey @tmcconechy , thanks for the feedback!  I think for now I won't fix this because so far everything I've done has caused other bugs.  The `paste` is still possible even if the cell is no longer in edit-mode, so I think we should ship this, and address the issue you mentioned in another PR.

**Comment by clayinfor** [comment]
Test is now fixed @tmcconechy!  That was a [good test](https://github.com/infor-design/enterprise-wc/actions/runs/5881982987/job/15951545717) @jdilag90 🤓

**Review by tmcconechy — DISMISSED** [review]

**Comment by jdilag90** [comment]
found a weird bug 

1) left click `Pub Date` cell for row 102 (date is 2/23/2021)
2) left click `Pub Date` cell for row 105 (date is 12/12/2021)
3) left click `Pub Date` cell for row 102 (data is changed from 2/23/2021 -> 12/12/2021)

**Comment by clayinfor** [comment]
Good catch @jdilag90 , it's fixed @tmcconechy.

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
