### PR TITLE
2517 - IdsModuleNav Dynamic nav items

### LINKED ISSUE #2517: IdsModuleNav: Rendering problems for dynamic content
**Describe the bug**
There are a couple of issues with the IdsModuleNav related to dynamic content:

1. If the panel is initially expanded, and menu items are added later, then they do not render at all.
2. If the panel is expanded after the "dynamic" menu items have been added, they are visible but the selection state does not work. Also the accordion chevrons are not visible.

This is currently stopping us from using the ModuleNav, as the menu items are either dynamically loaded at runtime (based on a HTTP request), or dynamically rendered using Angular conditional syntax (`@if`, `*ngIf` `@for` etc). Both of these cause the issue.

**Update: Similar issues with IdsAppMenu.** See https://github.com/infor-design/enterprise-wc/issues/2517#issuecomment-2208710352

**To Reproduce**

1. Clone the repository: https://github.com/anhallbe/repro-ids-module-nav
2. Run `npm install`
4. Run `ng serve` and open in the browser, or start the VSCode debugger.
5. See rendering issues in module nav

**Expected behavior**
It should be possible to add menu items after the Module Nav has been created.

**Version**

- ids-enterprise-wc: 1.2.0

**Screenshots**

https://github.com/infor-design/enterprise-wc/assets/4991954/b2325b20-a58e-47ac-84e2-f0fb82cb30bb

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Code to reproduce:

## app.component.html:
```html
<ids-container role="main">
  <ids-module-nav #moduleNav responsive>
    <ids-module-nav-bar>
      <ids-accordion>
        <ids-accordion-section slot="" grow>
          @for (action of actions; track action) {
          <ids-accordion-panel>
            <ids-module-nav-item slot="header" [icon]="action.icon">
              <ids-text font-size="16" overflow="ellipsis">{{ action.text }}</ids-text>
            </ids-module-nav-item>
            @for (child of action.children; track child) {
            <ids-accordion-panel slot="content">
              <ids-module-nav-item slot="header">
                <ids-text font-size="14">{{ child }}</ids-text>
              </ids-module-nav-item>
            </ids-accordion-panel>
            }
          </ids-accordion-panel>
          }
        </ids-accordion-section>
      </ids-accordion>
    </ids-module-nav-bar>

    <ids-module-nav-content>
      <ids-header>
        <ids-toolbar>
          <ids-toolbar-section type="button">
            <ids-button icon="menu" (click)="toggleMenu()">
            </ids-button>
          </ids-toolbar-section>
          <ids-toolbar-section type="title">
            <ids-text font-size="20" type="h1">
              Page Title
            </ids-text>
          </ids-toolbar-section>
        </ids-toolbar>
      </ids-header>

      <ids-text>
        When actions (ids-accordion-panel) are added after the Module Nav has already been created, the menu titles are
        not visible at all. When the menu is collapsed and then expanded again, the menu titles are visible but do not
        render properly. They get a different text color and the selection state and accordion chevron do not work.
      </ids-text>

    </ids-module-nav-content>
  </ids-module-nav>
</ids-container>
```

## app.component.ts:
```ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, ElementRef, viewChild } from '@angular/core';
import type IdsModuleNav from 'ids-enterprise-wc/components/ids-module-nav/ids-module-nav';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppComponent {
  moduleNav = viewChild<ElementRef<IdsModuleNav>>('moduleNav');

  actions: Action[] = INITIAL_ACTIONS;

  ngAfterViewInit() {
    this.moduleNav()!.nativeElement.displayMode = "expanded";

    setTimeout(() => {
      this.actions = [...this.actions, ...DELAYED_ACTIONS];
    }, 1000)
  }

  toggleMenu() {
    const moduleNav = this.moduleNav()!.nativeElement;
    const displayMode = moduleNav.displayMode;
    moduleNav.displayMode = displayMode === "expanded" ? "collapsed" : "expanded";
  }
}

const INITIAL_ACTIONS: Action[] = [
  {
    text: "Home",
    icon: "home",
  },
  {
    text: "Warehouse",
    icon: "warehouse",
    children: [
      "Warehouse 1",
      "Warehouse 2",
      "Warehouse 3",
    ],
  },
  {
    text: "Shirts",
    icon: "shirt",
    children: [
      "Shirt 1",
      "Shirt 2",
      "Shirt 3",
    ],
  },
  {
    text: "Trucks",
    icon: "truck",
    children: [
      "Truck 1",
      "Truck 2",
      "Truck 3",
    ],
  }
];

const DELAYED_ACTIONS: Action[] = [
  {
    text: "Delayed",
    icon: "clock",
    children: [
      "Delayed 1",
      "Delayed 2",
      "Delayed 3",
    ],
  },
];

type Action = {
  text: string;
  icon: string;
  children?: string[];
}
```

### LINKED ISSUE #2543: IdsTabs: More button issue - BETA 1.3
**Describe the bug**
More button is not properly placed when the app menu is expanded.

**To Reproduce**

1. Go to https://main.wc.design.infor.com/ids-tabs/app-example.html
1. Click on menu button to expand the app menu
1. Click on more button
1. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by andrivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fixed the issue where `display-mode="expanded"` was not being added for newly added navigation items, so they were in a collapsed state where only the icon was visible. Added mutation observer to module nav bar to detect changes and re-apply current display mode for added nav items

**Related github/jira issue (required)**:
Closes #2517 
Fixes #2543

**Steps necessary to review your pull request (required)**:
- pull the branch in Angular examples https://github.com/infor-design/enterprise-wc-examples/pull/82
- pull this branch
- `npm run publish:link`
- go to Angular examples and run `npm link ids-enterprise-wc`
- run Angular examples
- go to http://localhost:4200/ids-app-menu/dynamic-content
- see the Delayed menu item is visible and selectable
- go to http://localhost:4200/ids-module-nav/dynamic-content
- see the Delayed menu item is visible and selectable

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by n-ace-ancog — APPROVED** [review]
Working on my end.

https://github.com/user-attachments/assets/eb2c5865-09df-43dd-8864-b0d5d9399a3f

**Review by jbrcna — CHANGES_REQUESTED** [review]
image

However, in safari the theme switcher button and pop up is off
image

Also, is the extra line intended?
image

**Review by tmcconechy — APPROVED** [review]
Looks good to me @andrivarhanov but waiting to see if you fix the minor comments from @jbrcna

**Review by tmcconechy — DISMISSED** [review]

**Comment by andrivarhanov** [comment]
@jbrcna @tmcconechy the issue with separator is fixed, the issue with theme switcher popup menu can be reproduced everywhere https://main.wc.design.infor.com/ids-app-menu/example.html , not sure how long it was there, might take some time to fix

**Comment by tmcconechy** [comment]
@andrivarhanov maybe just fix the smaller css issues related to the Module nav (extra line).

The more button issue does have a separate issue already https://github.com/infor-design/enterprise-wc/issues/2543 for next sprint. And @jdilag90 has a similar fix on another issue we may be able to use. 

https://github.com/infor-design/enterprise-wc/pull/2624

But anyway it is a separate issue. So feel free to wait if hard. Thanks!

**Comment by andrivarhanov** [comment]
@tmcconechy found it, the code that caused the issue was added here https://github.com/infor-design/enterprise-wc/pull/2276#pullrequestreview-2066399316 with this example http://localhost:4300/ids-toolbar/in-header.html .
I've checked the example and regular app menu examples, safari, firefox, everything looks fine

https://github.com/infor-design/enterprise-wc/issues/2543 should be fixed as well

**Review by jbrcna — APPROVED** [review]
great work @andrivarhanov ! 🍌. thanks
image
image

**Pull request merged**
