### PR TITLE
1941 - Convert Hyperlink test to Playwright

### PR DESCRIPTION
**Pull request by glenlieorillo**
**Explain the details for making this change. What existing problem does the pull request solve?**

Converted Hyperlink test to Playwright

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-wc/issues/1941

**Steps necessary to review your pull request (required)**:

1. Pull this branch, build, and run the app
2. Run the test suite
3. Check the code conversion
4. New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [x] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]

**Review by andrivarhanov — APPROVED** [review]

**Comment by ericangeles** [comment]
@n-ace-ancog, yeah looks like it's missing.

**Comment by ericangeles** [comment]
I don't see any commits.

**Comment by tmcconechy** [comment]
@glenlieorillo @ericangeles @n-ace-ancog 

it looked like it was ready to merge. So i did by mistake. But I reopened the issue. Just do a new PR with testing contents. I guess wrong branch was merged? Or Empty?

Just start again :)

**Comment by n-ace-ancog** [comment]
@ericangeles @tmcconechy I checked the files and the changes were there. Even the change log was updated. In terms of test conversion for this component, I think we're good. Let me know otherwise.

**Pull request merged**
