### PR TITLE
252- change the default button text color to slate-60

### LINKED ISSUE #252: IdsButton: Change to slate60
**Describe the bug**

Should make changes to the icon button and text only button and check the card button color as per https://github.com/infor-design/enterprise/pull/5413#pullrequestreview-705197287

In light/new theme the icon buttons should be slate60

**To Reproduce**
1. Go to http://localhost:4300/ids-button
2.  Check icon and text button color

**Expected behavior**
Change to slate like the EP PR

**Additional context**
https://github.com/infor-design/enterprise/pull/5413#pullrequestreview-705197287

### PR DESCRIPTION
**Pull request by vivz753**
**Explain the details for making this change. What existing problem does the pull request solve?**
- Changed the default button text color to slate-60 in `ids-button-base.scss`

**Related github/jira issue (required)**:

- Closes #252

**Steps necessary to review your pull request (required)**:
- `npm run start` and go to http://localhost:4300/ids-button
- NOTE: Tertiary and Default button are the same--font color has now been changed to #606066 (slate-60)

Screen Shot 2021-07-15 at 9 57 29 AM

- NOTE TO SELF: 
- color palette documentation: https://main-enterprise.demo.design.infor.com/components/colors/example-index.html
- design tokens (check here for variables used in the `enterprise-wc` repo--this was handy bc I didn't know what `--ids-color-font-base` referred to in `ids-button-base.scss`)
https://github.com/infor-design/design-system/blob/main/design-tokens/theme-new/theme.json
- in the `enterprise-wc` repo, can check `node_modules/ids-identity/dist/theme-new/tokens/web/theme-new-mixins.scss` which has shorthand for CSS (similar to TailwindCSS)--prefer to use `@include text-slate-60();` over `color: var(--ids-color-palette-slate-60)`

### CODE REVIEW

**Comment by vivz753** [comment]
Screen Shot 2021-07-15 at 10 15 30 AM

Test is failing due to contrast levels. What's the solution to this?

**Comment by tmcconechy** [comment]
It shouldnt because it is passing here https://main-enterprise.demo.design.infor.com/components/button/example-index.html (use axe-tools).

But you can ignore rules here https://github.com/infor-design/enterprise-wc/blob/main/test/ids-upload-advanced/ids-upload-advanced-e2e-test.js#L15

But this should be passing slate60 should pass on a white background

**Comment by tmcconechy** [comment]
@vivz753 I think the change impacted something on http://localhost:4300/ids-swipe-action so for that one we need to keep the text at slate10 so just need to add a new rule there.

(I looked again)

**Comment by vivz753** [comment]
Percy shows some visual changes.

Why did the size for `Extra Small` label change?

**Comment by tmcconechy** [comment]
@vivz753 this looks like a mix of some other changes. Lets see where it is after we get some of the other PR's merged

**Review by tmcconechy — APPROVED** [review]

**Review by EdwardCoyle — APPROVED** [review]

**Pull request merged**
