### PR TITLE
877 - Fix Action Panel lifecycle issues

### LINKED ISSUE #877: IdsActionPanel: Lifecycle Issues
**Describe the bug**
IdsActionPanel still has some direct references to shadow root elements that need to be guarded against in situations where the Shadow root doesn't exist

**To Reproduce**
1. Pull/Build/Link/Run the web components with the [Sveltekit examples project](https://github.com/infor-design/enterprise-wc-examples/tree/main/sveltekit-ids-wc)
2. Open http://localhost:3000/ids-action-panel
3. Click the link to navigate to the example.  The Sveltekit hydration process tries to load the example code and fails due to a reference to `shadowRoot` on the action panel without a guard.

**Expected behavior**
The component should load without an issue.

**Additional context**
Found during development of #792

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
While working on the Svelte examples, some additional guards were needed in IdsActionPanel and its child/slotted components to ensure it loads properly without hydration issues

**Related github/jira issue (required)**:
Closes #877
Related to #792

**Steps necessary to review your pull request (required)**:
All tests should pass on this branch.  When testing http://localhost:4300/ids-action-panel/example.html, no component behavior should have changed from `main`

To test against the Sveltekit examples:
- Pull/Build/Link/Run this branch against [this branch](https://github.com/infor-design/enterprise-wc-examples/compare/main...792-more-sveltekit-examples) of the Sveltekit IDS Web Component Examples
- Open http://localhost:3000/ids-action-panel
- Click the "Example" link (this kicks off hydration as opposed to full page load)
- Open the action panel in the example page.  Its contents should load the same as if a full page load occurred.

### CODE REVIEW

**Comment by tmcconechy** [comment]
@EdwardCoyle do the e2e tests look OK to you? Or Flaky?

**Comment by EdwardCoyle** [comment]
Hey I accidentally approved this, but the tests are flaky.  I think I need to adjust the IdsSeparator changes a bit further... please hold off on merging

**Comment by tmcconechy** [comment]
fyi @EdwardCoyle i have a ticket in with percy about some of the text being wierd on certain PR's (like about)n so waiting to here back on that

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — COMMENTED** [review]
FYI - It's already merged to main, so not specific to this PR.

looks all good, just typo, (HdsPopupElementRef)
https://github.com/infor-design/enterprise-wc/blob/1e09b3f6953a16dbbc1ca3b02b624a099165ee2c/src/components/ids-popup/ids-popup.ts#L614

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
