### PR TITLE
371 - Ids Week View Component

### LINKED ISSUE #371: WeekView: New Component
TBD

### PR DESCRIPTION
**Pull request by andriivarhanov**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds `ids-week-view` component that provides calendar view that displays weeks and days
with navigation and current time indicator. 

Some notes:
- I didn't add month/year text to the toolbar, it looks like it's part of the date picker component. Let me know if I should use something like `ids-trigger-field` to add it in the PR
- `All Day` text is uppercased in the component. I used `ids-text` with font size 12 what is uppercased and it looks like small text is uppercased in the new typography. Let me know if I should make it capitalized
- There is some issue with tabindex in toolbar buttons, only first button has focus, same with http://localhost:4300/ids-toolbar
- It's not 100% test coverage, not sure how to test render loop updateCallback what updates timeline position every 30 seconds. 30 seconds exceeds timeout for the test and we probably should not be doing such tests. Let me know if you have any ideas
- Scrollable week view component with sticky toolbar/header is shown in standalone css http://localhost:4300/ids-week-view/standalone-css.html

**Related github/jira issue (required)**:
Closes #371 

**Steps necessary to review your pull request (required)**:
- pull the branch and run the app
- go to main example http://localhost:4300/ids-week-view doesn't show today's day highlight and timeline in order to make Percy screenshots persistant
- go to current week example http://localhost:4300/ids-week-view/current-week.html what should show today's day highlight and timeline
- compare to the design
https://main-enterprise.demo.design.infor.com/components/week-view/example-index.html
- run tests `npm run test -- ids-week-view`
- run coverage `npm run test:coverage`
- check `coverage/components/ids-week-view/index.html` html file in browser
- check `components/ids-week-view/README.md`
- check standalone css http://localhost:4300/ids-week-view/standalone-css.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
~- [ ] A note to the change log.~

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
This looks really great! The only thing im requesting change for is to make the header / days of the week sticky like the old example (position: sticky) 

https://main-enterprise.demo.design.infor.com/components/week-view/example-index.html

And in response to your questions:

> 1. I didn't add month/year text to the toolbar, it looks like it's part of the date picker component. Let me know if I should use something like ids-trigger-field to add it in the PR

I think you can add this as it is going to be shared between here and month/dateview. Before we had a "calendar toolbar" component and i think that would work?

> 2. All Day text is uppercased in the component. I used ids-text with font size 12 what is uppercased and it looks like small text is uppercased in the new typography. Let me know if I should make it capitalized

I think upper case is fine as it does follow the new typography.

> There is some issue with tabindex in toolbar buttons, only first button has focus, same with http://localhost:4300/ids-toolbar

Ok, Can you make an issue with this with steps? im a bit unclear on the steps.

> It's not 100% test coverage, not sure how to test render loop updateCallback what updates timeline position every 30 seconds. 30 seconds exceeds timeout for the test and we probably should not be doing such tests. Let me know if you have any ideas

We lowered this requirement but also you can use an e2e / puppetteer test now to fill coverage. So i would do that for this. Maybe:
- make a setting for the 30s timeout and set to 1-5s
- in the e2e test you load the page and check the position of the line
- wait 1-5 seconds and check it again -> this should cover it now as well as func tests do

> Scrollable week view component with sticky toolbar/header is shown in standalone css http://localhost:4300/ids-week-view/standalone-css.html

Woops missed this in the comment above. Can we not make all examples sticky tho?

**Comment by andriivarhanov** [comment]
@tmcconechy thanks for the feedback, everything makes sense, just one thing regarding
> Can we not make all examples sticky tho?

should I make the component sticky as well or should I make standalone example not sticky?

**Comment by tmcconechy** [comment]
@andriivarhanov i think the component should be always sticky (not just the one example). It was like this before

**Comment by andriivarhanov** [comment]
@tmcconechy 
> There is some issue with tabindex in toolbar buttons, only first button has focus, same with http://localhost:4300/ids-toolbar

> Ok, Can you make an issue with this with steps? im a bit unclear on the steps.

my bad, it's not an issue, just found out ids-toolbar has `tabbable` setting what allows all items in the toolbar be focusable

**Comment by andriivarhanov** [comment]
ready for review, recent changes are:
- added 100% test coverage
- added toolbar month range text
- added sticky

**Review by jmacaluso711 — APPROVED** [review]
Looks good

**Review by EdwardCoyle — APPROVED** [review]
Yes, looks really good @andriivarhanov

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
