### PR TITLE
683 - IdsTabs Additional Features

### LINKED ISSUE #683: IdsTabs: Remaining Features/Issues
**Original Issue:** #120
**Previous refactoring work:** #411  / #427

**Major**

- [x] #729
- [x] Add overflow detection feature (may need design review?)
- [x] Dismissible Tabs
- [x] `ids-tab-divider`: Improve accessibility + add aXe tests

**Minor**

- [x] Sortable Behavior ([Example](https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html))
- [ ] test: for keyboard events
- [ ] test: figure out how to get coveralls + Jest to detect certain parts of code
- [ ] test: figure out why ids-tab.selected = false doesn't trigger in Jest
- [x] test: resolve aXe color contrast issues (disabled state, similar to other components)
- [ ] Review current solution for potential optimization (remove extraneous elements and looping)

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR adds several more features into the IdsTabs component:
- Adds dismissible tabs (tab content can be closed by clicking the "X" button on a tab)
- Adds IdsSwappable/IdsTabs integration to enable swappable (formerly "sortable") tabs
- Fixes an accessibility issue with IdsTabsDivider
- Add tests/docs where needed

**Related github/jira issue (required)**:
Closes #683 

**Steps necessary to review your pull request (required)**:
Pull/build/run, then:

http://localhost:4300/ids-tabs/dismissible.html
- Try clicking the "X" button on a tab.  It should be removed from the tab list.
- Use dev tools and find the element that contains Tab Panels: `<div class="ids-tabs-content"></div>`.  The tab panel connected to the removed tab should also have been removed.1

http://localhost:4300/ids-tabs/counts.html
- The visual style of these tabs should be unchanged, except for the dismissible ones.
- Try navigating these tabs with the arrow keys.  The arrow keys should not become stuck inside each divided area.  Instead keyboard navigation should wrap around to the first/last tabs if needed.
- Clearing these tabs should act the same as the first example.

http://localhost:4300/ids-tabs/module.html
- Use the "+" actionable tab to add a new tab.  It should have an "X" button
- Clearing these tabs should act the same as the first example.

http://localhost:4300/ids-tabs/swappable.html
- Hovering these tabs should display a "swappable" state with a drag handle
- Dragging/ordering tabs should behave as expected

Also, smoke test the following to ensure no visual/behavioral changes:
- http://localhost:4300/ids-tabs/header-tabs.html
- http://localhost:4300/ids-tabs/vertical.html
- http://localhost:4300/ids-swappable/example.html
- http://localhost:4300/ids-list-builder/example.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — COMMENTED** [review]
Just a couple comments feel free to defer. 

1. With the percy tests 
a) i tried to fix the listbuilder missing on my PR (datagrid) maybe you can try to add the same code: https://github.com/infor-design/enterprise-wc/pull/782/files#diff-5b56e2bcb064c103728a91d3f66e66e10669dad8bbf6e0aeb19794369fc7c285R8 
b) whats the problem/change with the icons that seems unrelated?
2. no any of the dismissible examples http://localhost:4300/ids-tabs/counts.html can we make backspace/delete remove it when focused? so there is keyboard support?
3. On http://localhost:4300/ids-tabs/module.html i can click and focus the disabled attachment tab
4. on http://localhost:4300/ids-tabs/swappable.html if i try to drag the last tab i cant see the text when i drag. I think that would be better so you can see the tab name you are dragging.
5. Can we get rid of the green drop icon when dropping this can be done like this:
https://github.com/infor-design/enterprise-wc/pull/782/files#diff-3a110fc62c39cb0fbf614a19ccb00fcb78c13fc87a9263b4552b5b75cf304a5fR606-R610

**Review by deep7102 — DISMISSED** [review]
🍌 Looks good!
Not related, but just wondering about the disable tab behavior, why it is focus-able.

**Comment by tmcconechy** [comment]
@EdwardCoyle 
Ok make some todos as you  need to. The thing that wont link is just this: You change the icon in the dragover. 

```
    this.onEvent('dragover.resize', header, (e: DragEvent) => {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      e.dataTransfer!.dropEffect = 'move';
      e.preventDefault();
    });
 ```   
 
This could go in ids-swappable.

Maybe to better customize the icon you can use this code from my PR where you clone the image and customize it (i append it in the same container so it gets styles but its off screen:

```
this.onEvent('dragstart.resize', header, (e: DragEvent) => {
 ....
      dragger = target.parentNode.cloneNode(true);
      dragger.classList.add('dragging');
      dragger.style.position = 'absolute';
      dragger.style.top = '0';
      dragger.style.left = '-1000px';

      this.header.appendChild(dragger);
      e?.dataTransfer?.setDragImage(dragger, this.locale.isRTL() ? 100 : 10, 18);
      target.style.position = 'absolute';
 ....
    });
```

FYI ended up not using swappable on mine.

**Comment by tmcconechy** [comment]
Also maybe the icons are some change like a chrome version so maybe i'll just accept

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
