### PR TITLE
IdsCalendar - Improvements to Event Customization

### PR DESCRIPTION
**Pull request by manoj-kothuri**
Implemented logic to override the default calendar event with custom calendar multiline event display and also added logic to display number of event pills in a day cell with dynamic count.

**Related github/jira issue (required):**
"Fixes https://github.com/infor-design/enterprise-wc/issues/911"

**Steps necessary to review your pull request (required):**

Checkout branch, npm run start
Go to http://localhost:4300/ids-calendar/example-custom.html
Added new example specific for IdsCalendarEvent overriding in ids-custom-calendar-event.ts and added new class ids-custom-calendar-event-manger.ts under IDS Calendar demos to handle multiline event pill display along with number of event pills to be displayed in a day cell.
The following is the screenshot for the above mentioned calendar event overriding.

Custom Calendar Event

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Comment by jdilag90** [comment]
Looks good...some issues I found

1) Switch view to `Week View`, then switch back to `Month View`. More events are visible and overlap each other in day cells Oct 21st and 22nd. Overflow count is covered.

before view switch
calendar-before-viewswitch

after view switch
calendar-after-viewswitch

2) Resize browser to narrower width (about <= 1140px). Event pill on the 26th has text cut off.
calendar-resize-narrow

3) Resize browser to wider width (>= 1600px). Event time and title are displayed inline. Not sure if intended
calendar-resize-wide

**Review by tmcconechy — COMMENTED** [review]
From a "checking the boxes" perspective...

a) can you add a change log (should indicate what in the calendar API changes/ relavent additions for other uses)
b) do we need some sort of a test for this?

**Comment by manoj-kothuri** [comment]
> Looks good...some issues I found
> 
> 1. Switch view to `Week View`, then switch back to `Month View`. More events are visible and overlap each other in day cells Oct 21st and 22nd. Overflow count is covered.
> 
> before view switch calendar-before-viewswitch
> 
> after view switch calendar-after-viewswitch
> 
> 2. Resize browser to narrower width (about <= 1140px). Event pill on the 26th has text cut off.
> 
> calendar-resize-narrow
> 
> 3. Resize browser to wider width (>= 1600px). Event time and title are displayed inline. Not sure if intended
> 
> calendar-resize-wide

For the first issue we are going to handle that using the "beforeeventsrendered" and "aftereventsrendered" event listeners introduced by @tmcconechy in IdsMonthview to overcome this issue.

Regarding the second and third points as of now we haven't handled the text resizing with respect to Responsiveness. As of now our prime focus to do the event pill customizations which we did and will be looking into handling this issues as well.

**Comment by manoj-kothuri** [comment]
> From a "checking the boxes" perspective...
> 
> a) can you add a change log (should indicate what in the calendar API changes/ relavent additions for other uses) b) do we need some sort of a test for this?

As suggested added the change log under ## 1.0.0-beta.7 and we do have a test class for this namely 'custom-calendar-event-func-test.ts'

**Comment by tmcconechy** [comment]
@manoj-kothuri so this now contains the code from https://github.com/infor-design/enterprise-wc/pull/1143 ? If so should we include it all including the new docs or just merge it first as good to go and then merge here?

Also i see a lint error to fix https://github.com/infor-design/enterprise-wc/actions/runs/4251975940/jobs/7394994474

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri so this now contains the code from #1143 ? If so should we include it all including the new docs or just merge it first as good to go and then merge here?
> 
> Also i see a lint error to fix https://github.com/infor-design/enterprise-wc/actions/runs/4251975940/jobs/7394994474

I synced the forked repository to get the latest changes but I couldn't find the event listeners you have added. So, I have included them in my code base and worked on the example. So you can merge all the new docs and relevant code changes of ours.

I fixed the above lint issue as well.

**Comment by tmcconechy** [comment]
Ok i see. I merged the new event listeners so you can have them now and test them with this. Needs merging...

Thanks!

**Comment by tmcconechy** [comment]
@manoj-kothuri just a merge conflict to fix. Can you sync with main?

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri just a merge conflict to fix. Can you sync with main?

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri just a merge conflict to fix. Can you sync with main?

@tmcconechy  I synced the branch with main.

**Review by tmcconechy — DISMISSED** [review]
Looks good to me ...

**Comment by jdilag90** [comment]
@manoj-kothuri  Seeing some errors in console after switching back and forth between month and week/day views

calendar-errors

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri Seeing some errors in console after switching back and forth between month and week/day views
> 
> calendar-errors

Fixed the above mentioned issue

**Review by jdilag90 — APPROVED** [review]
Looks good thanks

**Review by tmcconechy — APPROVED** [review]

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
