### PR TITLE
Custom Calendar multiline event display with dynamic count

### LINKED ISSUE #911: IdsMonthView: Add ability to extend and use customized calendar events
**Is your feature request related to a problem or use case? Please describe.**
The IdsMonthView is hard coded to utilize a IdsCalendarEvent Web Component to display each event on the calendar. This isn't very flexible and doesn't allow such customizations as multi-line events, custom colors and other pill options.

**Describe the solution you'd like**
Ideally, we could provide our own Web Component that inherits from the IdsCalendarEvent and overrides the Template or any other methods required. This would allow multi-line text, different icon placement, as well as any other scenario's in the future. 

image

With a quick look at ids-month-view.ts, a couple issues will arise:

- MAX_EVENT_COUNT is hard-coded to 3. If multi-line event pills are allowed, the isOverflowing logic will need to be changed. Possibly add lineCount to idsCalendarEvent defaulted to 1. Override in subclass.
- Multi-Day Events
- Currently hard-coded to IdsCalendarEvent. Needs to be extendable.

**Describe alternatives you've considered**
We could try manually modifying the calendar after rendering. However this is not a sustainable approach as with each update we have a higher chance of breaking something in our application. Providing a extendable framework would allow the IDS library to control most of the code, while allowing unique UI use cases on a per-application basis. 

**Additional context**
**!!Only worrying about the event pill in this ticket!!**
image
image
image

And what application do you work on? Infor WFM

### PR DESCRIPTION
**Pull request by manoj-kothuri**
IDS Calendar Event Customization

Implemented logic to override the default calendar event with custom calendar multiline event display and also added logic to display number of event pills in a day cell with dynamic count.

**Related github/jira issue (required)**:
"Fixes #911"

**Steps necessary to review your pull request (required)**:

1. Checkout branch, npm run start
2. Go to http://localhost:4300/ids-calendar/example-custom.html
3. Added new example specific for **IdsCalendarEvent** overriding in **ids-custom-calendar-event.ts** and added new class **ids-custom-calendar-event-manger.ts** under IDS Calendar demos to handle multiline event pill display along with number of event pills to be displayed in a day cell.
4. The following is the screenshot for the above mentioned calendar event overriding.

Custom Calendar Event

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@manoj-kothuri a couple of things..

1) if you look inline on https://github.com/infor-design/enterprise-wc/pull/1115/files see some warnings
2) some tests are failing
3) for all files in demos folder can you not have the name "ids" in the start of the name because this will cause the file to end up in the npm build... Might need to confirm this on my branch but seems right. i.e. anything in demos doesnt need ids in front

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri a couple of things..
> 
> 1. if you look inline on https://github.com/infor-design/enterprise-wc/pull/1115/files see some warnings
> 2. some tests are failing
> 3. for all files in demos folder can you not have the name "ids" in the start of the name because this will cause the file to end up in the npm build... Might need to confirm this on my branch but seems right. i.e. anything in demos doesnt need ids in front
> 4. can you add an entry to docs/change.log in the beta 4 section?

- I have fixed the jsdoc warnings.
- Renamed the files under demos as suggested. (Removed prefix "ids")
- Added change log entry under beta 4 section.

**Review by tmcconechy — APPROVED** [review]
Can also rename the test ids-custom-calendar-event-func-test.ts to drop the ids.. Otherwise looks good.

@jdilag can you take a peek?

**Comment by jdilag90** [comment]
Looks good...few things

* If you add the view-picker setting `<ids-calendar id="custom-calendar" date="10/22/2019" show-details view-picker>` to your `example-custom.html`, there are errors switching to different views (week/day)


* In `example-custom.ts`, there is `noOfAttributes` and `attrs`...is it possible to remove noOfAttributes and just use `attrs.length` instead? It'd be one less event type property to maintain


* On the 25th day cell, looks like there is more space between the two events than there is on the 31st day cell events, not sure if that's intended
calendar

**Comment by tmcconechy** [comment]
@manoj-kothuri made some other PRs merged ~ can you check the merge conflict now. Also see previous comments 👍🏻

**Comment by manoj-kothuri** [comment]
> @manoj-kothuri made some other PRs merged ~ can you check the merge conflict now. Also see previous comments 👍🏻

sure thing

**Pull request closed without merging**
