### PR TITLE
Chore: Fix a duplicate percy test name

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**
One Test had a duplicate name, this caused some test errors on builds.

**Related github/jira issue (required)**:
NA

**Steps necessary to review your pull request (required)**:
- will merge if tests pass

### CODE REVIEW

**Review by vivz753 — APPROVED** [review]
A new screenshot got added, is that intended?

**Comment by tmcconechy** [comment]
@vivz753  Yes thats correct because i renamed one now would be a new one for app-menu. I approved it

**Comment by vivz753** [comment]
This was already addressed in @jeffwa428's PR FYI

https://github.com/infor-design/enterprise-wc/pull/474/files

**Comment by tmcconechy** [comment]
yep @vivz753 thats because i wanted this on main faster in case it effects someone else. It will merge ok since its the same fix. Me and him collaborated on this fix.

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
