### PR TITLE
643 - Add keyboard API and more e2e and 100% test coverage

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR makes the following notable changes:

- Cleans up the style lint plugin and make it use public defaults - fixing all errors (@EdwardCoyle saw something on your PR you may want to revert when you get this)
- Adds type option to ids-label so i can make h1/h2 labels. (@jmacaluso711 label works but didnt add the for yet and test inputs)
- Moved ids-layout grid standalone css to own example
- Made tag page pass Axe (accessibility)
- Added CSP header to ensure we are doing anything wrong (like inline js or styles)
- Added `npm run test:watch` mode which is useful for active test writing
- Updated many dependencies
- Changed uglify to terser - this was needed to support source maps and have CSP work
- Added Ids Keyboard Mixin - this adds keyboard support for components - see ids-tags for details
- Cleanup ids-input and ids-label as some methods would set the attributes and then revert
- Added 100% test coverage (lets keep this going)
- Added e2e tests for image regression and CSP/Error Checks and axe (see tags)
- 
**Related github/jira issue (required)**:
Fixes infor-design/enterprise@643

**Steps necessary to review your pull request (required)**:
- try `npm run test`
- try `npm run lint`
- try `npm run test:watch`
- test the ids tags and kitchen sink page
- note changes

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Comment by tmcconechy** [comment]
Quick Update - i thought using SSIM the images would work on both CI and Mac but i was wrong. Looking for a solution for the failing test. Rest is ready to revie

**Comment by tmcconechy** [comment]
This pr is ready to review - have a look at the percy review process. I think this is going to work nicely.

**Comment by deep7102** [comment]
Getting js error on demo app

image

**Comment by tmcconechy** [comment]
Pushed a fix - good catch @deep7102

**Review by deep7102 — APPROVED** [review]
🍌 Looks good!

**Review by EdwardCoyle — APPROVED** [review]
:banana: love watch mode on the tests!

**Pull request merged**
