### PR TITLE
2583 - Add fix for splitter text issue

### LINKED ISSUE #2583: IdsSplitter: Content is overlapping between splitter panes
**Describe the bug**
when moving the splitter around content is overlapping between splitter panes

**To Reproduce**

1. Go to (https://main.wc.design.infor.com/ids-splitter/expand-collapse.html
2. move the splitter to the left
3. See overlapping content

**Expected behavior**
content should not overlap between split panes

**Version**

- ids-enterprise-wc: 1.3.0

**Screenshots**
image

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Additional context**

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes an issue where text overflows on the pane

**Related github/jira issue (required)**:
Fixes #2583 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4300/ids-splitter/expand-collapse.html
- collapse the splitter
- text should not be visible
- drag the sides

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by jbrcna — DISMISSED** [review]
image

**Review by glenlieorillo — APPROVED** [review]
https://github.com/user-attachments/assets/d75f994b-4670-4a29-b7d0-c30d22e3e95b

**Review by janahintal — APPROVED** [review]
Working as expected in http://localhost:4300/ids-splitter/expand-collapse.html

**Comment by pwpatton** [comment]
@tmcconechy There seems to be an issue here the children tree node text is truncating to early.

image

**Comment by tmcconechy** [comment]
@pwpatton I think this is ok as its based on the actual contents where`padding-x` is added. But we dont want to remove that or we dont get the padding on the other side and it screws up the layout. You can probably rearrange the markup for the layout grid or you may not see this. But it is working according to how the child ids-layout grid works

```
<ids-layout-grid auto-fit="true" padding-x="sm">
   <ids-layout-grid-cell>
       <ids-tree id="tree" label="Tree"></ids-tree>
   </ids-layout-grid-cell>
</ids-layout-grid>
```

**Pull request merged**
