### PR TITLE
700 - Add IdsSearchField remaining features

### LINKED ISSUE #700: IdsSearchField: Remaining Features/Issues
**Original Issue:** #314

**Major:**

- [ ] Add responsive behavior (opt-in via boolean attribute) for existence within Toolbars or other containers [(example)](https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html) - includes a focusable "collapse" button for accessibility. (Skip go button just the mobile look)
- [ ] Check dark/contrast theme colors for `app-menu` color variant
- [x] Check Figma for New or conflicting Designs https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.5?node-id=760%3A771&t=Hn2ppFMeWdP3xPLC-0 

**Minor:**

- [x] Check dark/contrast theme colors for `alternate` variant
- [x] Add categories functionality (named slot? + dropdown or menu button + callbacks/events for menu selection) [("short categories" example)](https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-short.html) [("full categories" example)](https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html)
- [x] Side-by-side Example
- [ ] Standalone CSS Example

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR adds Categories feature to IdsSearch field and updates styles to match new Figma designs.

```html
<ids-search-field label="Categories" category="Files" clearable></ids-search-field>
<ids-search-field label="Categories - Multiple" category="Files" multiple></ids-search-field>
<ids-search-field label="Categories - Short"  id="categories-short"></ids-search-field>
```

```js
document.querySelector('ids-search-field[category]')?.categories = ['Images', 'Documents', 'Audio', 'Video'];
document.querySelector('ids-search-field[multiple]')?.categories = ['Images', 'Documents', 'Audio', 'Video'];
document.querySelector('#categories-short')?.categories = ['Images', 'Documents', 'Audio', 'Video'];
```

**Related github/jira issue (required)**:

Closes #700 

**Steps necessary to review your pull request (required)**:

1. Check out branch and run: `nvm use && npm run start`
2. Check against [Figma Designs](https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.5?type=design&node-id=29037-60326&t=DLBsHpELr5hmfC5A-0)
3. Open http://localhost:4300/ids-search-field/example.html
4. Open http://localhost:4300/ids-search-field/side-by-side.html
5. Run tests to ensure they all pass: `npx jest -- search-field-func-test`

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — CHANGES_REQUESTED** [review]
@clayinfor I know this is WIP but some suggestions having reviewed it so far

Bugs:
- on the single select example when i select an item it should close (the multiple stays open until you click out
- if i pick a longer item the popup gets messed up
Screenshot 2023-05-22 at 10 16 01 AM
- if i tab into the category field to use the keyboard the focus state looks a bit off
Screenshot 2023-05-22 at 10 16 25 AM
- if i select several items the selected text is returning with square brackets ~ you maybe copied a bug from the old version. Its supposed to use translated text selected (locale.translate('Selected') and the square brackets means it wasnt found
Screenshot 2023-05-22 at 10 17 11 AM
- i think we need to omit an event when you select. So maybe just catch the `selected` and `deselected` events and fire them up to the searchfield so they get a notification and show that in the example?

Overall looks really good. Just some nitpicks/bugs/suggestions on initial review

**Comment by danielortiz1982** [comment]
@clayinfor When you have a moment can you provide an update on @tmcconechy feedback. Thanks!

**Comment by clayinfor** [comment]
hey @tmcconechy , thanks for the feedback.  I've correct # 2 and # 4 and am now working on fixing responsiveness... will also add some documentation.

**Comment by tmcconechy** [comment]
@clayinfor small note when you done, can you make the changelog in a section beta.12 because i released twice for some fixes so thats where this will end up

**Comment by jdilag90** [comment]
Hey Clay, it's looking good! Just a heads up, it looks like the autocomplete dropdown popup alignment is a bit off now.
You can compare it with the `Autocomplete Search Bar` [example on main](https://main.wc.design.infor.com/ids-search-field/example.html)

Autocomplete search
autocomp-align

Cateogories search with autocomplete setting enabled
autocomp-align2

**Review by tmcconechy — APPROVED** [review]

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
