### PR TITLE
1658 - IdsNotificationBanner message attribute not working in Angular

### LINKED ISSUE #1658: IdsNotificationBanner: Dynamic Creation in Angular & Dynamic Text
**Description:**

Providing a dynamic value to the message field of the notification banner web component through a typescript variable in the html does not work and is not recognized by the component, which shows the default text in the banner. Additionally, adding the component dynamically through typescript as shown in the example here: https://design.infor.com/code/wc-beta/latest/ids-notification-banner does not render the component in Angular, and also does not solve the need of assigning methods for responding to events e.g. tracking when the banner was closed.

**Code**

1. Dynamic text for banner

HTML
```
       <ids-notification-banner
            (afterNotificationRemove)="onBannerRemoved()"
            *ngIf="filteredGridObjects.length"
            message-text="{{ testBanner }}"
            type="error"
        ></ids-notification-banner>
```

TypeScript

```
 testBanner: string = 'Test banner text';
```

2. Dynamic notification banner:

As in example: https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-notification-banner/demos/dynamic.ts#L12

Tried using this code in all Angular lifecycle methods, but the component renders only if added in the AfterViewCheck method, which shouldn't be used for this matter. 

**Version**
Angular v16
ids-enterprise-wc: "^1.0.0-beta.16",

**Example Result for dynamic banner message**

image

### LINKED ISSUE #1888: Notification banner dynamic variables in message-text for angular
**Describe the bug**
When I'm trying to use notification-banner to show a dynamic variable I have to use [attr.message-text]="errorMessages" to make it work. 
```
<ids-notification-banner
        id="error-message-for-configuration"
        type="error"
        [attr.message-text]="errorMessages">
      </ids-notification-banner>
```

**To Reproduce**
To reproduce it write where errorMessages is a variable like: 

let errorMessages = 'This is my perfect error message I would like to show'
```
<ids-notification-banner
        id="error-message-for-configuration"
        type="error"
        message-text="errorMessages">
        hidden="{{errorMessages.length === 0}}"
      </ids-notification-banner>
```

Add a notification banner to any page where you can use it and change between 'message-text' and '[attr.message-text]'

**Expected behavior**
I would like to see my message 'This is my perfect error message I would like to show' when I use a dynamic variable in message-text. 

**Version**
    "ids-enterprise-wc": "^1.0.0-beta.21" and angular version ^17.2.1

**Screenshots**

**With message-text:**
Screenshot 2024-02-23 at 08 59 59

**With [attr.message-text]:**
Screenshot 2024-02-23 at 08 59 36

**Platform**
 - Infor Application/Team Name: M3Portals
 - Device: Macbook Pro
 - OS Version: Somana 14.2.1
 - Browser Name: Chrome
 - Browser Version: Version 121.0.6167.184 (Official Build) (x86_64)

### LINKED ISSUE #2087: IdsNotificationBanner: Not updating valuing when value changes
**Describe the bug**
When I calculate the error to show in the notification banner it does not change value.

**To Reproduce**
Use this: 
where the list of errorMessages = ['Field 'HEI' is invalid.']
```
    <ids-layout-grid-cell>
      <ids-notification-banner
        *ngIf="errorMessages.length > 0"
        id="error-message-for-configuration"
        type="error"
        [attr.message-text]="errorMessages"
      >
```

When I change programaticly so it removes it error code since everything is correct the notification banner do not update itself.  (I use [attr.message-text] because of: https://github.com/infor-design/enterprise-wc/issues/1888)

**Expected behavior**
I want when I have no error messages to update the banner so I do not have any errors.

**Version**
- ids-enterprise: 1.0.0-beta.21

**Screenshots**
First image when I have my error and then my ids-editor is red for the invalid value:
Screenshot 2024-03-20 at 11 20 14
Here I have validated and have no errors, but my ids-notification-banner still shows error: 
Screenshot 2024-03-20 at 11 20 22

**Platform**
 - Infor Application/Team Name: M3Portals
 - Device: Macbook Pro
 - OS Version: Sonoma 14.4
 - Browser Name: Chrome
 - Browser Version: Version 122.0.6261.129 (Official Build) (x86_64)

**Additional context**

### PR DESCRIPTION
**Pull request by clayinfor**
**Explain the details for making this change. What existing problem does the pull request solve?**

Fixes bug where notification-banner's message-attribute was not recognizing dynamic class properties in Angular.

**Related github/jira issue (required)**:

Closes #1658
Closes #1888   
Closes #2087

**Steps necessary to review your pull request (required)**:

1. Check out this branch and run: `nvm use && npm install && npm run start`
2. Ensure no regressions here: http://localhost:4300/ids-notification-banner/dynamic.html
3. In another terminal window, and run `npm run publish:link`
4. Then check out this branch: https://github.com/infor-design/enterprise-wc-examples/pull/61
5. Then run: `npm install && npm link ids-enterprise-wc`
6. Then run: `rm -fr .angular/cache && npm run build && npm run start`
7. Then confirm trigger button works here: http://localhost:4200/ids-notification-banner/dynamic

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by jdilag90 — DISMISSED** [review]

**Review by jmacaluso711 — APPROVED** [review]

**Comment by tmcconechy** [comment]
@clayinfor I think this fixes https://github.com/infor-design/enterprise-wc/issues/2087 do you agree?

**Review by tmcconechy — CHANGES_REQUESTED** [review]
1. Can you check and show messageText setting too?
2. I noticed on http://localhost:4300/ids-notification-banner/dynamic.html all the links show the button twice. Not a new bug but wierd and should be investigated

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise-wc/issues/1888 also seems like a duplicate does this fix it too? lets check

**Comment by clayinfor** [comment]
hey @tmcconechy , this PR should close the 3 tickets you mentioned:
Closes #1658
Closes #1888   
Closes #2087

**Review by tmcconechy — APPROVED** [review]

**Pull request merged**
