### PR TITLE
507 - Fix ripple width on button

### PR DESCRIPTION
**Pull request by jeffwa428**
**Explain the details for making this change. What existing problem does the pull request solve?**
Fix ripple effect on button when it has big width.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-wc/issues/507

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

### CODE REVIEW

**Review by danielortiz1982 — COMMENTED** [review]
This looks great @jeffwa428 however I am seeing one failing test. I am not sure if this is your change or not.
Screen Shot 2022-02-04 at 10 57 06 AM

**Review by tmcconechy — APPROVED** [review]
@danielortiz1982 i didnt see that test fail - could it be a one off event?

**Comment by danielortiz1982** [comment]
@tmcconechy I think the test was fixed in commit [fb6f418](https://github.com/infor-design/enterprise-wc/pull/540/commits/fb6f418d97526d4729f36a15aada18c8dca30173)

**Review by danielortiz1982 — APPROVED** [review]
@jeffwa428 This PR look good to go! Thanks for fixing the test in commit [fb6f418](https://github.com/infor-design/enterprise-wc/pull/540/commits/fb6f418d97526d4729f36a15aada18c8dca30173). Good job on cleaning up this button ripple looks much better now. 👌
Screen Shot 2022-02-07 at 7 40 33 AM

**Pull request merged**
