### PR TITLE
554 - Standalone css / Css Var Cleanup

### LINKED ISSUE #554: Standalone Css: Make faster / More module / And Fix Demos
**Describe the bug**
After #311 the standalone css wont work right away and we need to fix...

**Tasks**
- dont change root to host https://github.com/infor-design/enterprise-wc/blob/main/webpack.config.dist.js#L133-L147
- put the css variables under the container element (fx .ids-tag) instead of host so it works in both standalone css and demos
- use sass use command and make sass modules for colors / sizes and different variable groups so you can import less (200 lines to just whats needed as an example) modules TBD

**Expected behavior**
-  standalone css demos work
- standalone css work as a library
- no slower

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**

This PR makes all the standalone css examples work again. I was able to do this by just using the assets pipeline in webpack and updating the examples.

In addition i added a new sass map with all the variables and a function that can filter the map to limit the rules. Also found some un-needed things in each components. Which was moved to a hide-mixin.sass. I think we have another option to this i'll go over next team call. But this seems useful so left it in

**Related github/jira issue (required)**:
Closes #554

**Steps necessary to review your pull request (required)**:

*Standalone Css - the following pages can be tested*
- [ ] http://localhost:4300/ids-about/standalone-css.html
- [ ] http://localhost:4300/ids-breadcrumb/standalone-css.html
- [ ] http://localhost:4300/ids-button/standalone-css.html
- [ ] http://localhost:4300/ids-card/standalone-css.html
- [ ] http://localhost:4300/ids-checkbox/standalone-css.html
- [ ] http://localhost:4300/ids-counts/standalone-css.html
- [ ] http://localhost:4300/ids-data-grid/standalone-css.html
- [ ] http://localhost:4300/ids-fieldset/standalone-css.html
- [ ] http://localhost:4300/ids-header/standalone-css.html
- [ ] http://localhost:4300/ids-image/standalone-css.html
- [ ] http://localhost:4300/ids-input/standalone-css.html
- [ ] http://localhost:4300/ids-layout-grid/standalone-css.html
- [ ] http://localhost:4300/ids-list-view/standalone-css.html
- [ ] http://localhost:4300/ids-message/standalone-css.html
- [ ] http://localhost:4300/ids-month-view/standalone-css.html
- [ ] http://localhost:4300/ids-popup-menu/standalone-css.html
- [ ] http://localhost:4300/ids-progress-bar/standalone-css.html
- [ ] http://localhost:4300/ids-radio/standalone-css.html
- [ ] http://localhost:4300/ids-switch/standalone-css.html
- [ ] http://localhost:4300/ids-tabs/standalone-css.html
- [ ] http://localhost:4300/ids-tag/standalone-css.html
- [ ] http://localhost:4300/ids-textarea/standalone-css.html
- [ ] http://localhost:4300/ids-toolbar/standalone-css.html
- [ ] http://localhost:4300/ids-tooltip/standalone-css.html
- [ ] http://localhost:4300/ids-week-view/standalone-css.html

*Css Var Cleanup*
- see the "api" i converted in cards
- go to http://localhost:4300/ids-card
- inspect the ids-card element and look at the `:host` rules

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.

### CODE REVIEW

**Review by danielortiz1982 — DISMISSED** [review]
good find! ❤️

**Comment by tmcconechy** [comment]
Working on the tests - had a segmentation fault but i figured it out. Need to run this a few times to sort out

**Comment by tmcconechy** [comment]
Making some css property fixes...

**Review by deep7102 — DISMISSED** [review]
Looks good 🍌

**Review by andriivarhanov — COMMENTED** [review]
looks good, the only thing I noticed is ids-image standalone css is missing http://localhost:4300/ids-image/standalone-css.html

**Comment by tmcconechy** [comment]
@andriivarhanov i had removed it as it was broken badly. But went and fixed it so its there now. Also so the colors where missing in standalone css. So should be good now

**Review by andriivarhanov — APPROVED** [review]
looks great 👍

**Review by deep7102 — APPROVED** [review]

**Pull request merged**
