### PR TITLE
1518/1536 - Add IdsModuleNav responsive behavior and finalize design/features

### LINKED ISSUE #1518: IdsModuleNav: Add new mobile behavior
**Describe the bug**
Need to add same mobile behavior as Enterprise. 

https://github.com/infor-design/enterprise/issues/8019
and
https://github.com/infor-design/enterprise/issues/7804

**To Do**

- [x] Clean up example https://github.com/infor-design/enterprise-wc/issues/1417#issuecomment-1746854664
- [x] Add breakpoints setting
- [x] On mobile it will hang over with an overlay (will do it on resize and page load)
- [x] Clicking on mobile will close the menu
- [x] Mobile by default (no conflicting settings)

### LINKED ISSUE #1536: ModuleNav: Add additional Missing Features
**Describe the bug**

- [x] Add new mobile behaviors ([#1518](https://github.com/infor-design/enterprise-wc/issues/1518))
- [x] What else? (need to check through a bit) -> check last few PR's
- [x] Demo page should use mobile behavior and have a few less settings
- [x] Alignment - https://github.com/infor-design/enterprise/issues/7934 - is this ok

### PR DESCRIPTION
**Pull request by EdwardCoyle**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR completes the IdsModuleNav per its specification, and brings it into feature-parity with the Soho components.

**Related github/jira issue (required)**:
Closes #1518
Closes #1536

**Steps necessary to review your pull request (required)**:
Pull/build/run, then test the following:

_New Example Page:_
- Open http://localhost:4300/ids-module-nav/example.html
- Use the hamburger button to expand/collapse the module nav.  Try this at different breakpoints.  When opening the Module Nav when the viewport is below 840px, an overlay should appear and the "content" area will be overlapped by the Module Nav.  Clicking inside the overlay area should dismiss the Module Nav.  Clicking the hamburger button should re-open it.
- In collapsed mode, the Module Nav Button, all module nav items, and the settings button should all generate a tooltip
- In expanded mode, only Module Nav items with text-ellipsis should generate a tooltip.  All other elements should not.
- Try opening the settings menu, role switcher, and tooltips on RTL reading modes.  All these elements should display and be usable.
- Review the general Module Nav appearance and ensure it matches [its Soho counterpart](https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff) -- Module Nav's [Figma file](https://www.figma.com/file/bL4EBYtWjgfBsvTVI9seXU/branch/eHul2nKNMdypFLSb55ZwR1/Module-Nav-%7C-Application-Menu?type=design&node-id=3161-29750&mode=design&t=sjN1N5PPMs7CNJNJ-0) may be useful

_Sandbox Page:_
- Open http://localhost:4300/ids-module-nav/sandbox.html
- Try all the various settings and make sure the combinations make sense.

_6-Level Depth and alignment:_
- Review both http://localhost:4300/ids-module-nav/nesting-with-icons.html and http://localhost:4300/ids-module-nav/nesting-no-icons.html.  Ensure the nesting depth is present and makes visual sense.

_Additional tests:_

Review all Popup-related settings for accuracy, especially on RTL:

- http://localhost:4300/ids-popup/sandbox.html

Smoke test these items and make sure context menus open properly on RTL:
- http://localhost:4300/ids-popup-menu/scrolling.html
- http://localhost:4300/ids-data-grid/contextmenu.html (right click inside cells and activate submenus)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

### CODE REVIEW

**Review by tmcconechy — APPROVED** [review]
Everything looks good to me. The only thing i was wondering if if the hamburger should show a tooltip.

@talkaboutdesign do you guys want to re-qa this on the web component side?

**Review by jdilag90 — APPROVED** [review]
Looks great!

**Comment by talkaboutdesign** [comment]
can you update links for review? I can't get preview links to work.

**Comment by tmcconechy** [comment]
@talkaboutdesign we dont have the preview links working in this repo yet. But you can review here https://main.wc.design.infor.com/ids-module-nav/ and comment and we'll fix subsequently.

**Pull request merged**
