### PR TITLE
Chore: Update icons

### PR DESCRIPTION
**Pull request by tmcconechy**
**Explain the details for making this change. What existing problem does the pull request solve?**
This PR goes along with https://github.com/infor-design/enterprise/issues/6868 but for the WC repo instead. 

- icons have 2px top and bottom padding, making them "smaller"
- many new icons have been added
- new empty state icons http://localhost:4300/ids-empty-message/example.html

This worked well on my tests locally but expecting many image tests and need to see test output.

Also expecting https://github.com/infor-design/enterprise-wc/pull/975 to be merged first so this may need updating for the package.lock

**Related github/jira issue (required)**:
https://github.com/infor-design/enterprise/issues/6868

**Steps necessary to review your pull request (required)**:
- look at any / everything icon related
- but the tests should do a good job uncovering anything, especially look at the test output for percy for "errors" or layout issues

**Included in this Pull Request**:
- [x] A note to the change log.

### CODE REVIEW

**Review by andriivarhanov — COMMENTED** [review]
it looks like `first-page` icon has wrong direction http://localhost:4300/ids-pager/example.html, everything else looks good, just smaller

**Comment by tmcconechy** [comment]
ok @andriivarhanov added a fix for the pager issue and also this included updates to empty state icons http://localhost:4300/ids-empty-message/example.html

**Review by andriivarhanov — APPROVED** [review]
looks good

**Review by jdilag90 — APPROVED** [review]
Looks good, the smaller icons also look better on the calendar events

**Pull request merged**
