### PR TITLE
#1971 - Ids slider conversion

### LINKED ISSUE #1971: Tests: Convert Slider Tests
**Describe the task**
Convert Slider tests from https://github.com/infor-design/enterprise-wc/tree/main/tests-to-convert/ids-slider to https://github.com/infor-design/enterprise-wc/blob/main/tests/ids-slider/ids-slider.spec.ts

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jbrcna**
**Explain the details for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes #1971 

**Steps necessary to review your pull request (required)**:

Run the test suite
Check the code conversion
New converted tests should pass

**Included in this Pull Request**:
- [ ] Some documentation for the feature.
- [ ] A test for the bug or feature.
- [ ] A note to the change log.

**additional context**
``` diff
+ added validations/assertions where appropriate.
+ included a working test for skipping tests.
- discard a missing module createfromtemplate
+ I refer to the goal of the test case title, rather than following the exact script from the previous one.
```

### CODE REVIEW

**Comment by jbrcna** [comment]
I need help on this error  `Cannot find name  'createKeyboardEvent`. I already  tried expose function.

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
You can use `await page.keyboard.press('ArrowUp');` instead.

[Keyboard](https://playwright.dev/docs/api/class-keyboard)

**Review by n-ace-ancog — CHANGES_REQUESTED** [review]
Build is failing due to some test case. 

Try applying [expect.toPass](https://playwright.dev/docs/test-assertions#expecttopass) in your test case.

_sample code:_ everything inside the expect block will be repeated until it passes or a timeout is reached.
```ts
await expect(async () => {
  await tapExpander();
  await expect(idsExpandArea).toHaveAttribute('expanded', 'true');
}).toPass();
```

**Comment by jbrcna** [comment]
I choose not to utilize await page.keyboard.press because I am getting issues.

**Comment by jbrcna** [comment]
this is odd. I'm getting a value of 77 on my end.
image
changing value to 76 now

**Comment by n-ace-ancog** [comment]
@jbrcna update this branch to fix the flaky test on other component. 

For the inconsistent result below, you are trying to move the slider by using the mouse with a static Y coordinate which, maybe is causing the issue. Try to use the `expect().toBeInAllowedBounds()` to give a "room for error" in asserting the value.

**Sample**
```ts
import { test, expect } from '../base-fixture';
// this will still pass if the value of `sliderEl.valueSecondary` is either from 75 to 79
await expect(sliderEl.valueSecondary).toBeInAllowedBounds(77, 2);
```

> this is odd. I'm getting a value of 77 on my end. image changing value to 76 now

**Review by tmcconechy — APPROVED** [review]

**Review by n-ace-ancog — APPROVED** [review]

**Pull request merged**
